### ISSUE TITLE
net core $Expand->$filter Parsing is not supported

### ISSUE THREAD

**Issue by cqkisyouq** [OData/WebApi#1087]
Expression filterSource =
                    typeof(IEnumerable).IsAssignableFrom(source.Type.GetProperty(propertyName).PropertyType)
                        ? Expression.Call(
                            ExpressionHelperMethods.QueryableAsQueryable.MakeGenericMethod(clrElementType),
                            nullablePropertyValue)
                        : nullablePropertyValue;

                Expression filterPredicate = FilterBinder.Bind(filterClause, clrElementType, _context.RequestContainer);
                MethodCallExpression filterResult = Expression.Call(
                    ExpressionHelperMethods.QueryableWhereGeneric.MakeGenericMethod(clrElementType),
                    filterSource,
                    filterPredicate);

$Expand Does not support this   ".AsQuery.Where(xx) "  ef parse error
            var result = _userService.Get(query => query).Select(x=> new UserOutput{
                Account=x.Account,
                Alias=x.Alias,
                Id=x.Id,
                Email=x.Email,
                Name=x.Name,
                Mobile=x.Mobile,
                DisplayOrder=x.DisplayOrder,
                Description=x.Description,
                Enabled=x.Enabled,
                UpdatedOnUtc=x.UpdatedOnUtc,
                CreatedOnUtc=x.CreatedOnUtc,
                Roles=x.Roles.Where(r=>r.Enabled&&r.Deleted==false&&r.Role.Enabled&&r.Role.Deleted==false)
                            .Select(d=>new RoleOutput() {
                                Id=d.Role.Id,
                                ApplicationId=d.Role.ApplicationId,
                                Enabled=d.Role.Enabled,
                                DisplayOrder=d.Role.DisplayOrder,
                                Description=d.Role.Description,
                                CreatedOnUtc=d.Role.CreatedOnUtc,
                                UpdatedOnUtc=d.Role.UpdatedOnUtc
                            }).ToList()
            });

**Comment by biaol-odata** [comment]
@cqkisyouq : Can you also include the 'filterClause' details? Any call stack available for this error? It would be helpful for the investigation. Thanks.

**Comment by cqkisyouq** [comment]
at Remotion.Linq.Parsing.Structure.MethodCallExpressionParser.GetNodeType(MethodCallExpression expressionToParse)
   at Remotion.Linq.Parsing.Structure.MethodCallExpressionParser.Parse(String associatedIdentifier, IExpressionNode source, IEnumerable`1 arguments, MethodCallExpression expressionToParse)
   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseMethodCallExpression(MethodCallExpression methodCallExpression, String associatedIdentifier)
   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseNode(Expression expression, String associatedIdentifier)
   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseMethodCallExpression(MethodCallExpression methodCallExpression, String associatedIdentifier)
   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseTree(Expression expressionTree)
   at Remotion.Linq.Parsing.Structure.QueryParser.GetParsedQuery(Expression expressionTreeRoot)
   at Remotion.Linq.Parsing.ExpressionVisitors.SubQueryFindingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitConditional(ConditionalExpression node)
   at System.Linq.Expressions.ConditionalExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Remotion.Linq.Parsing.ExpressionVisitors.SubQueryFindingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitConditional(ConditionalExpression node)
   at System.Linq.Expressions.ConditionalExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Remotion.Linq.Parsing.ExpressionVisitors.SubQueryFindingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Remotion.Linq.Parsing.ExpressionVisitors.SubQueryFindingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitConditional(ConditionalExpression node)
   at System.Linq.Expressions.ConditionalExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Remotion.Linq.Parsing.ExpressionVisitors.SubQueryFindingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Remotion.Linq.Parsing.ExpressionVisitors.SubQueryFindingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Remotion.Linq.Parsing.ExpressionVisitors.SubQueryFindingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Remotion.Linq.Parsing.ExpressionVisitors.SubQueryFindingExpressionVisitor.Visit(Expression expression)
   at Remotion.Linq.Parsing.ExpressionVisitors.SubQueryFindingExpressionVisitor.Process(Expression expressionTree, INodeTypeProvider nodeTypeProvider)
   at Remotion.Linq.Parsing.Structure.MethodCallExpressionParser.ProcessArgumentExpression(Expression argumentExpression)
   at System.Linq.Enumerable.SelectListPartitionIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Remotion.Linq.Parsing.Structure.MethodCallExpressionParser.Parse(String associatedIdentifier, IExpressionNode source, IEnumerable`1 arguments, MethodCallExpression expressionToParse)
   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseMethodCallExpression(MethodCallExpression methodCallExpression, String associatedIdentifier)
   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseTree(Expression expressionTree)
   at Remotion.Linq.Parsing.Structure.QueryParser.GetParsedQuery(Expression expressionTreeRoot)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at Microsoft.AspNetCore.OData.PageResult`1.System.Collections.IEnumerable.GetEnumerator() in D:\Work\huaqi\Jazea.v2\src\Microsoft.AspNetCore.OData\PageResultOfT.cs:line 65
   at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteResourceSet(IEnumerable enumerable, IEdmTypeReference resourceSetType, ODataWriter writer, ODataSerializerContext writeContext) in D:\Work\huaqi\Jazea.v2\src\Microsoft.AspNetCore.OData\Formatter\Serialization\ODataResourceSetSerializer.cs:line 130
   at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteObjectInline(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext) in D:\Work\huaqi\Jazea.v2\src\Microsoft.AspNetCore.OData\Formatter\Serialization\ODataResourceSetSerializer.cs:line 87
   at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteObject(Object graph, Type type, ODataMessageWriter messageWriter, ODataSerializerContext writeContext) in D:\Work\huaqi\Jazea.v2\src\Microsoft.AspNetCore.OData\Formatter\Serialization\ODataResourceSetSerializer.cs:line 56
   at Microsoft.AspNetCore.OData.Formatter.ODataOutputFormatter.WriteResponseBody(OutputFormatterWriteContext context) in D:\Work\huaqi\Jazea.v2\src\Microsoft.AspNetCore.OData\Formatter\ODataOutputFormatter.cs:line 143
   at Microsoft.AspNetCore.OData.Formatter.ODataOutputFormatter.<>c__DisplayClass3_0.<WriteResponseBodyAsync>b__0() in D:\Work\huaqi\Jazea.v2\src\Microsoft.AspNetCore.OData\Formatter\ODataOutputFormatter.cs:line 54
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

**Comment by cqkisyouq** [comment]
Like this:

 var test = _applicationService.Get(query => query).Select(x => new
            {
                x.Id,
                Clients = x.Clients.AsQueryable().Where(d => d.CreatedOnUtc > DateTime.Now.AddYears(-1)).ToList()
            }).ToList();

The usage is wrong:
 x.Clients.AsQueryable().Where(xxx)

**Comment by robward-ms** [comment]
@cqkisyouq  - Looks like you are using the code in the maintenance-aspnetcore branch, correct? There are a few features not implemented in this branch.  It's likely this feature will not be implemented in this branch.

The feature/netcore branch (https://github.com/OData/WebApi/tree/feature/netcore) is being used to build a netcore version of OData WebApi will feature parity to the existing OData WebApi product. You can follow this work in #975.

**Comment by cqkisyouq** [comment]
Yes. This has been answered by EF, and it is not supported by this method of analysis, but isn't it also used in this way?

**Comment by robward-ms** [comment]
@rmadisonhaynie - See #1221, I'll bet you are using EFCore 2.0.0 which does not support IQueryable. That said, EFCore overall has issues tracked in #669

**Comment by rmadisonhaynie** [comment]
Thank you @robward-ms that is correct.
