### ISSUE TITLE
Delta<TStructuralType> breaks on types with public indexer properties

### ISSUE THREAD

**Issue by kendfrey** [OData/WebApi#1091]
`new Delta<TStructuralType>()` throws an error if `TStructuralType` has a publicly settable indexer.

### Assemblies affected

System.Web.OData v6.0.0

### Reproduce steps

Given an entity type that contains an indexer:

```c#
public class Example
{
    public int this[int index]
    {
        get
        {
            return 0;
        }
        set
        {
        }
    }
}
```

This will fail:

```c#
var delta = new Delta<Example>();
```

### Expected result

A new `Delta<Example>` should be created which doesn't include the indexer as an updatable property.

### Actual result

The constructor throws an `ArgumentException`.

Message:

> Cannot bind to the target method because its signature or security transparency is not compatible with that of the delegate type.

Stack trace:

>    at System.Reflection.RuntimeMethodInfo.CreateDelegateInternal(Type delegateType, Object firstArgument, DelegateBindingFlags bindingFlags, StackCrawlMark& stackMark)
   at System.Reflection.RuntimeMethodInfo.CreateDelegate(Type delegateType)
   at System.Web.Http.Internal.PropertyHelper.MakeFastPropertySetter[TDeclaringType](PropertyInfo propertyInfo)
   at System.Web.OData.FastPropertyAccessor\`1..ctor(PropertyInfo property)
   at System.Web.OData.Delta\`1.<InitializeProperties>b__4(PropertyInfo p)
   at System.Linq.Enumerable.WhereSelectArrayIterator\`2.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable\`1 source, Func\`2 keySelector, Func\`2 elementSelector, IEqualityComparer\`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable\`1 source, Func\`2 keySelector)
   at System.Web.OData.Delta\`1.<InitializeProperties>b__2(Type backingType)
   at System.Collections.Concurrent.ConcurrentDictionary\`2.GetOrAdd(TKey key, Func\`2 valueFactory)
   at System.Web.OData.Delta\`1.InitializeProperties(IEnumerable\`1 updatableProperties)
   at System.Web.OData.Delta\`1..ctor()

### Additional detail

Exception is thrown here:

https://github.com/OData/WebApi/blob/88c5f01f2ee2d685d873b2ab075909b7da6651f1/src/Common/PropertyHelper.cs#L62

Faulty code is here:

https://github.com/OData/WebApi/blob/88c5f01f2ee2d685d873b2ab075909b7da6651f1/src/System.Web.OData/OData/DeltaOfTStructuralType.cs#L445-L451

Suggested fix:

```diff
 _allProperties = _propertyCache.GetOrAdd(
     _entityType,
     (backingType) => backingType
         .GetProperties(BindingFlags.Instance | BindingFlags.Public)
-        .Where(p => (p.GetSetMethod() != null || p.PropertyType.IsCollection()) && p.GetGetMethod() != null)
+        .Where(p => (p.GetSetMethod() != null || p.PropertyType.IsCollection()) && p.GetGetMethod() != null && p.GetIndexParameters().Length == 0)
         .Select<PropertyInfo, PropertyAccessor<TStructuralType>>(p => new FastPropertyAccessor<TStructuralType>(p))
         .ToDictionary(p => p.Property.Name));
```

**Comment by biaol-odata** [comment]
@kendfrey: Thanks for the detailed report.
First, Is this scenario supported in previous versions of the WebApi? The answer will be helpful for us to determine whether this is a regression or new feature ask.
Secondly, I checked the revision history of the file of your suggested changes, it has no recent revisions, and looks like your fix here is to skip the processing if the parameter is associated with indexer. It will be great if you can create a PR along with, ideally, test cases, so that we can have some basic assessment of the fix. Please let me know if it is too much of a hassle for you to create a PR, and at least I can try it out from my dev box. 
Thanks for your support for OData.

**Comment by kendfrey** [comment]
@biaol-odata:

> First, Is this scenario supported in previous versions of the WebApi?

Not as far as I know. It could have been, but I have no reason to think so. This is probably a new feature ask.

> Please let me know if it is too much of a hassle for you to create a PR, and at least I can try it out from my dev box.

I haven't contributed to this repository before, so it would take some time to set up and create a complete PR. I tried to give as much information as possible to make it easy for maintainers to implement. Once I have an idea of this fix's priority for my team, I may decide to work on a PR, if it's important but not being fixed by active maintainers.

**Comment by jamers99** [comment]
What is the status of this?

**Comment by Jamaxack** [comment]
What is the status of this?
