### ISSUE TITLE
[feature/netcore] Bug with OData functions

### ISSUE THREAD

**Issue by gordon-matt** [OData/WebApi#1336]
I've found a bug with **OData functions**. I get HTTP 404 errors.. Here are 2 of them that I am testing at the moment:

```
public class PageVersionApiController : GenericTenantODataController<PageVersion, Guid>
{
    [HttpGet]
    public IActionResult GetCurrentVersion([FromODataUri] Guid pageId, [FromODataUri] string cultureCode)
    {
        // Implementation...
    }
}

public class MessageTemplateVersionApiController : GenericODataController<MessageTemplateVersion, int>
{
    [HttpGet]
    public IActionResult GetCurrentVersion([FromODataUri] int templateId, [FromODataUri] string cultureCode)
    {
        // Implementation...
    }
}
```

The functions are registered as follows:

```
builder.EntitySet<PageVersion>("PageVersionApi");
builder.EntitySet<MessageTemplateVersion>("MessageTemplateVersionApi");
// etc...

var getCurrentVersionFunction = builder.EntityType<PageVersion>().Collection.Function("GetCurrentVersion");
getCurrentVersionFunction.Parameter<Guid>("pageId");
getCurrentVersionFunction.Parameter<string>("cultureCode");
getCurrentVersionFunction.Returns<EdmPageVersion>();
// etc...

var getCurrentVersionFunction = builder.EntityType<MessageTemplateVersion>().Collection.Function("GetCurrentVersion");
getCurrentVersionFunction.Parameter<int>("templateId");
getCurrentVersionFunction.Parameter<string>("cultureCode");
getCurrentVersionFunction.Returns<MessageTemplateVersion>();
// etc...
```

I use the following in Ajax requests:

```
$.ajax({
    url: pageVersionApiUrl + "/Default.GetCurrentVersion(pageId=" + self.id() + ",cultureCode='" + self.parent.currentCulture + "')",
    type: "GET",
    dataType: "json",
    async: false
})
// etc
```

and:

```
$.ajax({
    url: templateVersionApiUrl + "/Default.GetCurrentVersion(templateId=" + self.id() + ",cultureCode='" + self.parent.currentCulture + "')",
    type: "GET",
    dataType: "json",
    async: false
})
// etc
```

Note that this is all code I am migrating from MVC5 to .NET Core with pretty much zero changes.. so it should work, but isn't. Anyway, I decided to try something different and use `[ODataRoute]` attributes. So I added them as follows:

```
public class PageVersionApiController : GenericTenantODataController<PageVersion, Guid>
{
    [HttpGet]
    [ODataRoute("PageVersionApi/Default.GetCurrentVersion(pageId={pageId},cultureCode={cultureCode})")]
    public IActionResult GetCurrentVersion([FromODataUri] Guid pageId, [FromODataUri] string cultureCode)
    {
        // Implementation...
    }
}

public class MessageTemplateVersionApiController : GenericODataController<MessageTemplateVersion, int>
{
    [HttpGet]
    [ODataRoute("MessageTemplateVersionApi/Default.GetCurrentVersion(templateId={templateId},cultureCode={cultureCode})")]
    public IActionResult GetCurrentVersion([FromODataUri] int templateId, [FromODataUri] string cultureCode)
    {
        // Implementation...
    }
}
```

Now something interesting happens: if I only use one of those attributes (not both), then it works... when I use both, then if I go to the page where I am using **PageVersion**, it complains about the path template on **MessageTemplateVersion** and vice versa.

Also, commenting one of the `ODataRoute` attributes out again, and going to any page that uses OData (other than the one related to that function) causes the same error message. Here is the error message and stack trace for you:

```
System.InvalidOperationException: The path template 'PageVersionApi/Default.GetCurrentVersion(pageId={pageId},cultureCode={cultureCode})' on the action 'GetCurrentVersion' in controller 'PageVersionApi' is not a valid OData path template. Resource not found for the segment 'PageVersionApi'.

   at Microsoft.AspNet.OData.Routing.Conventions.AttributeRoutingConvention.GetODataPathTemplate(String prefix, String pathTemplate, IServiceProvider requestContainer, String controllerName, String actionName)
   at Microsoft.AspNet.OData.Routing.Conventions.AttributeRoutingConvention.<>c__DisplayClass11_0.<GetODataPathTemplates>b__0(ODataRouteAttribute route)
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Microsoft.AspNet.OData.Routing.Conventions.AttributeRoutingConvention.BuildAttributeMappings(IEnumerable`1 controllerActions)
   at Microsoft.AspNet.OData.Routing.Conventions.AttributeRoutingConvention.get_AttributeMappings()
   at Microsoft.AspNet.OData.Routing.Conventions.AttributeRoutingConvention.SelectAction(RouteContext routeContext)
   at Microsoft.AspNet.OData.Routing.ODataActionSelector.SelectCandidates(RouteContext context)
   at Microsoft.AspNetCore.Mvc.Internal.MvcRouteHandler.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SaasKit.Multitenancy.Internal.TenantResolutionMiddleware`1.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```

Unless you've purposefully changed things (or things work differently in .NET Core), then I think we shouldn't have to use the `[ODataRoute]` attributes, right? Anyway, that's a minor thing. I don't mind using them so long as there's no errors caused as shown above.

By the way, I suspect issue #1249 (**OData actions** might be due to the same bug as with **OData functions** we see above)

**Comment by gordon-matt** [comment]
**UPDATE**: Ignore #1249 - it was not related as previously thought.

Also, my other **OData functions** seem to be working fine.. it seems to be just these ones that are causing a problem. I don't know if it's because they share the same method name - `GetCurrentVersion` (I think unlikely) or because they have multiple `[FromODataUri]` attributes... or what..

**Comment by gordon-matt** [comment]
Well, I'm not sure what changed, but I no longer have this bug. I did update to the latest nightly recently though.. so not sure if it's that or what, but all seems fine at the moment. Closing this issue for now...
