### ISSUE TITLE
[feature/netcore] OkObjectResult seems to be bugged

### ISSUE THREAD

**Issue by gordon-matt** [OData/WebApi#1369]
I have an OData function as follows

```
[HttpGet]
public IActionResult GetCurrentVersion([FromODataUri] int templateId, [FromODataUri] string cultureCode)
{
    var currentVersion = Service.FindOne(templateId, cultureCode);

    if (currentVersion == null)
    {
        var template = messageTemplateService.FindOne(templateId);

        var utcNow = DateTime.UtcNow;
        currentVersion = new MessageTemplateVersion
        {
            MessageTemplateId = templateId,
            CultureCode = cultureCode,
            Subject = template.Name,
            DateCreatedUtc = utcNow,
            DateModifiedUtc = utcNow
        };
        Service.Insert(currentVersion);
    }

    // return Ok(currentVersion); // <-- Doesn't work
    return new JsonResult(currentVersion); // Workaround
}
```

Basically, `OkObjectResult` seems to be bugged. If using `return Ok(currentVersion)`, the browser says **"Connection timed out"** and when inspecting the **Network** tab in the developer tools, I see this error message:
`SyntaxError: JSON.parse: end of data while reading object contents at line 1 column 2 of the JSON data`

So I tried `return new JsonResult(currentVersion);` instead as a workaround and that seems fine. Any idea why `Ok()` is broken? Is this a bug or expected behavior? I was using `Ok()` in MVC5

**Comment by robward-ms** [comment]
@gordon-matt - I think you will find that it's an issue with delayed execution of the IActionResult. Is it possible the Service is destroyed/disposed after the method returns? When the result finally does execute, it may be that Service is trying to connect to the DB and planning to timeout and that the timeout in Kestrel occurs first. 

Just a guess but [OkObjectResult ](https://github.com/aspnet/Mvc/blob/760c8f38678118734399c58c2dac981ea6e47046/src/Microsoft.AspNetCore.Mvc.Core/OkObjectResult.cs) and [JsonResult ](https://github.com/aspnet/Mvc/blob/760c8f38678118734399c58c2dac981ea6e47046/src/Microsoft.AspNetCore.Mvc.Formatters.Json/JsonResult.cs)derives form different classes so it is possible they behave differently.

**Comment by gordon-matt** [comment]
@robward-ms Thanks for the response, but that is not the case, because I tried the following and got the same results:
```
public IActionResult GetCurrentVersion([FromODataUri] int templateId, [FromODataUri] string cultureCode)
{
	return Ok(new MessageTemplateVersion
	{
		MessageTemplateId = templateId,
		CultureCode = cultureCode,
		Subject = "Name",
		DateCreatedUtc = DateTime.UtcNow,
		DateModifiedUtc = DateTime.UtcNow
	});
}
```

As you can see, there is no database work or anything else being done here - simply returning a new object via `Ok()`

**Comment by gordon-matt** [comment]
@robward-ms Here you go:

```
public class MessageTemplateVersion : IEntity
{
    public int Id { get; set; }

    public int MessageTemplateId { get; set; }

    public string CultureCode { get; set; }

    public string Subject { get; set; }

    public string Data { get; set; }

    public DateTime DateCreatedUtc { get; set; }

    public DateTime DateModifiedUtc { get; set; }

    public virtual MessageTemplate MessageTemplate { get; set; }

    #region IEntity Members

    public object[] KeyValues
    {
        get { return new object[] { Id }; }
    }

    #endregion IEntity Members
}
```

**Comment by robward-ms** [comment]
@gordon-matt - I was able to use the class and navigation property with Ok() without issue in a Get method, now I'm working on a controller method like yours to see if FromODataUri affects this.

**Comment by gordon-matt** [comment]
Thanks. You can pull the latest copy of my [OData Test Project](https://github.com/gordon-matt/OData_Test), where I have copied the problematic code to. Run that and try the following URL to see what happens:

`https://localhost:44367/odata/MessageTemplateVersionApi/Default.GetCurrentVersion(templateId=1,cultureCode=null)`

**Comment by robward-ms** [comment]
Will do, thanks for the repo.

**Comment by robward-ms** [comment]
I'm going to ask @xuzhg or @mikepizzo to look at this one. ODL is throwing an exception while writing the resource. The exception thrown [here](https://github.com/OData/odata.net/blob/bf1f8c2a3a9b72d9fba05853ecb01f425abfeaca/src/Microsoft.OData.Core/ODataResourceTypeContext.cs#L170) when accessing the [NavigationSourceEntityTypeName](https://github.com/OData/odata.net/blob/bf1f8c2a3a9b72d9fba05853ecb01f425abfeaca/src/Microsoft.OData.Core/ODataResourceTypeContext.cs#L64-L67).  I am not very knowledgeable about the ODL writer.

I can explain the other issues you are seeing as a result of the exception:
1.) The exception occurs after the headers have been sent. In this case, Kestrel can't do much so it throws what seems like a strange exception. It would provide you with a debug page if the headers were not already sent.
2.) You see this when using Ok() because the invokes the OData formatter. When you use Json(), you specifically tell AspNetCore to use it's JSON formatter, bypassing the exception.

So it is not a problem with OkObjectResult(), AspNetCore is working as expected in this case. Still not sure if it's a bug in WebApi or ODL so I'll leave it tagged as a question until we know for sure.

FYI, if you use the OData_Test debug option (as opposed to IIS Express), you'll see all sorts of great debugging info in a console window. In this case, it would not have helped all that much but it does display potions of the exception from ODL, which helps a bit.

**Comment by robward-ms** [comment]
Forgot to add: I debugged this with the latest code from ODL master and WebAPi feature/netcore. The stack trace is below, I saved a dump if anyone wants it:

   at Microsoft.OData.ODataResourceTypeContext.ValidateAndReturn[T](T value) in C:\Users\rob\Source\Repos\odata.net\src\Microsoft.OData.Core\ODataResourceTypeContext.cs:line 173
   at Microsoft.OData.ODataResourceTypeContext.get_NavigationSourceName() in C:\Users\rob\Source\Repos\odata.net\src\Microsoft.OData.Core\ODataResourceTypeContext.cs:line 58
   at Microsoft.OData.ODataContextUrlInfo.Create(ODataResourceTypeContext typeContext, ODataVersion version, Boolean isSingle, ODataUri odataUri) in C:\Users\rob\Source\Repos\odata.net\src\Microsoft.OData.Core\ODataContextUrlInfo.cs:line 153
   at Microsoft.OData.JsonLight.ODataJsonLightResourceSerializer.<>c__DisplayClass11_0.<WriteResourceContextUri>b__0() in C:\Users\rob\Source\Repos\odata.net\src\Microsoft.OData.Core\JsonLight\ODataJsonLightResourceSerializer.cs:line 353
   at Microsoft.OData.JsonLight.ODataJsonLightSerializer.WriteContextUriProperty(ODataPayloadKind payloadKind, Func`1 contextUrlInfoGen, ODataContextUrlInfo parentContextUrlInfo, String propertyName) in C:\Users\rob\Source\Repos\odata.net\src\Microsoft.OData.Core\JsonLight\ODataJsonLightSerializer.cs:line 153
   at Microsoft.OData.JsonLight.ODataJsonLightResourceSerializer.WriteResourceContextUri(ODataResourceTypeContext typeContext, ODataContextUrlInfo parentContextUrlInfo) in C:\Users\rob\Source\Repos\odata.net\src\Microsoft.OData.Core\JsonLight\ODataJsonLightResourceSerializer.cs:line 353
   at Microsoft.OData.JsonLight.ODataJsonLightWriter.StartResource(ODataResource resource) in C:\Users\rob\Source\Repos\odata.net\src\Microsoft.OData.Core\JsonLight\ODataJsonLightWriter.cs:line 292
   at Microsoft.OData.ODataWriterCore.<>c__DisplayClass105_0.<WriteStartResourceImplementation>b__0() in C:\Users\rob\Source\Repos\odata.net\src\Microsoft.OData.Core\ODataWriterCore.cs:line 1283
   at Microsoft.OData.ODataWriterCore.InterceptException(Action action) in C:\Users\rob\Source\Repos\odata.net\src\Microsoft.OData.Core\ODataWriterCore.cs:line 1806
   at Microsoft.OData.ODataWriterCore.WriteStartResourceImplementation(ODataResource resource) in C:\Users\rob\Source\Repos\odata.net\src\Microsoft.OData.Core\ODataWriterCore.cs:line 1270
   at Microsoft.OData.ODataWriterCore.WriteStart(ODataResource resource) in C:\Users\rob\Source\Repos\odata.net\src\Microsoft.OData.Core\ODataWriterCore.cs:line 483
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteResource(Object graph, ODataWriter writer, ODataSerializerContext writeContext, IEdmTypeReference expectedType) in C:\Users\rob\Source\Repos\WebApi1\src\Microsoft.AspNet.OData.Shared\Formatter\Serialization\ODataResourceSerializer.cs:line 330
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteObjectInline(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext) in C:\Users\rob\Source\Repos\WebApi1\src\Microsoft.AspNet.OData.Shared\Formatter\Serialization\ODataResourceSerializer.cs:line 77
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteObject(Object graph, Type type, ODataMessageWriter messageWriter, ODataSerializerContext writeContext) in C:\Users\rob\Source\Repos\WebApi1\src\Microsoft.AspNet.OData.Shared\Formatter\Serialization\ODataResourceSerializer.cs:line 54
   at Microsoft.AspNet.OData.Formatter.ODataOutputFormatterHelper.WriteToStream(Type type, Object value, IEdmModel model, ODataVersion version, Uri baseAddress, MediaTypeHeaderValue contentType, IWebApiUrlHelper internaUrlHelper, IWebApiRequestMessage internalRequest, IWebApiHeaders internalRequestHeaders, Func`2 getODataMessageWrapper, Func`2 getEdmTypeSerializer, Func`2 getODataPayloadSerializer, Func`1 getODataSerializerContext) in C:\Users\rob\Source\Repos\WebApi1\src\Microsoft.AspNet.OData.Shared\Formatter\ODataOutputFormatterHelper.cs:line 189
   at Microsoft.AspNet.OData.Formatter.ODataOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding) in C:\Users\rob\Source\Repos\WebApi1\src\Microsoft.AspNetCore.OData\Formatter\ODataOutputFormatter.cs:line 218

**Comment by xuzhg** [comment]
@gordon-matt 
I took a look this issue. It seems you did a wrong way to add the return for the function `GetCurrentVersion`.

I modified your model builder codes as:

```
var getCurrentVersionFunction = builder.EntityType<MessageTemplateVersion>().Collection.Function("GetCurrentVersion");
getCurrentVersionFunction.Parameter<int>("templateId");
getCurrentVersionFunction.Parameter<string>("cultureCode");
//getCurrentVersionFunction.Returns<MessageTemplateVersion>();  // Returns<T>() is used to add primitive or complex, or enum return type.
getCurrentVersionFunction.ReturnsFromEntitySet<MessageTemplateVersion>("MessageTemplateVersionApi");
```

I can get the result:
![image](https://user-images.githubusercontent.com/9426627/42003148-d6292148-7a1e-11e8-90e2-60839feb2bc1.png)
