### ISSUE TITLE
[feature/netcore] Returning SingleResult with ODataQueryOptions is throwing an exception

### ISSUE THREAD

**Issue by rmadisonhaynie** [OData/WebApi#1391]
If I try to return a type of SingleResult<> and use ODataQueryOptions attribute as a parameter in the controller method an exception is thrown saying that the result does not implement IEnumerable<>. 

### Assemblies affected

Microsoft.AspNetCore.OData 7.0.0-beta2

### Reproduce steps
[ODataRoute("({id})")]
[EnableQuery]
[HttpGet]
public SingleResult<Customer> Get([FromODataUri] string id, ODataQueryOptions opts)
{
      VerifySelectOption(opts);
      return SingleResult.Create(_dbContext.Customers.Where(x => x.Id == id).AsQueryable());
}
### Expected result

Not sure...
I guess this may make sense since you can only use $select and $expand query options with a Single result.

If so, then a better message would be nice. i.e. I had to dig a little to figure out it's because I was using ODataQueryOptions and returning SingleResult. 
And I would like to know if there's an easy way I can easily get a SelectExpandQueryOption

### Actual result

`
System.InvalidOperationException: Cannot create an EDM model as the action 'Get' on controller 'Customers' has a return type 'Microsoft.AspNet.OData.SingleResult'1[[Customer]]' that does not implement IEnumerable<T>.
   at Microsoft.AspNet.OData.ODataQueryParameterBindingAttribute.ODataQueryParameterBinding.GetEntityClrTypeFromActionReturnType(ActionDescriptor actionDescriptor)
   at Microsoft.AspNet.OData.ODataQueryParameterBindingAttribute.ODataQueryParameterBinding.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BinderTypeModelBinder.<BindModelAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.<BindModelAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter'1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
`

**Comment by rmadisonhaynie** [comment]
So I got around this "issue"? for now by extending EnableQuery and adding my own query validation.

I had problem with this too however which is for my controller method which returns a collection of the entities EnableQuery.ValidateQuery wouldn't execute if there were no query params, where as it is executed for the single result. This is a problem for my purpose as part of what I'm verifying is that $select query is provided, so if this method isn't executed if there are no query params I miss validating exactly what I'm trying to avoid.
At the least the behavior should be the same for a single result or a collection.

**Comment by robward-ms** [comment]
@rmadisonhaynie - Can you try a few things?

1.) Use Queryable instead of AsQueryable. See [SingleResultOfT.cs](https://github.com/OData/WebApi/blob/e5034f9c2a99b343eabe710d25573b54d72f495c/src/Microsoft.AspNetCore.OData/SingleResultOfT.cs#L27-L33)
2.) Any chance you are using EFCore? SingleResult() passes .Queryable down to the inner expression and EFCore does not support IQueryable until 2.1.0.

All that said, SingleResult does not support AsQuerable() and neither does the AspNet version. We could consider adding it to the AspNetCore version.

**Comment by rmadisonhaynie** [comment]
@robward-ms 

1.) I tried this without success
2.) I am using EFCore 2.0.0, but I tried 2.1.0-preview2-final and still had the issue.

BUT... I randomly discovered if I use the parameterized ODataQueryOptions<T> vs non-parameterized ODataQueryOptions I no longer have a problem and everything works fine.

**Comment by robward-ms** [comment]
@rmadisonhaynie - Not sure whether to keep thinking of this as a bug or as a by-design, i.e. use the template version. But I guess that means that using the non-template one should be harder so I guess it's a bug either way. Thoughts?

**Comment by rmadisonhaynie** [comment]
@robward-ms yeah seems as design to me so for now I'm unblocked :)
Though, in general I think the OData library is really great but this wouldn't be the first time I was tripped up on something that I was doing to the best of my knowledge from documentation and IntelliSense, only to solve it from looking through source code or trial and error. 

For example here https://docs.microsoft.com/en-us/aspnet/web-api/overview/odata-support-in-aspnet-web-api/supporting-odata-query-options there are 4 examples using ODataQueryOptions as a controller method parameter but only 1 example is using the template version. And then here http://odata.github.io/WebApi/#04-16-ignore-query-option there's only 1 example and it's not the template version.

Given that... I guess I personally wouldn't qualify it as a bug either but a tech debt, being I think it'd probably be better to make it harder to use the non-template version, or some documentation update.

**Comment by robward-ms** [comment]
@rmadisonhaynie - Documentation can always be better, thanks for the feedback! @xuzhg , @madansr7 , any thoughts?

**Comment by xuzhg** [comment]
@rmadisonhaynie I also think it's by design. And we are working on the RTM of 7.0. Updating documentation will be later. 
Please let us know any other concerns or file new issues.
