### ISSUE TITLE
 How to handle snake_case OData queries together with PascalCase entities?

### ISSUE THREAD

**Issue by ilya-chumakov** [OData/WebApi#1469]
Is it possible to have `PascalCase` C# entities but build `snake_case` OData queries and get `snake_case` JSON responses? I tried to set ASP.NET Core custom JSON options but OData ignores it.

### Assemblies affected

Microsoft.AspNetCore.OData (7.0.0-beta4)

### Reproduce steps
Entity:
```csharp
    public class User
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
    }
```
Controller:
```csharp
    public class UserController : Controller
    {
        [EnableQuery]
        public IQueryable<User> Get()
        {
            return _context.User.AsQueryable();
        }
    }
```
Startup.cs:
```csharp
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().AddJsonOptions(options =>
                {
                    //convert lower_case <-> PascalCase
                    options.SerializerSettings.ContractResolver = new DefaultContractResolver()
                    {
                        NamingStrategy = new SnakeCaseNamingStrategy()
                    };
                });

            services.AddOData();
        }

        public void Configure(IApplicationBuilder app)
        {
            var builder = new ODataConventionModelBuilder();
            builder.EntitySet<User>(nameof(User));
            IEdmModel edmModel = builder.GetEdmModel();

            app.UseMvc(routeBuilder =>
            {
                routeBuilder.MapODataServiceRoute("ODataRoute", "odata", edmModel);
                routeBuilder.Count().Filter().OrderBy().Select().MaxTop(100);
                routeBuilder.EnableDependencyInjection();
            });
        }
    }
```
[SnakeCaseNamingStrategy](https://stackoverflow.com/a/3938546/5112433) is a JSON.NET way to serialize to `snake_case` and back.
### Expected result

Queries having the entity properties in `snake_case` work:

    /odata/User$filter=contains(first_name, 'est')

Server responses are in `snake_case`:

    {
        "id": 1,
        "first_name": "aecat cupida"
    }
### Actual result

    "error": {
        "code": "",
        "message": "The query specified in the URI is not valid. Could not find a property named 'first_name' on type '<cleanup>.User'.",
        "details": [ ],
        "innererror": {<cleanup>}
    }

### Additional detail
All requests/responses are serialized to `snake_case` and deserialized back if the built-in ASP.NET Core serialization is used and [SnakeCaseNamingStrategy](https://stackoverflow.com/a/3938546/5112433) is set:
```csharp
    [HttpGet("users/raw")]
    public IActionResult Raw(UserInput input)
    {
        return Json(new UserOutput());
    }
```
it produces something like:

    {
        "id": 1,
        "first_name": "aecat cupida"
    }

**Comment by xuzhg** [comment]
@ilya-chumakov 

I think you can use [DataContract] and [DataMember] attributes to control the property name.

For example: 
```C#
[DataContract]
public class Employee
{
    [DataMember]
    public int Id { get; set; }

    [DataMember(Name = "first_name")]
    public string FirstName { get; set; }
}
```

you will get the edm model as:


```xml

<EntityType Name="Employee">
  <Key>
    <PropertyRef Name="Id"/>
  </Key>
  <Property Name="Id" Nullable="false" Type="Edm.Int32"/>
  <Property Name="first_name" Type="Edm.String"/>
</EntityType>
```

**Comment by ilya-chumakov** [comment]
@xuzhg 
I tried to add these attributes to my EF Core entity, but:

1) It doesn't work: `InvalidOperationException` is thrown on app startup. 
2) It means UI logic leaking to DAL level.
3) It's error-prone: easy to forget adding/updating the attribute, hard to maintain.

Entity: 

    [Table("pz_event", Schema = "bar")]
    [DataContract]
    public partial class PzEvent
    {
        [Key]
        [Column("row_id")]
        public Guid RowId { get; set; }

        [Column("user_email")]
        [DataMember(Name = "user_email")]
        public string UserEmail { get; set; }
    }

Exception:

```
{System.InvalidOperationException: The entity 'PzEvent' does not have a key defined.
   at Microsoft.AspNet.OData.Builder.ODataModelBuilder.ValidateModel(IEdmModel model)
   at Microsoft.AspNet.OData.Builder.ODataConventionModelBuilder.ValidateModel(IEdmModel model)
   at Microsoft.AspNet.OData.Builder.ODataModelBuilder.GetEdmModel()
   at Microsoft.AspNet.OData.Builder.ODataConventionModelBuilder.GetEdmModel()
```

**Comment by xuzhg** [comment]
@ilya-chumakov The error message `the entity 'PzEvent' does not have a key define` is very clear that OData model build can't find the property can be used to define as `key`. So, you can find that you miss adding the `[DataMember]` to the `RowId` property. 

I think once you add `[DataMember]` to `RowId`, the error will disappear. Please let me know any other problem.

**Comment by ilya-chumakov** [comment]
@xuzhg  I added `[DataContract]` to all relevant entity properties and the app started successfully. However, if `user_email` is used in an OData query, then the server response is `500` with the empty body because of this unhandled exception:

```
System.ArgumentException: Instance property 'user_email' is not defined for type '<...>.PzEvent'
Parameter name: propertyName
   at System.Linq.Expressions.Expression.Property(Expression expression, String propertyName)
   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.CreatePropertyAccessExpression(Expression source, IEdmProperty property, String propertyPath)
   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.BindPropertyAccessQueryNode(SingleValuePropertyAccessNode propertyAccessNode)
   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.Bind(QueryNode node)
   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.<BindArguments>b__59_0(SingleValueNode n)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.BindArguments(IEnumerable`1 nodes)
   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.BindContains(SingleValueFunctionCallNode node)
   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.BindSingleValueFunctionCallNode(SingleValueFunctionCallNode node)
   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.Bind(QueryNode node)
   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.BindConvertNode(ConvertNode convertNode)
   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.Bind(QueryNode node)
   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.BindBinaryOperatorNode(BinaryOperatorNode binaryOperatorNode)
   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.Bind(QueryNode node)
   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.BindExpression(SingleValueNode expression, RangeVariable rangeVariable, Type elementType)
   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.BindFilterClause(FilterBinder binder, FilterClause filterClause, Type filterType)
   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.Bind(IQueryable baseQuery, FilterClause filterClause, Type filterType, ODataQueryContext context, ODataQuerySettings querySettings)
   at Microsoft.AspNet.OData.Query.FilterQueryOption.ApplyTo(IQueryable query, ODataQuerySettings querySettings)
   at Microsoft.AspNet.OData.Query.ODataQueryOptions.ApplyTo(IQueryable query, ODataQuerySettings querySettings)
   at Microsoft.AspNet.OData.Query.ODataQueryOptions`1.ApplyTo(IQueryable query, ODataQuerySettings querySettings)
   at Microsoft.AspNet.OData.Query.ODataQueryOptions.ApplyTo(IQueryable query)
   at Microsoft.AspNet.OData.Query.ODataQueryOptions`1.ApplyTo(IQueryable query)
```

**Comment by xuzhg** [comment]
@ilya-chumakov See my codes at: https://github.com/xuzhg/WebApi/tree/issue1469

That works well.

![image](https://user-images.githubusercontent.com/9426627/41484280-15844c1a-7091-11e8-895d-aebcb09e971d.png)

**Comment by xuzhg** [comment]
@ilya-chumakov Close this and please feel free to open new issue or re-open it if you have further concern. Thanks.

**Comment by ilya-chumakov** [comment]
Hello there. Maybe the situation has changed. Does AspNetCore.OData have any support for `snake_case` JSON if entities remain in PascalCase except covering them with explicit `[DataMember]` attributes?
