### ISSUE TITLE
OData AspNetCore + EF Core contains on string value which is null throws NullReferenceException

### ISSUE THREAD

**Issue by prochnowc** [OData/WebApi#1478]
If i try to filter records using eg. `$filter=contains(firstName,'Alan')` and the value of `firstName` is `null` for some record i receive NullReferenceException.

### Assemblies affected

- Microsoft.AspNetCore.OData 7.0.0-beta4
- Microsoft.EntityFrameworkCore 2.1.0

### Reproduce steps

Create a OData query ontop of EF core entity and try to filter records which have null strings using contains.

### Expected result

Records with fields which have null value should be filtered out.

### Actual result

NullReferenceException is thrown:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , TransparentIdentifier`2 )
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__7.MoveNext()
   at System.Linq.Enumerable.SelectIPartitionIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at Microsoft.AspNet.OData.Query.TruncatedCollection`1..ctor(IQueryable`1 source, Int32 pageSize)
   at Microsoft.AspNet.OData.Query.ODataQueryOptions.LimitResults[T](IQueryable`1 queryable, Int32 limit, Boolean& resultsLimited)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at Microsoft.AspNet.OData.Query.ODataQueryOptions.LimitResults(IQueryable queryable, Int32 limit, Boolean& resultsLimited)
   at Microsoft.AspNet.OData.Query.ODataQueryOptions.ApplyTo(IQueryable query, ODataQuerySettings querySettings)
```

**Comment by xuzhg** [comment]
@prochnowc 

I had the test and it looks work fine at my side.

Would you please take a look at: https://github.com/xuzhg/WebApiSample/commit/99c0eba3a91a2b5a9fe530041c4a79ebdbb298f3

And please feel free to clone and try. Let me know your found. Thanks.

**Comment by prochnowc** [comment]
Thanks for your help - i found the issue.
`HandleNullPropagation` was set to `False`.

**Comment by xuzhg** [comment]
You are welcome. Please let us know any further concerns and questions.
