### ISSUE TITLE
Custom implementation of IETagHandler that returns null as ETag is not supported

### ISSUE THREAD

**Issue by ghost** [OData/WebApi#1479]
*Custom implementation of IETagHandler that returns null as ETag is not supported.*

### Assemblies affected

*Microsoft.AspNetCore.OData 7.0.0.20307

### Reproduce steps

Created and injected the following ETagHandler in attempt to disable ETag handling on OData side

    public class NullETagHandler : IETagHandler
    {
        public EntityTagHeaderValue CreateETag(IDictionary<string, object> properties)
        {
            return null;
        }

        public IDictionary<string, object> ParseETag(EntityTagHeaderValue etagHeaderValue)
        {
            return null;
        }
    }

### Expected result

Expected to ignore passed If-None-Match header in a request.

### Actual result

Throws a NullReferenceException:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNet.OData.Extensions.HttpRequestExtensions.GetETag(HttpRequest request, EntityTagHeaderValue entityTagHeaderValue)
   at Microsoft.AspNet.OData.Extensions.HttpRequestExtensions.GetETag[TEntity](HttpRequest request, EntityTagHeaderValue entityTagHeaderValue)
   at Microsoft.AspNet.OData.Query.ODataQueryOptions.get_IfNoneMatch()
   at Microsoft.AspNet.OData.Query.ODataQueryOptions`1.get_IfNoneMatch()
   at Microsoft.Extensions.Internal.PropertyHelper.CallNullSafePropertyGetter[TDeclaringType,TValue](Func`2 getter, Object target)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationEntry.get_Model()

**Comment by xuzhg** [comment]
@abasyuk Would you please create repro for us to investigate? Thanks.
