### ISSUE TITLE
Is it possible to disable ETag support to stop it blowing up?

### ISSUE THREAD

**Issue by freeranger** [OData/WebApi#1481]
I am generating my own Etags for my GET controller actions using custom middleware and would like to disable OData Etag handling because it blows up as it is unable to handle the custom format.

### Assemblies affected

Microsoft.AspNetCore.OData 7.0.0.20307

### Reproduce steps

Call any end point that has an ODataQueyOptions parameter and include an If-None-Match header with any made up value you like - it should not be one generated by the OData etag handler.

### Expected result

I would expect the method to just work normally, ignoring the invalid ETag

### Actual result

```Microsoft.OData.ODataException: Syntax error: character '�' is not valid at position 0 in '�}� =}�`�QE�.z���=��Qx'.
   at Microsoft.OData.UriParser.ExpressionLexer.NextToken()
   at Microsoft.OData.UriParser.ExpressionLexerLiteralExtensions.ReadLiteralToken(ExpressionLexer expressionLexer)
   at Microsoft.OData.ODataUriUtils.ConvertFromUriLiteral(String value, ODataVersion version, IEdmModel model, IEdmTypeReference typeReference)
   at Microsoft.AspNet.OData.Formatter.DefaultODataETagHandler.ParseETag(EntityTagHeaderValue etagHeaderValue)
   at Microsoft.AspNet.OData.Extensions.HttpRequestExtensions.GetETag(HttpRequest request, EntityTagHeaderValue entityTagHeaderValue)
   at Microsoft.AspNet.OData.Extensions.HttpRequestExtensions.GetETag[TEntity](HttpRequest request, EntityTagHeaderValue entityTagHeaderValue)
   at Microsoft.AspNet.OData.Query.ODataQueryOptions.get_IfNoneMatch()
   at Microsoft.AspNet.OData.Query.ODataQueryOptions`1.get_IfNoneMatch()
   at Microsoft.Extensions.Internal.PropertyHelper.CallNullSafePropertyGetter[TDeclaringType,TValue](Func`2 getter, Object target)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationEntry.get_Model()```

### Additional detail

If it doesn't make sense to silently ignore these etags then a way to disable etag support in your library would suffice.
My use case is I have middleware which generates ETags for me for all GET end points, (unless the controller action generates an etag for that particular case), only some of which take ODataQueryOptions (we are not using EF or ODataController).
Any end point with odata support is currently broken because they blow up as described above.

**Comment by madansr7** [comment]
Can you please provide an example of the invalid ETag that throws an exception?

**Comment by freeranger** [comment]
If I set it to literally X, no quotes, then I get this:
```
 at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index)
   at System.Net.Http.Headers.EntityTagHeaderValue.Parse(String input)
   at Microsoft.AspNet.OData.Query.ODataQueryOptions.get_IfNoneMatch()
   at Microsoft.AspNet.OData.Query.ODataQueryOptions`1.get_IfNoneMatch()
   at Microsoft.Extensions.Internal.PropertyHelper.CallNullSafePropertyGetter[TDeclaringType,TValue](Func`2 getter, Object target)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationEntry.get_Model()
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitChildren(IValidationStrategy strategy)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitComplexType(IValidationStrategy defaultStrategy)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, String key, Object model)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.<BindModelAsync>d__6.MoveNext()
```

If I set it to "X", ie with quotes, I get:
```
at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at Microsoft.AspNet.OData.Formatter.DefaultODataETagHandler.ParseETag(EntityTagHeaderValue etagHeaderValue)
   at Microsoft.AspNet.OData.Extensions.HttpRequestExtensions.GetETag(HttpRequest request, EntityTagHeaderValue entityTagHeaderValue)
   at Microsoft.AspNet.OData.Extensions.HttpRequestExtensions.GetETag[TEntity](HttpRequest request, EntityTagHeaderValue entityTagHeaderValue)
   at Microsoft.AspNet.OData.Query.ODataQueryOptions.get_IfNoneMatch()
   at Microsoft.AspNet.OData.Query.ODataQueryOptions`1.get_IfNoneMatch()
   at Microsoft.Extensions.Internal.PropertyHelper.CallNullSafePropertyGetter[TDeclaringType,TValue](Func`2 getter, Object target)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationEntry.get_Model()
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitChildren(IValidationStrategy strategy)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitComplexType(IValidationStrategy defaultStrategy)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, String key, Object model)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.<BindModelAsync>d__6.MoveNext()
```

And finally, if I set it to one of my generated tags, which is an MD5 hash of the body of the (json) response:  "7DA93857D637AD1EE0CA1B67F822607F"
then I get the response I posted originally.

**Comment by xuzhg** [comment]
@freeranger would you please share us your repro project and sample data?

**Comment by freeranger** [comment]
@xuzhg I don’t have a project I can share with you at the moment - all you need is a controller action that has an ODataQueryOptins argument and use Postman to supply an ETag like the ones I supplied.
Is that not enough to recreate the issue?

**Comment by freeranger** [comment]
@xuzhg Actually I had some spare cycles today and created something quickly: https://github.com/freeranger/ODataETagTest
Run this and then use Postman or similar to send an If-None-Match header to api/values using the various values I mentioned before - you get a different error each time.
I think you should get no error and/or we should have the ability to turn off OData trying to process etags.

**Comment by xuzhg** [comment]
@freeranger If I run your sample, I can get:

![image](https://user-images.githubusercontent.com/9426627/41612659-69f91f22-73a8-11e8-8048-789b60dac67e.png)

**Comment by freeranger** [comment]
@xuzhg interesting.  Did you use the same version as me or a later one?
Did you try the two other examples I gave?  All three were throwing different errors?
What did you use to submit to the API?  I used postman

**Comment by xuzhg** [comment]
@freeranger Thank for your verification. Please feel free file other issues if you have any concerns or questions.
