### ISSUE TITLE
System.Reflection  System.TypeInitializationException using ODataConventionModelBuilder (Totally Breaks V7)

### ISSUE THREAD

**Issue by sckid1108** [OData/WebApi#1540]
*Short summary (3-5 sentences) describing the issue.*
var modelBuilder = new ODataConventionModelBuilder();
modelBuilder.GetEdmModel();
Produces this:
System.TypeInitializationException

### Assemblies affected

*Which assemblies and versions are known to be affected e.g. OData WebApi lib 6.1.0
Microsoft.AspNet.OData V7.0.0.20629

### Reproduce steps

Using .NET Framework 4.6.2 using Web Api 2

var modelBuilder = new ODataConventionModelBuilder();
modelBuilder.GetEdmModel();

Produces this:
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Microsoft.OData.Edm.Vocabularies.V1.CoreVocabularyModel' threw an exception.
  Source=Microsoft.OData.Edm
  StackTrace:
   at Microsoft.OData.Edm.EdmModelBase..ctor(IEnumerable`1 referencedModels, IEdmDirectValueAnnotationsManager annotationsManager)
   at Microsoft.OData.Edm.EdmModel..ctor()
   at Microsoft.AspNet.OData.Builder.EdmModelHelperMethods.BuildEdmModel(ODataModelBuilder builder)
   at Microsoft.AspNet.OData.Builder.ODataConventionModelBuilder.GetEdmModel()
   at DataServerV11.Startup.Configuration(IAppBuilder builder) in C:\Development\InsulinAlgoOnAzureV1.1\InsulinAlgoOnAzureV1.1\AzureServerV11\DataServerV11\Startup.cs:line 234

Inner Exception 1:
FileLoadException: Could not load file or assembly 'System.Reflection, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

in Startup.cs

### Expected result

Site would continue to load and run

### Actual result

Major exception and site crashes on load

### Additional detail

*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by xuzhg** [comment]
@sckid1108 
From the codes, it looks you're using OWin to host the service. I have a test and it can work fine. Would you please take a look at: https://github.com/xuzhg/WebApiSample/tree/master/ODataOWin
Please let me know if something wrong.
Thanks.
