### ISSUE TITLE
Custom serialization/deserialization for certain property type

### ISSUE THREAD

**Issue by iamkinetic** [OData/WebApi#1575]
So I'm using OData (7.0.1) for Asp.Net Core (2.1) with EFCore (PgSql + Postgis).  We have one model with a property of type Point (NetTopologySuite.Geometries.Point).  

For whatever reason, OData is not correctly handling this type.  I'm getting this exception when I'm selecting only this field with no expand at all:

`
Microsoft.OData.ODataException: The depth limit for entries in nested expanded navigation links was reached. The number of nested expanded entries cannot exceed 100.
   at Microsoft.OData.ODataWriterCore.ThrowODataException(String errorMessage, ODataItem item)
   at Microsoft.OData.ODataWriterCore.WriteStartResourceImplementation(ODataResource resource)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteResource(Object graph, ODataWriter writer, ODataSerializerContext writeContext, IEdmTypeReference expectedType)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteComplexProperties(IEnumerable complexProperties, ResourceContext resourceContext, ODataWriter writer)
`

So i thought I would create a custom serializer/deserializer for this type. I know how to do it for the "normal" asp.net core serialization, but I can't figure how to do it with OData.

Is this the right way to do it?  Can I get some pointer on how to implement my custom serializer/deserializer?

Thanks.

**Comment by mloffer** [comment]
I would also like to use Json.NET to serialize DbGeometry to GeoJSON, but I can't figure out how to write a custom serializer, either. It appears that OData on AspNetCore uses its own ODataMediaTypeFormatter instead of the usual JsonMediaTypeFormatter, but I have yet to find any documentation that describes how to use it.

**Comment by iamkinetic** [comment]
Yeah, documentation has never been OData strongest point!   I kind of give up on using ODataMediaTypeFormatter.  This is how I've done it.  

First, I've added this wrapper in my project (pretty sure I've found this somewhere on the internet, but can't remember where).  In my case, i've used WKT, but I'm sure you'll adapt this code easily:

```
public class NetTopologySuitePointWrapper
{
    private readonly string point;

    public static implicit operator NetTopologySuitePointWrapper(string dbg)
    {
	if (dbg == null)
		return null;
	return new NetTopologySuitePointWrapper(dbg);
    }

    public static implicit operator String(NetTopologySuitePointWrapper wrapper)
    {
	return wrapper?.point;
    }

    public static implicit operator NetTopologySuitePointWrapper(Point point)
    {
	if (point == null)
		return null;
	return new NetTopologySuitePointWrapper(point.ToText());
    }

    public static implicit operator Point(NetTopologySuitePointWrapper wrapper)
    {
	try
	{
		if (wrapper?.point == null)
			return null;

		var r = new NetTopologySuite.IO.WKTReader {DefaultSRID = 4326, HandleOrdinates = GeoAPI.Geometries.Ordinates.XY};
		var vr = r.Read(wrapper.point) as Point;
		return vr;
	}
	catch
	{
		return null;
	}
    }

    private NetTopologySuitePointWrapper(string dbg)
    {
	point = dbg;
    }		
}
```

Then, I've changed the object I was trying to custom serialize to use the wrapper.

```
public class SomeObject
{
   private NetTopologySuitePointWrapper wrapper;

   [JsonIgnore]
   public NetTopologySuite.Geometries.Point PointCoordinates 
   { 
       get => wrapper; 
       set => wrapper = value; 
   }

   public string Coordinates { get => wrapper; set => wrapper = value; }  
}
```

`PointCoordinates` is what comes from the database.  `Coordinates` is the WKT representation that is made available through OData.  The JsonIgnore is there for non OData api calls.

In startup.cs, where I create my ODataConventionModelBuilder, I have to ignore the PointCoordinates property to make OData only use the WKT property.

```
var builder = new ODataConventionModelBuilder();			
builder.EnableLowerCamelCase();
builder.EntitySet<SomeObject>("SomeObject").AllowAllQueryType();
builder.EntityType<SomeObject>().Ignore(t => t.PointCoordinates);
// etc...
```

It's not a great solution, but it works perfectly.

**Comment by iamkinetic** [comment]
Here is a class named `GeographyPointWrapper` that is pretty much my NetTopologySuitePointWrapper: 

https://github.com/OData/ODataSamples/blob/master/WebApiCore/ODataSpatialSample/ODataSpatialSample/Models/GeographyPointWrapper.cs

This whole ODataSpatialSample is pretty much what I've used a model to make my api works correctly.
