### ISSUE TITLE
CreatedAtAction raise "No route matches the supplied values"

### ISSUE THREAD

**Issue by Angelinsky7** [OData/WebApi#1584]
If i use odata controller to build an api i cannot call the `CreatedAtAction` method to return the correct url of the created resource.

### Assemblies affected

```
<PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.2" />
<PackageReference Include="Microsoft.AspNetCore.OData" Version="7.0.1" />
<PackageReference Include="Microsoft.AspNetCore.OData.Versioning" Version="3.0.0-beta1" />
<PackageReference Include="Microsoft.AspNetCore.OData.Versioning.ApiExplorer" Version="3.0.0-beta1" />
<PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.1.1" />
<PackageReference Include="Microsoft.Extensions.PlatformAbstractions" Version="1.1.0" />
<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.1" />
<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="2.1.1" />
<PackageReference Include="Swashbuckle.AspNetCore" Version="3.0.0" />
```

### Reproduce steps

```
 [ApiVersion("1.0")]
 [ApiVersion("2.0")]
 [ODataRoutePrefix("VBonEchange")]
 [EnableQuery()]
 public class VBonEchangeController : ODataController {

        [HttpGet]
        [ODataRoute]
        [Produces("application/json")]
        [ProducesResponseType(typeof(ODataValue<IEnumerable<VBonEchange>>), Status200OK)]
        public IActionResult GetBonEchanges() {
            return Ok(_context.VBonEchangeRepository());
        }

        [HttpGet("({id})")]
        [ODataRoute("({id})")]
        [Produces("application/json")]
        [ProducesResponseType(typeof(VBonEchange), Status200OK)]
        [ProducesResponseType(Status404NotFound)]
        public async Task<IActionResult> GetBonEchange([FromRoute] Int64 id) {
            ....
            return Ok(vBonEchange);
        }

        [HttpPost]
        [ODataRoute()]
        [Produces("application/json")]
        [ProducesResponseType(typeof(VBonEchange), Status201Created)]
        [ProducesResponseType(Status400BadRequest)]
        public async Task<IActionResult> CreateBonEchange([FromBody] VBonEchange bonEchange) {
             ...
             VBonEchange vBonEchange = await _context.VBonEchangeRepository().SingleOrDefaultAsync(p => p.Id == newBon.Id);
             return CreatedAtAction("GetBonEchange", new { id = vBonEchange.Id }, vBonEchange);
        }

}
```

### Expected result

The route should be created correctly... if i revert back to ControllerBase and only use WebApi everything is working correctly

### Actual result

```
System.InvalidOperationException: No route matches the supplied values.
   at Microsoft.AspNetCore.Mvc.CreatedAtRouteResult.OnFormatting(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsync(ActionContext context, ObjectResult result)
   at Microsoft.AspNetCore.Mvc.ObjectResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by Angelinsky7** [comment]
The thing interesting is that it's not the call to `CreatedAtAction` that is causing the crash but later during the execution

**Comment by sunsided** [comment]
Maybe it is related: I have a similar problem with a regular controller and it is driving me crazy. For me, it appears that the URL is correctly generated (the API version number being inferred automatically), because the location header of the response is set to the correct value. However, _after_ that, it crashes. Here's how it looks like for me:

```
Microsoft.AspNetCore.Mvc.CreatedAtRouteResult.OnFormatting(ActionContext context)
Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsync(ActionContext context, ObjectResult result)
Microsoft.AspNetCore.Mvc.ObjectResult.ExecuteResultAsync(ActionContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync<TFilter, TFilterAsync>()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext<TFilter, TFilterAsync>(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.HttpOverrides.HttpMethodOverrideMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
App.Metrics.AspNetCore.Tracking.Middleware.PerRequestTimerMiddleware.Invoke(HttpContext context) in C:\projects\aspnetcore\src\App.Metrics.AspNetCore.Tracking\Middleware\PerRequestTimerMiddleware.cs
App.Metrics.AspNetCore.Tracking.Middleware.RequestTimerMiddleware.Invoke(HttpContext context) in C:\projects\aspnetcore\src\App.Metrics.AspNetCore.Tracking\Middleware\RequestTimerMiddleware.cs
App.Metrics.AspNetCore.Tracking.Middleware.ErrorRequestMeterMiddleware.Invoke(HttpContext context) in C:\projects\aspnetcore\src\App.Metrics.AspNetCore.Tracking\Middleware\ErrorRequestMeterMiddleware.cs
App.Metrics.AspNetCore.Tracking.Middleware.ActiveRequestCounterEndpointMiddleware.Invoke(HttpContext context) in C:\projects\aspnetcore\src\App.Metrics.AspNetCore.Tracking\Middleware\ActiveRequestCounterEndpointMiddleware.cs
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

So starting from `Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)`, the call stack seems to be identical.

**Comment by nckmcghie** [comment]
Hey @sunsided you issue isn't with Postman but rather with your implementation. The below should work just fine. You don't need to generate a route, All you need to do is call the action and reference the correct Ids and this should work.

```
public async Task<IActionResult> GetBonEchange(int id) {
            ....
            return Ok(vBonEchange);
        }
```
and 

`return CreatedAtAction("GetBonEchange", new { id = vBonEchange.Id }, vBonEchange);`

Note that the variable **_id_** in the **_CreatedAtAction_** function must be the same as the variable passed to **_GetBonEchange_**

**Comment by crgolden** [comment]
@Angelinsky7 I have this issue also.
I find it works when I add "odataPath" to the `routeValues`:
```cs
return CreatedAtAction(nameof(GetBonEchange), new { vBonEchange.Id, odataPath = $"VBonEchange/{vBonEchange.Id}" }, vBonEchange);
```
I don't know why that's the case - seems like a bug.

**Comment by kevindstanley1988** [comment]
I am seeing this exact same issue, your manual odataPath works, but shouldn't be necesarry. It does not seem to be handling the route building correctly inside of the CreatedAtAction. I think this is a bug as well.

> @Angelinsky7 I have this issue also.
> I find it works when I add "odataPath" to the `routeValues`:
> 
> ```cs
> return CreatedAtAction(nameof(GetBonEchange), new { vBonEchange.Id, odataPath = $"VBonEchange/{vBonEchange.Id}" }, vBonEchange);
> ```
> 
> I don't know why that's the case - seems like a bug.

**Comment by crgolden** [comment]
@kevindstanley1988 FYI, I added an additional approach here: [https://stackoverflow.com/a/59839860](https://stackoverflow.com/a/59839860).

**Comment by kevindstanley1988** [comment]
This fixed it and made it far more readable. CreatedODataResult return type and return Created(new Object()) is the way to go for HttpPost with Odata. 

> @kevindstanley1988 FYI, I added an additional approach here: https://stackoverflow.com/a/59839860.

**Comment by sunsided** [comment]
@nckmcghie  Thanks for pointing that one out! The Postman issue still was there though (I remember it vividly): Once I switched to the result preview, it would continue to show me the same error page even long after I fixed the bug. I've never encountered it ever after, but it's already one and a half year ago. :)
