### ISSUE TITLE
Batch create entity realtaion error!

### ISSUE THREAD

**Issue by CarefreeXT** [OData/WebApi#1635]
*I try add two entity and one entity link by batch, request content is *
[Request Content.txt](https://github.com/OData/WebApi/files/2453701/Request.Content.txt)

### Expected result

*Return 500, Server is exception.*

Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 POST http://localhost:52715/sample/odata/$batch multipart/mixed; boundary=batch_61e1460e-54dc-4861-b425-3a5cf2753d8d 970
Microsoft.AspNetCore.Cors.Infrastructure.CorsService:Information: Policy execution successful.
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware:Error: An unhandled exception has occurred while executing the request.

System.InvalidOperationException: This operation is not supported for a relative URI.
   at System.Uri.get_Scheme()
   at Microsoft.AspNet.OData.Batch.HttpRequestExtensions.CopyAbsoluteUrl(HttpRequest request, Uri uri)
   at Microsoft.AspNet.OData.Batch.ODataBatchReaderExtensions.ReadOperationInternalAsync(ODataBatchReader reader, HttpContext originalContext, Guid batchId, Nullable`1 changeSetId, CancellationToken cancellationToken, Boolean bufferContentStream)
   at Microsoft.AspNet.OData.Batch.ODataBatchReaderExtensions.ReadChangeSetRequestAsync(ODataBatchReader reader, HttpContext context, Guid batchId, CancellationToken cancellationToken)
   at Microsoft.AspNet.OData.Batch.DefaultODataBatchHandler.ParseBatchRequestsAsync(HttpContext context)
   at Microsoft.AspNet.OData.Batch.DefaultODataBatchHandler.ProcessBatchAsync(HttpContext context, RequestDelegate nextHandler)
   at Microsoft.AspNet.OData.Batch.ODataBatchMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 72.0522ms 500 text/html; charset=utf-8

**Comment by CarefreeXT** [comment]
Microsoft.AspNetCore.OData 7.0.1

**Comment by biaol-odata** [comment]
@CarefreeXT can you provide more details of your code, such as code on client and server sides? The error message "System.InvalidOperationException: This operation is not supported for a relative URI." indicates that it encounters a relative uri.

**Comment by CarefreeXT** [comment]
@biaol-odata Hello,The zip is code.
[ODataBug1635Sample.zip](https://github.com/OData/WebApi/files/2471334/ODataBug1635Sample.zip)
This is error Screenshot
![error](https://user-images.githubusercontent.com/12483062/46844004-bd404980-ce07-11e8-81ac-36fb7f1cd2c8.png)

**Comment by bbycroft** [comment]
This appears to be a regression from AspNet.OData to AspNetCore.OData, where the batch handler crashes when trying to parse a batch request that contains sub-requests with relative urls (using Content-ID's), such as

DELETE $27/SubItem/ref HTTP/1.1

Note that AspNet.OData correctly handled this, and the Microsoft.OData.Client generates these batches links.

### Assemblies affected

* Microsoft.AspNetCore.OData 7.0.1

### Reproduce steps

*I'll add to this soon*

### Expected result

The batch handler should succeed correctly parse the request, and create a valid sub-request.

### Actual result

We get the exception:

> --InvalidOperationException
>    at System.Uri.get_Scheme()
>    at Microsoft.AspNet.OData.Batch.HttpRequestExtensions.CopyAbsoluteUrl(HttpRequest request, Uri uri)
>    at Microsoft.AspNet.OData.Batch.ODataBatchReaderExtensions.ReadOperationInternalAsync(ODataBatchReader reader, HttpContext originalContext, Guid batchId, Nullable`1 changeSetId, CancellationToken cancellationToken, Boolean bufferContentStream)
>    at Microsoft.AspNet.OData.Batch.ODataBatchReaderExtensions.ReadChangeSetRequestAsync(ODataBatchReader reader, HttpContext context, Guid batchId, CancellationToken cancellationToken)
>    at Microsoft.AspNet.OData.Batch.DefaultODataBatchHandler.ParseBatchRequestsAsync(HttpContext context)
>    at Microsoft.AspNet.OData.Batch.DefaultODataBatchHandler.ProcessBatchAsync(HttpContext context, RequestDelegate nextHandler)
>    at Microsoft.AspNet.OData.Batch.ODataBatchMiddleware.Invoke(HttpContext context)

### Additional detail

In the AspNetCore version, the issue is this line:
https://github.com/OData/WebApi/blob/bbbaebfba53a01e289f25a72dc5863da1b547a8b/src/Microsoft.AspNetCore.OData/Batch/ODataBatchReaderExtensions.cs#L127
which does not safely handle relative urls.

The corresponding line in the AspNet version, here:
https://github.com/OData/WebApi/blob/bbbaebfba53a01e289f25a72dc5863da1b547a8b/src/Microsoft.AspNet.OData/Batch/ODataBatchReaderExtensions.cs#L152
works correctly with the relative urls.

**Comment by shatteredarm** [comment]
I just ran into this issue. Is there a workaround, besides not using batch requests?
