### ISSUE TITLE
v5.6: Odata+WebApi Filtering Open Dynamic Objects. SingleValueOpenPropertyAccess.

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#169]
I am attempting to apply an Odataquery against a collection of Json objects
(OpenType / Dynamic). I have instantiated my json as "MyDynamicObjects", a
class which simply enumerates each json property in a DynamicProperties
dictionary (as demonstrated in the opentype samples).  

    
    
     public class MyDynamicObject : Dictionary<string, object>
        {
            public IDictionary<string, object> DynamicProperties
            {
                get { return this; }
            } 
        }

I am serving this object via a WebApi controller.  

    
    
     [EnableQuery(PageSize = 25, MaxExpansionDepth = 5)]
            public IQueryable Get(ODataQueryOptions<MyDynamicObject> options)
            {
                return MyRepository.AsQueryable();
            }

The method works fine so long as I do not attempt to filter my data. When I
attempt to filter my data, it dies.  

    
    
        "Message": "The query specified in the URI is not valid. Validating OData QueryNode of kind SingleValueOpenPropertyAccess is not supported by FilterQueryValidator.",
        "ExceptionMessage": "Validating OData QueryNode of kind SingleValueOpenPropertyAccess is not supported by FilterQueryValidator.",
        "ExceptionType": "System.NotSupportedException",
        "StackTrace": "   at System.Web.OData.Query.Validators.FilterQueryValidator.ValidateSingleValueNode(SingleValueNode node, ODataValidationSettings settings)
       at System.Web.OData.Query.Validators.FilterQueryValidator.ValidateQueryNode(QueryNode node, ODataValidationSettings settings)
       at System.Web.OData.Query.Validators.FilterQueryValidator.ValidateConvertNode(ConvertNode convertNode, ODataValidationSettings settings)
       at System.Web.OData.Query.Validators.FilterQueryValidator.ValidateSingleValueNode(SingleValueNode node, ODataValidationSettings settings)
      at System.Web.OData.Query.Validators.FilterQueryValidator.ValidateQueryNode(QueryNode node, ODataValidationSettings settings)
       at System.Web.OData.Query.Validators.FilterQueryValidator.ValidateLogicalOperator(BinaryOperatorNode binaryNode, ODataValidationSettings settings)
       at System.Web.OData.Query.Validators.FilterQueryValidator.ValidateBinaryOperatorNode(BinaryOperatorNode binaryOperatorNode, ODataValidationSettings settings)
      at System.Web.OData.Query.Validators.FilterQueryValidator.ValidateSingleValueNode(SingleValueNode node, ODataValidationSettings settings)
      at System.Web.OData.Query.Validators.FilterQueryValidator.ValidateQueryNode(QueryNode node, ODataValidationSettings settings)
       at System.Web.OData.Query.Validators.FilterQueryValidator.Validate(FilterQueryOption filterQueryOption, ODataValidationSettings settings)
       at System.Web.OData.Query.FilterQueryOption.Validate(ODataValidationSettings validationSettings)\r\n   at System.Web.OData.Query.Validators.ODataQueryValidator.Validate(ODataQueryOptions options, ODataValidationSettings validationSettings)
       at System.Web.OData.Query.ODataQueryOptions.Validate(ODataValidationSettings validationSettings)\r\n   at System.Web.OData.EnableQueryAttribute.ValidateQuery(HttpRequestMessage request, ODataQueryOptions queryOptions)
      at System.Web.OData.EnableQueryAttribute.ExecuteQuery(Object response, HttpRequestMessage request, HttpActionDescriptor actionDescriptor)
       at System.Web.OData.EnableQueryAttribute.OnActionExecuted(HttpActionExecutedContext actionExecutedContext)"
    

I am not sure how to proceed. Is Filtering even supported ? If not when is it
scheduled to be supported.  
  
Lastly, I have tried other ways of going about this such as returning a
newtonsoft JObject and calling the Apply method myself.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 2187](http://aspnetwebstack.codeplex.com/workitem/2187)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Nov 14, 2014 at 7:49 PM
**Reported by:**	SimpleNick
**Updated on:**	Tue at 8:36 AM
**Updated by:**	cysu

**Comment by xuzhg** [comment]
It should be fixed. See: https://github.com/OData/WebApi/pull/250
Thanks.
