### ISSUE TITLE
No coercion operator is defined between types 'Microsoft.OData.Edm.Date' and 'System.DateTimeOffset'.

### ISSUE THREAD

**Issue by svyme** [OData/WebApi#1725]
We decided to finally update move from oData 6.14 to 7.5 to enjoy new features, fixes, and improvements.
Went through all required code changes and all looked good until we got to testing endpoints where $filter contains a date field ($filter=AsOfDate eq 2018-01-04)

Getting the below exception when applying query options:
No coercion operator is defined between types 'Microsoft.OData.Edm.Date' and 'System.DateTimeOffset'.

I see two more issues were already opened to report this bug. Both were closed without any solution. How come?
A workaround to require API consumers to change just because we update internal library is not a workable approach.

We were able to reproduce this with versions 7.5, 7. But not version 6.14.

**Comment by madansr7** [comment]
@svyme , could you please your metadata with us? Are you using EF or EF core?

**Comment by svyme** [comment]
Stack trace:
   at System.Linq.Expressions.Expression.GetUserDefinedCoercionOrThrow(ExpressionType coercionType, Expression expression, Type convertToType)
   at System.Linq.Expressions.Expression.Convert(Expression expression, Type type, MethodInfo method)
   at System.Linq.Expressions.Expression.Convert(Expression expression, Type type)
   at Microsoft.AspNet.OData.Query.Expressions.ExpressionBinderBase.CreateConvertExpression(ConvertNode convertNode, Expression source)
   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.BindConvertNode(ConvertNode convertNode)
   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.BindSingleValueNode(SingleValueNode node)
   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.Bind(QueryNode node)
   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.BindBinaryOperatorNode(BinaryOperatorNode binaryOperatorNode)
   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.BindSingleValueNode(SingleValueNode node)
   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.Bind(QueryNode node)
   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.BindConvertNode(ConvertNode convertNode)
   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.BindSingleValueNode(SingleValueNode node)
   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.Bind(QueryNode node)
   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.BindBinaryOperatorNode(BinaryOperatorNode binaryOperatorNode)
   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.BindSingleValueNode(SingleValueNode node)
   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.Bind(QueryNode node)
   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.BindExpression(SingleValueNode expression, RangeVariable rangeVariable, Type elementType)
   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.BindFilterClause(FilterBinder binder, FilterClause filterClause, Type filterType)
   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.Bind(IQueryable baseQuery, FilterClause filterClause, Type filterType, ODataQueryContext context, ODataQuerySettings querySettings)
   at Microsoft.AspNet.OData.Query.FilterQueryOption.ApplyTo(IQueryable query, ODataQuerySettings querySettings)
   at Microsoft.AspNet.OData.Query.ODataQueryOptions.ApplyTo(IQueryable query, ODataQuerySettings querySettings)
   at Microsoft.AspNet.OData.Query.ODataQueryOptions`1.ApplyTo(IQueryable query, ODataQuerySettings querySettings)
   at Microsoft.AspNet.OData.Query.ODataQueryOptions.ApplyTo(IQueryable query)
   at Microsoft.AspNet.OData.Query.ODataQueryOptions`1.ApplyTo(IQueryable query)
   at MyApp.WebApi.Controllers.CommonController`1.GetPageResultTask[T](IQueryable`1 query, ODataQueryOptions`1 queryOptions) in C:\MyApp.WebApi\Controllers\CommonController.cs:line 23
   at MyApp.WebApi.Controllers.MyController.Get(ODataQueryOptions`1 queryOptions) in C:\MyApp.WebApi\Controllers\MyController.cs:line 18
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass12.<GetExecutor>b__8(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
   
Line 23 in CommonController:
		protected Task<PageResult<T>> GetPageResultTask<T>(IQueryable<T> query, ODataQueryOptions<T> queryOptions)
        {
            query = queryOptions.ApplyTo(query) as IQueryable<T>;

MyController inherits CommonController.

Thank you.

**Comment by svyme** [comment]
We're not using EF

**Comment by xuzhg** [comment]
@svyme I see. 

 `AsOfDate` is 'Edm.DateTimeOffset' type in your model. Meanwhile, `2018-01-04` is now converted to `Edm.Date` object.

In your scenario, you should use `date` built-in method.

_$filter=**date**(AsOfDate) eq 2018-01-04_

It should work.

**Comment by svyme** [comment]
We do not have the luxury to ask our API consumers to change how they make the call.
And it is not a workable solution to ask client apps to change because of a library update in the service.
Our metadata is created from DTOs that have DateTime? AsOfDate. 
Shouldn't there be a conversion from Edm.Date to System.DateTime?

**Comment by xuzhg** [comment]
@svyme I merged a change to make the functionality back compatible. If It works, would you please try the nightly and give us a feedback?

**Comment by svyme** [comment]
The fix works as expected. Thanks!

**Comment by matdavies** [comment]
@xuzhg Where is the nightly that you reference?  The 7.x nightly that is referred to in readme.md does not seem to exist any more?: https://www.myget.org/F/webapinetcore does not exist, so it's only possible to get the 6.x nightlies at the moment.  That doesn't work for me because we need to ensure a dependency on Microsoft.Extensions.DependencyInjection.Abstraction >= 2, and 6 requires >= 1 && < 2

**Comment by xuzhg** [comment]
@matdavies https://www.myget.org/F/webapinetcore is still there. Is there any problem for you to access the nightly build from this Nuget source?

**Comment by matdavies** [comment]
@xuzhg Sorry, yes, you are right, that is still there, and there is no problem accessing the nightly build from there.  I was confused because https://www.myget.org/gallery/webapinetcore (7.x nightly gallery page) does not exist, whereas https://www.myget.org/gallery/webapinightly (6.x nightly gallery page) does.  I've raised an issue re the problem in the readme.md.  Can confirm that the nightly fixed this same issue that I was experiencing too.  Thanks!
