### ISSUE TITLE
Bad error message if no function return type specified in model build

### ISSUE THREAD

**Issue by sandersaares** [OData/WebApi#1730]
Bad error message if no function return type specified.

### Assemblies affected

```
<PackageReference Include="Microsoft.AspNetCore.OData" Version="7.1.0" />
```

### Reproduce steps

```
var builder = new ODataConventionModelBuilder();

var movie = builder.EntitySet<Movie>(nameof(Movie));
var movieFoo = movie.EntityType.Function("Foo");

// Problem occurs if this is commented out.
// movieFoo.Returns<string>();

// Exception thrown from this.
return builder.GetEdmModel();
```

### Expected result

Auto-detect return type.

Alternative expected result: reasonable error along the lines of "you must specify the return type".

### Actual result

```
System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null.
Arg_ParamName_Name
  Source=Microsoft.OData.Edm
  StackTrace:
   at Microsoft.OData.Edm.EdmUtil.CheckArgumentNull[T](T value, String parameterName)
   at Microsoft.OData.Edm.EdmFunction..ctor(String namespaceName, String name, IEdmTypeReference returnType, Boolean isBound, IEdmPathExpression entitySetPathExpression, Boolean isComposable)
   at Microsoft.AspNet.OData.Builder.EdmModelHelperMethods.CreateFunctionImport(FunctionConfiguration function, EdmEntityContainer container, IEdmTypeReference returnReference, IEdmExpression expression, IEdmPathExpression pathExpression)
   at Microsoft.AspNet.OData.Builder.EdmModelHelperMethods.AddOperations(EdmModel model, IEnumerable`1 configurations, EdmEntityContainer container, Dictionary`2 edmTypeMap, IDictionary`2 edmNavigationSourceMap)
   at Microsoft.AspNet.OData.Builder.EdmModelHelperMethods.BuildEdmModel(ODataModelBuilder builder)
   at Microsoft.AspNet.OData.Builder.ODataConventionModelBuilder.GetEdmModel()
   at App.WebApi.Program.GetEdmModel() in C:\Source\CmsTinkering\App.WebApi\Program.cs:line 183
   at App.WebApi.Program.<>c.<Configure>b__12_0(IRouteBuilder routes) in C:\Source\CmsTinkering\App.WebApi\Program.cs:line 171
   at Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder app, Action`1 configureRoutes)
   at App.WebApi.Program.Configure(IApplicationBuilder app) in C:\Source\CmsTinkering\App.WebApi\Program.cs:line 168
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Server.IISIntegration.IISSetupFilter.<>c__DisplayClass4_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

```

**Comment by rblanca** [comment]
Confirmed....on Net 7...any workaround? Thanks!
