### ISSUE TITLE
InvalidOperationException with Bad Request - Error in query syntax

### ISSUE THREAD

**Issue by B4st13n** [OData/WebApi#1789]
InvalidOperationException: The path template 'Classes({id})/Bookings({bookingId})' on the action 'GetBookingFromClass' in controller 'Classes' is not a valid OData path template. Bad Request - Error in query syntax.

InvalidOperationException: The path template 'Classes({classKey})/Bookings({key})' on the action 'DeleteBooking' in controller 'Classes' is not a valid OData path template. Bad Request - Error in query syntax.

But no issue on [ODataRoute("Classes({id})/Bookings")]
        public async Task<IActionResult> GetBookings([FromODataUri] Guid id)

The system allow me to generate a route for list of booking but doesn't allow me to generate a route for getting a specific booking.

### Assemblies affected

Microsoft.AspNet.OData.Routing.Conventions.AttributeRoutingConvention.GetODataPathTemplate(string prefix, string pathTemplate, IServiceProvider requestContainer, string controllerName, string actionName)
Assembly Microsoft.AspNetCore.OData, Version=7.1.0.21120, Culture=neutral, PublicKeyToken=31bf3856ad364e35

### Additional detail

'Booking' in a contained collection of 'Classes'. 'Classes' is also a contained collection of another entity but can also be reached from root.

My GetEdmModel() define
builder.EntitySet<Class>("Classes");

System.InvalidOperationException: The path template 'Classes({classKey})/Bookings({key})' on the action 'DeleteBooking' in controller 'Classes' is not a valid OData path template. Bad Request - Error in query syntax.
   at Microsoft.AspNet.OData.Routing.Conventions.AttributeRoutingConvention.GetODataPathTemplate(String prefix, String pathTemplate, IServiceProvider requestContainer, String controllerName, String actionName)
   at Microsoft.AspNet.OData.Routing.Conventions.AttributeRoutingConvention.<>c__DisplayClass11_0.<GetODataPathTemplates>b__1(ODataRouteAttribute route)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Microsoft.AspNet.OData.Routing.Conventions.AttributeRoutingConvention.BuildAttributeMappings(IEnumerable`1 controllerActions)
   at Microsoft.AspNet.OData.Routing.Conventions.AttributeRoutingConvention.get_AttributeMappings()
   at Microsoft.AspNet.OData.Routing.Conventions.AttributeRoutingConvention.SelectAction(RouteContext routeContext)
   at Microsoft.AspNet.OData.Routing.ODataActionSelector.SelectCandidates(RouteContext context)
   at Microsoft.AspNetCore.Mvc.Internal.MvcRouteHandler.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.Route.OnRouteMatched(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteBase.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by raheph** [comment]
@B4st13n Would you please share us your CSDL information?

**Comment by B4st13n** [comment]
You means this 

```
<?xml version="1.0" encoding="utf-8"?>
<edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
    <edmx:DataServices>
        <Schema Namespace="Oyg" xmlns="http://docs.oasis-open.org/odata/ns/edm">
            <EntityType Name="Owner">
                <Key>
                    <PropertyRef Name="Id" />
                </Key>
                <Property Name="Id" Type="Edm.Guid" Nullable="false" />
                <Property Name="Name" Type="Edm.String" />
                <Property Name="Email" Type="Edm.String" />
                <Property Name="PhoneNumber" Type="Edm.String" />
                <Property Name="Hash" Type="Edm.String" />
                <Property Name="ConfigurationString" Type="Edm.String" />
                <NavigationProperty Name="Teachers" Type="Collection(Oyg.Teacher)" ContainsTarget="true" />
                <NavigationProperty Name="Locations" Type="Collection(Oyg.Location)" ContainsTarget="true" />
                <NavigationProperty Name="Classes" Type="Collection(Oyg.Class)" ContainsTarget="true" />
            </EntityType>
            <EntityType Name="Student">
                <Key>
                    <PropertyRef Name="Id" />
                </Key>
                <Property Name="Id" Type="Edm.Guid" Nullable="false" />
                <Property Name="Name" Type="Edm.String" />
                <Property Name="Email" Type="Edm.String" />
                <Property Name="PhoneNumber" Type="Edm.String" />
                <Property Name="Hash" Type="Edm.String" />
                <Property Name="ConfigurationString" Type="Edm.String" />
            </EntityType>
            <EntityType Name="Class">
                <Key>
                    <PropertyRef Name="Id" />
                </Key>
                <Property Name="Id" Type="Edm.Guid" Nullable="false" />
                <Property Name="Title" Type="Edm.String" />
                <Property Name="Description" Type="Edm.String" />
                <Property Name="StartTime" Type="Edm.DateTimeOffset" Nullable="false" />
                <Property Name="EndTime" Type="Edm.DateTimeOffset" Nullable="false" />
                <Property Name="Price_HKD" Type="Edm.Decimal" Nullable="false" />
                <Property Name="Status" Type="Oyg.ScheduleStatus" Nullable="false" />
                <Property Name="Positions" Type="Edm.Int32" Nullable="false" />
                <Property Name="Bookings" Type="Collection(Oyg.Booking)" />
                <NavigationProperty Name="Owner" Type="Oyg.Owner" />
                <NavigationProperty Name="Teacher" Type="Oyg.Teacher" />
                <NavigationProperty Name="Location" Type="Oyg.Location" />
            </EntityType>
            <ComplexType Name="Booking">
                <Property Name="Id" Type="Edm.Guid" Nullable="false" />
                <Property Name="Position" Type="Edm.Int32" Nullable="false" />
                <Property Name="ReservationTime" Type="Edm.DateTimeOffset" Nullable="false" />
                <Property Name="CancelTime" Type="Edm.DateTimeOffset" />
                <NavigationProperty Name="Class" Type="Oyg.Class" Nullable="false" />
                <NavigationProperty Name="Student" Type="Oyg.Student" Nullable="false" />
            </ComplexType>
            <EntityType Name="Teacher">
                <Key>
                    <PropertyRef Name="Id" />
                </Key>
                <Property Name="Id" Type="Edm.Guid" Nullable="false" />
                <Property Name="Name" Type="Edm.String" />
                <Property Name="Description" Type="Edm.String" />
                <Property Name="Email" Type="Edm.String" />
                <Property Name="PhoneNumber" Type="Edm.String" />
                <Property Name="Website" Type="Edm.String" />
                <NavigationProperty Name="Owner" Type="Oyg.Owner" />
            </EntityType>
            <EntityType Name="Location">
                <Key>
                    <PropertyRef Name="Id" />
                </Key>
                <Property Name="Id" Type="Edm.Guid" Nullable="false" />
                <Property Name="Title" Type="Edm.String" />
                <Property Name="Description" Type="Edm.String" />
                <Property Name="Geolocalisation" Type="Edm.String" />
                <Property Name="Address" Type="Edm.String" />
                <Property Name="Facilities" Type="Edm.String" />
                <NavigationProperty Name="Owner" Type="Oyg.Owner" />
            </EntityType>
            <EnumType Name="ScheduleStatus">
                <Member Name="Draft" Value="0" />
                <Member Name="Published" Value="1" />
                <Member Name="Cancelled" Value="2" />
            </EnumType>
            <EntityContainer Name="OygContainer">
                <EntitySet Name="Owners" EntityType="Oyg.Owner" />
                <EntitySet Name="Students" EntityType="Oyg.Student" />
                <EntitySet Name="Classes" EntityType="Oyg.Class">
                    <NavigationPropertyBinding Path="Bookings/Class" Target="Classes" />
                    <NavigationPropertyBinding Path="Bookings/Student" Target="Students" />
                    <NavigationPropertyBinding Path="Owner" Target="Owners" />
                </EntitySet>
            </EntityContainer>
        </Schema>
        <Schema Namespace="Oyg.Actions" xmlns="http://docs.oasis-open.org/odata/ns/edm">
            <Action Name="Register" IsBound="true">
                <Parameter Name="bindingParameter" Type="Oyg.Class" />
                <Parameter Name="studentId" Type="Edm.Guid" Nullable="false" />
                <ReturnType Type="Oyg.Booking" />
            </Action>
            <Action Name="CancelRegistration" IsBound="true">
                <Parameter Name="bindingParameter" Type="Oyg.Class" />
                <Parameter Name="studentId" Type="Edm.Guid" Nullable="false" />
            </Action>
        </Schema>
    </edmx:DataServices>
</edmx:Edmx>
```

**Comment by B4st13n** [comment]
And FYI

```
    public class Class
    {
        [Key]
        public Guid Id { get; set; }

        /// <summary>
        /// Title of the class
        /// </summary>
        [StringLength(40)]
        public string Title { get; set; }

        /// <summary>
        /// Description of this class
        /// </summary>
        [StringLength(400)]
        public string Description { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public DateTime StartTime { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public DateTime EndTime { get; set; }

        /// <summary>
        /// Owner of this class
        /// </summary>
        public Owner Owner { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public Teacher Teacher { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public Location Location { get; set; }

        /// <summary>
        /// Price of the class in HKD
        /// </summary>
        public decimal Price_HKD { get; set; }

        /// <summary>
        /// Number of positions availabe for students
        /// </summary>
        public ScheduleStatus Status { get; set; }

        public int Positions { get; set; }

        [Contained]
        public ICollection<Booking> Bookings { get; set; }
    }
```

So yes Bookings is contained

**Comment by B4st13n** [comment]
This can help?

```
 private static IEdmModel GetEdmModel()
        {
            ODataConventionModelBuilder builder = new ODataConventionModelBuilder();
            builder.Namespace = "Oyg";
            builder.ContainerName = "OygContainer";
            builder.EntitySet<Owner>("Owners");
            builder.EntitySet<Student>("Students");
            builder.EntitySet<Class>("Classes");
            //-- builder.EntitySet<Location>("Locations");
            //-- builder.EntitySet<Teacher>("Teachers");

            // action register to a class
            var registerAction = builder.EntityType<Class>().Action("Register");
            registerAction.Returns<Booking>();
            registerAction.Parameter<Guid>("studentId");
            registerAction.Namespace = "Oyg.Actions";

            // action cancel current registration
            var cancelRegistrationAction = builder.EntityType<Class>().Action("CancelRegistration");
            cancelRegistrationAction.Parameter<Guid>("studentId");
            cancelRegistrationAction.Namespace = "Oyg.Actions";

            return builder.GetEdmModel();
        }```

**Comment by B4st13n** [comment]
Last information I used partial classes for contained collections. So I have a ClassesController.cs file and a ClassesController.Booking.cs file for  `public partial class ClassesController : ODataController`

**Comment by xuzhg** [comment]
@B4st13n That's because the `Bookings` is configured as "Structural property" and its type is complex type. Complex type is structural type without key,therefore,  your path template 'Classes({id})/Bookings({bookingId})' can't work.

The root cause is the call "registerAction.Returns<Booking>()", this line will configure the "Booking" type as complex type. I think if you call "registerAction.ReturnsFromEntitySet<Booking>("Bookings")" can resolve the problem. Thanks

**Comment by B4st13n** [comment]
Magic... I mean, I didn't understood but it works. Thank you very much for the help. Where can I find a good documentation explaining all this. I followed some tutorial on web and Pluralsight and the details about all this are not in these course.

**Comment by xuzhg** [comment]
@B4st13n http://odata.github.io/WebApi/ has some tutorials related to the Web API. Of course, if you have further questions/concerns/problems, please feel free file new issues for us. Thanks a lot!
