### ISSUE TITLE
$apply(groupby) failing on simple SQL Server example with comparison exception

### ISSUE THREAD

**Issue by bschuth** [OData/WebApi#1811]
** This is for AspNetCore.OData.**

I am attempting to use `$apply=groupby((colname))` to obtain the unique values for a single column. This works correctly against a simple in-memory list. However, when running against the simplest possible SQL example (I am using SQL Server 2014), I get 

>System.NotSupportedException: Comparison operators not supported for type 'System.Collections.Generic.Dictionary`2[System.String,System.Object]'. 

Full stack trace is very long, appended at end.

### Assemblies affected

I was running against Microsoft.AspNetCore.OData 7.1.0 to start, but I am currently running against nightlies (7.1.1-Nightly201905201318 today) with the same result.

### Reproduce steps

A full sample can be found at https://github.com/bschuth/OdataApplyGroupDefect.git . In short:

1. A single table with three columns:

```sql
CREATE TABLE Locations (
  LocationId INT PRIMARY KEY,
  Name NVARCHAR(20) NOT NULL,
  PersonResponsible NVARCHAR(20) NULL);
```
2. Populate with a few rows (all have a PersonResponible value).
3. Configure by convention in Startup.cs:

```cs
            ODataConventionModelBuilder builder = new ODataConventionModelBuilder();
            builder.EntitySet<Location>("Locations");
            return builder.GetEdmModel();
```

4. Simple controller method. I use `opts.ApplyTo` here just so I can debug a little more but `[EnableQuery]` gets the same result...

```cs
        public ActionResult<Location> Get(ODataQueryOptions<Location> opts, string format="")
        {
            var table = DataContextFactory.GetContext().GetTable<Location>();
            return Ok(opts.ApplyTo(table));
        }
```

### Expected result

A return value with the distinct PersonResponsible values.

### Actual result
Error. Stack trace from console:

```
      Connection id "0HLMTD07JVUU0", Request id "0HLMTD07JVUU0:00000001": An unh
andled exception was thrown by the application.
System.NotSupportedException: Comparison operators not supported for type 'Syste
m.Collections.Generic.Dictionary`2[System.String,System.Object]'.
   at System.Data.Linq.SqlClient.SqlBinder.Visitor.VisitBinaryOperator(SqlBinary
 bo)
   at System.Data.Linq.SqlClient.SqlVisitor.Visit(SqlNode node)
   at System.Data.Linq.SqlClient.SqlBinder.Visitor.VisitExpression(SqlExpression
 expr)
   at System.Data.Linq.SqlClient.SqlBinder.Visitor.VisitBinaryOperator(SqlBinary
 bo)
   at System.Data.Linq.SqlClient.SqlVisitor.Visit(SqlNode node)
   at System.Data.Linq.SqlClient.SqlBinder.Visitor.VisitExpression(SqlExpression
 expr)
   at System.Data.Linq.SqlClient.SqlBinder.Visitor.VisitBinaryOperator(SqlBinary
 bo)
   at System.Data.Linq.SqlClient.SqlVisitor.Visit(SqlNode node)
   at System.Data.Linq.SqlClient.SqlBinder.Visitor.VisitExpression(SqlExpression
 expr)
   at System.Data.Linq.SqlClient.SqlVisitor.Visit(SqlNode node)
   at System.Data.Linq.SqlClient.SqlBinder.Visitor.VisitExpression(SqlExpression
 expr)
   at System.Data.Linq.SqlClient.SqlBinder.Visitor.VisitBinaryOperator(SqlBinary
 bo)
   at System.Data.Linq.SqlClient.SqlVisitor.Visit(SqlNode node)
   at System.Data.Linq.SqlClient.SqlBinder.Visitor.VisitExpression(SqlExpression
 expr)
   at System.Data.Linq.SqlClient.SqlBinder.Visitor.VisitBinaryOperator(SqlBinary
 bo)
   at System.Data.Linq.SqlClient.SqlVisitor.Visit(SqlNode node)
   at System.Data.Linq.SqlClient.SqlBinder.Visitor.VisitExpression(SqlExpression
 expr)
   at System.Data.Linq.SqlClient.SqlBinder.Visitor.VisitBinaryOperator(SqlBinary
 bo)
   at System.Data.Linq.SqlClient.SqlVisitor.Visit(SqlNode node)
   at System.Data.Linq.SqlClient.SqlBinder.Visitor.VisitExpression(SqlExpression
 expr)
   at System.Data.Linq.SqlClient.SqlVisitor.Visit(SqlNode node)
   at System.Data.Linq.SqlClient.SqlBinder.Visitor.VisitExpression(SqlExpression
 expr)
   at System.Data.Linq.SqlClient.SqlBinder.Visitor.VisitSelect(SqlSelect select)

   at System.Data.Linq.SqlClient.SqlVisitor.Visit(SqlNode node)
   at System.Data.Linq.SqlClient.SqlVisitor.VisitSequence(SqlSelect sel)
   at System.Data.Linq.SqlClient.SqlVisitor.VisitMultiset(SqlSubSelect sms)
   at System.Data.Linq.SqlClient.SqlBinder.Visitor.VisitSubSelect(SqlSubSelect s
s)
   at System.Data.Linq.SqlClient.SqlVisitor.Visit(SqlNode node)
   at System.Data.Linq.SqlClient.SqlBinder.Visitor.VisitExpression(SqlExpression
 expr)
   at System.Data.Linq.SqlClient.SqlBinder.Visitor.FetchExpression(SqlExpression
 expr)
   at System.Data.Linq.SqlClient.SqlBinder.Visitor.VisitGrouping(SqlGrouping g)
   at System.Data.Linq.SqlClient.SqlVisitor.Visit(SqlNode node)
   at System.Data.Linq.SqlClient.SqlBinder.Visitor.VisitExpression(SqlExpression
 expr)
   at System.Data.Linq.SqlClient.SqlBinder.Visitor.VisitSelect(SqlSelect select)
   at System.Data.Linq.SqlClient.SqlVisitor.Visit(SqlNode node)
   at System.Data.Linq.SqlClient.SqlBinder.Visitor.VisitAlias(SqlAlias a)
   at System.Data.Linq.SqlClient.SqlVisitor.Visit(SqlNode node)
   at System.Data.Linq.SqlClient.SqlVisitor.VisitSource(SqlSource source)
   at System.Data.Linq.SqlClient.SqlBinder.Visitor.VisitSelect(SqlSelect select)
   at System.Data.Linq.SqlClient.SqlVisitor.Visit(SqlNode node)
   at System.Data.Linq.SqlClient.SqlProvider.BuildQuery(ResultShape resultShape,
 Type resultType, SqlNode node, ReadOnlyCollection`1 parentParameters, SqlNodeAn
notations annotations)
   at System.Data.Linq.SqlClient.SqlProvider.BuildQuery(Expression query, SqlNod
eAnnotations annotations)
   at System.Data.Linq.SqlClient.SqlProvider.System.Data.Linq.Provider.IProvider
.Execute(Expression query)
   at System.Data.Linq.DataQuery`1.System.Collections.IEnumerable.GetEnumerator(
)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(J
sonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty m
ember, JsonContainerContract collectionContract, JsonProperty containerProperty)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonW
riter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Ob
ject value, Type objectType)
   at Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter.WriteObject(TextWr
iter writer, Object value)
   at Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter.<WriteResponseBody
Async>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__20
.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterA
sync>d__28`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedCo
ntext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilt
erAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultFilters>d__
26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilte
r>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecuted
Context context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope&
 scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsy
nc>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveN
ext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>
d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>
d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<Proce
ssRequests>d__185`1.MoveNext()
```

**Comment by kosinsky** [comment]
In your sample you using Linq to SQL (even you csproj includes Microsoft.EntityFrameworkCore.SqlServer nuget reference). Is it intentional or you meant to use EF Core? If you goal is to use EF Core you mean to use DbContext instead DataContext

Unfortunately, WebAPI doesn't work well with Linq to SQL (another issue https://github.com/OData/WebApi/issues/1807) 
In PR https://github.com/OData/WebApi/pull/1728  I added explicit exception for that https://github.com/OData/WebApi/pull/1728/files#diff-cffaed270dd0145cc05558a9c2457b50

**Comment by bschuth** [comment]
No, this sample reproduces an issue we found against a Linq-to-SQL code base. Turns out #1807 was submitted by my colleague across the hall to me working against the same code base.

I will look at the PR you reference to see if I can understand what is going on. Are WebApi's problems with LINQ to SQL something that can be fixed, or are we out of luck? Thank you!

**Comment by kosinsky** [comment]
I'm no sure that it will be easy fix to implement LINQ to SQL support. 

To support $select/$expand/$apply we need generate IQueryable with arbitrary projection. It's achived by generation something like (very schematically)
```
Select(it => new Wrapper() { Name = 'Selected1', Value = it.Selected1, Next = new Wrapper() {
                                                                Name = 'Selected2', Value = it.Selected2, Next = ...
}
})
```
Wrapper has Dictionary<string, object> property that used to reading that projection in generic way. Per my understanding LINQ to SQL looks at all public properties and try to do comparison for all of them. To summarize Linq-to-sql has problem with objects with non primitive properties.

Theoretically we could try to hide these details from Linq-to-sql. However, it's difficult to estimate how difficult it is.
