### ISSUE TITLE
Does the library supports filter path segment (/$filter) ?

### ISSUE THREAD

**Issue by savelievser** [OData/WebApi#1958]
According to 
http://docs.oasis-open.org/odata/odata/v4.01/cs01/part2-url-conventions/odata-v4.01-cs01-part2-url-conventions.html#sec_AddressingaSubsetofaCollection
there should be support of /$filter path segment. Does the library support it now?

**Comment by robertmclaws** [comment]
We are experiencing a situation where we have a unit test in Restier that leverages the filter segment: "/Books/$filter(endswith(Title,'The'))/DiscontinueBooks()". It's giving us a `NullReferenceException`:

```
{
"Message":"An error has occurred.",
"ExceptionMessage":"The method or operation is not implemented.",
"ExceptionType":"System.NotImplementedException",
"StackTrace":"   
   at Microsoft.OData.UriParser.PathSegmentHandler.Handle(FilterSegment segment)
   at Microsoft.OData.UriParser.FilterSegment.HandleWith(PathSegmentHandler handler)
   at Microsoft.OData.UriParser.ODataPath.WalkWith(PathSegmentHandler handler)
   at Microsoft.AspNet.OData.Routing.DefaultODataPathHandler.Parse(String serviceRoot, String odataPath, IServiceProvider requestContainer, Boolean template)
   at Microsoft.AspNet.OData.Routing.DefaultODataPathHandler.Parse(String serviceRoot, String odataPath, IServiceProvider requestContainer)
   at Microsoft.AspNet.OData.Routing.ODataPathRouteConstraint.GetODataPath(String oDataPathString, String uriPathString, String queryString, Func`1 requestContainerFactory)
   at Microsoft.AspNet.OData.Routing.ODataPathRouteConstraint.Match(HttpRequestMessage request, IHttpRoute route, String parameterName, IDictionary`2 values, HttpRouteDirection routeDirection)
   at System.Web.Http.Routing.HttpRoute.ProcessConstraint(HttpRequestMessage request, Object constraint, String parameterName, HttpRouteValueDictionary values, HttpRouteDirection routeDirection)
   at System.Web.Http.Routing.HttpRoute.ProcessConstraints(HttpRequestMessage request, HttpRouteValueDictionary values, HttpRouteDirection routeDirection)
   at System.Web.Http.Routing.HttpRoute.GetRouteData(String virtualPathRoot, HttpRequestMessage request)
   at System.Web.Http.HttpRouteCollection.GetRouteData(HttpRequestMessage request)
   at System.Web.Http.Dispatcher.HttpRoutingDispatcher.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Web.Http.HttpServer.<SendAsync>d__24.MoveNext()"
}
```
Are filter segments enabled in ODL? Thanks!
