### ISSUE TITLE
Work with hierarchical classes.

### ISSUE THREAD

**Issue by SenyaMur** [OData/WebApi#1972]
Bad work  with expand in hierarchical classes when parent class has navigation property and expand all in child class

### Assemblies affected

```
<PackageReference Include="Microsoft.AspNetCore.OData" Version="7.2.2"/>
<PackageReference Include="Microsoft.OData.Core" Version="7.6.2" />
<PackageReference Include="Microsoft.AspNetCore.OData" Version="7.2.2"/>
```

### Reproduce steps

```cs
  [DataContract]
  public abstract class BaseApiModel {
    [DataMember(Name = "id", EmitDefaultValue = false)]
    public virtual long Id { get; set; }
    [DataMember(Name = "name", EmitDefaultValue = false)]
    public string Name { get; set; }
  }
  
  [DataContract]
  public class InstrumentType: BaseApiModel {
   [DataMember(Name = "instrumentCode", EmitDefaultValue = false)]
    public string InstrumentCode { get; set; }    
  }

  [DataContract]
  public class Instrument : BaseApiModel {
    [DataMember(Name = "instrumentType", EmitDefaultValue = false)]
    public InstrumentType InstrumentType { get; set; }
  }

  [DataContract]
  public class PreciousApiModel : Instrument {
  }

 [DataContract]
  public class Bullion : Instrument {   
    [DataMember(Name = "baseInstrument", EmitDefaultValue = false)]
    public Instrument BaseInstrument { get; set; }
    [DataMember(Name = "ligatureMass", EmitDefaultValue = false)]
    public decimal? LigatureMass { get; set; }
   }
  
  [DataContract]
  public class PaymentApiModel {
    [DataMember(Name = "id")]
    public long Id { get; set; }

    [DataMember(Name = "instrument")]
    public Instrument Instrument { get; set; }
  
    [DataMember(Name = "amount")]
    public decimal Amount { get; set; }

    [DataMember(Name = "date")]
    public DateTimeOffset Date { get; set; }
  }
//Configure Edm
public void Apply(ODataModelBuilder builder, ApiVersion apiVersion) {
builder.EntitySet<InstrumentType>("InstrumentFinancialTypes");
builder.EntitySet<Instrument>("InstrumentsFinancial");
builder.EntitySet<Precious>("Precious");
      builder.EntitySet<Bullion>("Bullions");
builder.EntitySet<Payment>("Payments");
}

//In DbContext

builder.Entity<Instrument>(entity => {
        entity.ToTable("SEC_INSTRUMENT")
          .HasDiscriminator<string>("INSTRUMENTTYPE_CODE")
          .HasValue<Precious>("PREC")
          .HasValue<Bullion>("INGT");
});
```
When request: http://localhost:5003/odata/Precious?$expand=*
In log catch exception:
```
System.InvalidOperationException: The EDM instance of type '[InstrumentType  Nullable=True]' is missing the property 'instrumentCode'.
```
If request: 
http://localhost:5003/odata/Payments?$expand=instrument($expand=*)
return instrument with only navigationProperty from Instrument.  I cant expand property for children classes.

Try extract children navigation properties:
http://localhost:5003/odata/Payments?$expand=instrument($expand=Bullion/baseInstrument)

In log catch exception:
```
An exception occurred while iterating over the results of a query for context type 'SoftWell.Ctor.Api.Admin.DAL.ResmanDbContext'.
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , QueryContext , TransparentIdentifier`2 )
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities[TOut,TIn](IEnumerable`1 results, QueryContext queryContext, IList`1 entityTrackingInfos, IList`1 entityAccessors)+MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , QueryContext , TransparentIdentifier`2 )
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities[TOut,TIn](IEnumerable`1 results, QueryContext queryContext, IList`1 entityTrackingInfos, IList`1 entityAccessors)+MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
```

How expand all navigation property in children classes (include parent navigation property) without exception ?
How expand in children class navigation property from parent class which use **HasDiscriminator**?

**Comment by xuzhg** [comment]
@SenyaMur Thanks for your information. Do you have a simple repo for us to dig more?

**Comment by SenyaMur** [comment]
I created example repo https://github.com/SenyaMur/odata-expand-hierarchy 
The repo contained tests which demonstaiting all bad situaltions.
