### ISSUE TITLE
expand list failed to work when upgrading to .net core 3.1

### ISSUE THREAD

**Issue by xiaotupansy** [OData/WebApi#1994]
Code works for .net core 2.2, Microsoft.AspNetCore.OData 7.2.2.
But after upgrading to .net core 3.1, Microsoft.AspNetCore.OData 7.3.0,
All expand for list in odata throws an exception:
Value cannot be null. (Parameter 'key')

### Assemblies affected

Microsoft.AspNetCore.OData 7.3.0
.net core 3.1

### Reproduce steps

After setting up odata environment, use following address to call api:
http://serveraddr/api/Order?$expand=Items

entity:

```
<EntityType Name="Order">
<Key>
<PropertyRef Name="Id"/>
</Key>
... other property
<NavigationProperty Name="Items" Type="Collection(YT.Core.DomainModel.OrderItem)"/>
</EntityType>
<EntityType Name="OrderItem">
<Key>
<PropertyRef Name="Id"/>
</Key>
... other property
</EntityType>
```

### Actual result

System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNullException()
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryGetValue(TKey key, TValue& value)
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at Microsoft.AspNet.OData.Query.Expressions.ModelContainer.GetModel(String id)
   at Microsoft.AspNet.OData.Query.Expressions.SelectExpandWrapper.GetModel()
   at Microsoft.AspNet.OData.Query.Expressions.SelectExpandWrapper.GetEdmType()
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataSerializerContext.GetEdmType(Object instance, Type type)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.GetResourceType(Object graph, ODataSerializerContext writeContext)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteResource(Object graph, ODataWriter writer, ODataSerializerContext writeContext, IEdmTypeReference expectedType)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteObjectInline(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteResourceSet(IEnumerable enumerable, IEdmTypeReference resourceSetType, ODataWriter writer, ODataSerializerContext writeContext)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteObjectInline(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteComplexAndExpandedNavigationProperty(IEdmProperty edmProperty, SelectItem selectItem, ResourceContext resourceContext, ODataWriter writer)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteExpandedNavigationProperties(SelectExpandNode selectExpandNode, ResourceContext resourceContext, ODataWriter writer)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteResource(Object graph, ODataWriter writer, ODataSerializerContext writeContext, IEdmTypeReference expectedType)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteObjectInline(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteResourceSet(IEnumerable enumerable, IEdmTypeReference resourceSetType, ODataWriter writer, ODataSerializerContext writeContext)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteObjectInline(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteObject(Object graph, Type type, ODataMessageWriter messageWriter, ODataSerializerContext writeContext)
   at Microsoft.AspNet.OData.Formatter.ODataOutputFormatterHelper.WriteToStream(Type type, Object value, IEdmModel model, ODataVersion version, Uri baseAddress, MediaTypeHeaderValue contentType, IWebApiUrlHelper internaUrlHelper, IWebApiRequestMessage internalRequest, IWebApiHeaders internalRequestHeaders, Func`2 getODataMessageWrapper, Func`2 getEdmTypeSerializer, Func`2 getODataPayloadSerializer, Func`1 getODataSerializerContext)
   at Microsoft.AspNet.OData.Formatter.ODataOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
--- End of stack trace from previous location where exception was thrown ---

**Comment by xuzhg** [comment]
@xiaotupansy I tested it using our https://github.com/OData/WebApi/tree/master/samples/AspNetCore3xODataSample.Web sample. 

It works if you run/send:

`~/odata/Customers?$expand=Orders`

`~/odata/Customers(1)?$expand=Orders`
You can get
```json
{
    "@odata.context": "http://localhost:5000/odata/$metadata#Customers(Orders())/$entity",
    "Id": 1,
    "Name": "Jonier",
    "HomeAddress": {
        "City": "Redmond",
        "Street": "156 AVE NE"
    },
    "Orders": [
        {
            "Id": 2,
            "Title": "abc0"
        },
        {
            "Id": 3,
            "Title": "abc1"
        }
    ]
}
```

**Comment by xiaotupansy** [comment]
![image](https://user-images.githubusercontent.com/10205937/71585572-01755200-2b52-11ea-8073-b5db556b9771.png)

**Comment by xiaotupansy** [comment]
![image](https://user-images.githubusercontent.com/10205937/71585596-210c7a80-2b52-11ea-80f6-5261b550afa4.png)

**Comment by xiaotupansy** [comment]
Things work when I create a new project.
But in my own one, after debuging, I find that ModelID is null for expand item.
And the ModelID checking raises the exception.

**Comment by bdebaere** [comment]
@xiaotupansy Do you still have this issue? Can you add a repro project please if you do so I can investigate?

**Comment by xiaotupansy** [comment]
@bdebaere Yes, I do have this issue. And I found that many people here  faced exactly the same problem like me. I've tried to make a demo project but I find it will not throw any exception. I've uploaded some pictures when I debugged last year. That's all I can give.

**Comment by bdebaere** [comment]
@xiaotupansy If your demo project does not throw an exception, and your main project does throw an exception, I would compare the two projects to look for differences between them. In the worst case scenario, you will be able to provide a repro. In the best case scenario you will have solved the problem.

Another possibility is to take your main project, and strip it down until the exception no longer appears. Then you will know what is causing it.

**Comment by xiaotupansy** [comment]
@bdebaere Sorry but I cannot show code of my main project. I found this because I upgrade my project to .net core 3.1. Everything works in .net core 2.2.
I solved this problem by not using expand any more. I add some additional field in my model and get information from here. Because I also need to update data after getting data from odata. You can see my problem here: https://github.com/OData/WebApi/issues/1897

**Comment by KenitoInc** [comment]
Closing this. Feel free to open a new issue.
