### ISSUE TITLE
Expand returning duplicate data

### ISSUE THREAD

**Issue by benitazz** [OData/WebApi#2006]
The expand returns the duplicate data on the instance and untypedInstance.

### Assemblies affected

*Which assemblies and versions are known to be affected  = AspNetCore.OData .Net lib 7.3.0 , Asp.netCore 3.1

### Reproduce steps

    public IActionResult GetAll(ODataQueryOptions<LrsAttrTypeResource> options)
        {
            try
            {
                var query = this._repository.GetAll().AsQueryable();
                string[] requestedExpands = ExpandExtension.GetMembersToExpandNames(options);

                var LrsAttrTypeResources = query.ProjectTo<LrsAttrTypeResource>(
                    this._mapper.ConfigurationProvider, null, requestedExpands);

                return Ok(LrsAttrTypeResources.AsQueryable());
            }
            catch (Exception ex)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, ex);
            }
        }

### Expected result
http://localhost:5000/api/Lrs/LrsAttrType?$expand=LrsAttrs

Expected the main object with the expanded object only, like the following:
 {
"attrTypeId": 5,
"attrType": "Entity",
"lrsAttrs": []
}

### Actual result

{
"instance": {
"attrTypeId": 5,
"attrType": "Entity",
"lrsAttrs": []
},
"container": {},
"modelID": "aed5e410-a8aa-4ae0-b40c-5b0b59547f11",
"untypedInstance": {
"attrTypeId": 5,
"attrType": "Entity",
"lrsAttrs": []
},
"instanceType": null,
"useInstanceForProperties": true
}

### Additional detail
I would like to remove duplicate data and only return the instance object with the expanded object . I dont want to see the  untypedInstance, container, instanceType...

**Comment by KanishManuja-MS** [comment]
@xuzhg can you investigate if they are returning something unexpected or is this a breaking change between 7.2.2 and 7.3.0?

**Comment by xuzhg** [comment]
@benitazz 
It seems the actual payload includes the internal data. What's the code in your "ExpandExtension.GetMembersToExpandNames(options);" ? It seems that's your own codes? 

Did you try using the [EnableQuery] directly? or call ApplyTo() on options？

**Comment by benitazz** [comment]
@xuzhg the "ExpandExtension.GetMembersToExpandNames(options);" method only returns an array of  property names to expand, here is the full code:

 public static class ExpandExtension
    {
        public static string[] GetMembersToExpandNames(ODataQueryOptions options)
        {
            return GetExpandPropertyPaths(GetExpandItems(options?.SelectExpand?.SelectExpandClause)).ToArray();
        }

        private static IEnumerable<string> GetExpandPropertyPaths(IEnumerable<ExpandedNavigationSelectItem> items, string prefix = "")
        {
            foreach (var item in items)
            {
                foreach (var res in GetExpandPropertyPaths(item, prefix))
                {
                    yield return res;
                }
            }
        }

        private static IEnumerable<string> GetExpandPropertyPaths(ExpandedNavigationSelectItem item, string prefix = "")
        {
            var curPropName = item.NavigationSource.Name;
            var nestedExpand = GetExpandItems(item.SelectAndExpand).ToArray();
            if (nestedExpand.Count() > 0)
            {
                foreach (var res in GetExpandPropertyPaths(nestedExpand, $"{prefix}{curPropName}."))
                {
                    yield return res;
                }
            }
            else
            {
                yield return $"{prefix}{curPropName}";
            }
        }

        private static IEnumerable<ExpandedNavigationSelectItem> GetExpandItems(SelectExpandClause sec)
        {
            if (sec != null)
            {
                var res = sec?.SelectedItems?.OfType<ExpandedNavigationSelectItem>();
                if (res != null)
                {
                    return res;
                }
            }
            return new ExpandedNavigationSelectItem[0];
        }
    }


OdataEnableQuery is the attribute I have implemented which set the page size, I did not want to repeat the page size wherever I use the EnableQuery, here is the code:

   public class OdataEnableQueryAttribute : EnableQueryAttribute
    {
        public OdataEnableQueryAttribute()
        {
             base.PageSize = 100;
        }
    }

Lastly, here is the metadata of  AutoMapper.QueryableExtensions:
  //
        // Summary:
        //     Projects the source type to the destination type given the mapping configuration
        //
        // Parameters:
        //   source:
        //     Queryable source
        //
        //   configuration:
        //     Mapper configuration
        //
        //   parameters:
        //     Optional parameter object for parameterized mapping expressions
        //
        //   membersToExpand:
        //     Explicit members to expand
        //
        // Type parameters:
        //   TDestination:
        //     Destination type to map to
        //
        // Returns:
        //     Queryable result, use queryable extension methods to project and execute result
        public static IQueryable<TDestination> ProjectTo<TDestination>(this IQueryable source, IConfigurationProvider configuration, IDictionary<string, object> parameters, params string[] membersToExpand);

Can you please give me an example of ApplyTo?

Here is my reference: https://stackoverflow.com/questions/42394599/how-to-expand-sub-levels-of-childs-with-automapper-and-odata

**Comment by benitazz** [comment]
@KanishManuja-MS unfortunately I cannot downgrade from 7.3.0 to 7.2.2, I get the following error when I try to run my project on 7.2.2:

 ---> (Inner Exception #2) System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: Microsoft.AspNetCore.Mvc.Infrastructure.IActionSelector Lifetime: Singleton ImplementationType: Microsoft.AspNet.OData.Routing.ODataActionSelector': Could not load type 'Microsoft.AspNetCore.Mvc.Internal.ActionConstraintCache' from assembly 'Microsoft.AspNetCore.Mvc.Core, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
 ---> System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Mvc.Internal.ActionConstraintCache' from assembly 'Microsoft.AspNetCore.Mvc.Core, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeConstructorInfo.get_Signature()
   at System.Reflection.RuntimeConstructorInfo.GetParametersNoCopy()
   at System.Reflection.RuntimeConstructorInfo.GetParameters()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, ServiceProviderOptions options)<---

**Comment by benitazz** [comment]
@xuzhg 

I have changed my code as follows:

  [EnableQuery]
        [HttpGet]
        [ProducesResponseType(typeof(LrsAttrTypeResource), StatusCodes.Status200OK)]
        public IEnumerable<LrsAttrType> GetAll()
        {
               return this._repository.GetAll().AsQueryable();
        }


My Repository:
public virtual IQueryable<TEntity> GetAll()
        {
            return this.dbContext.Set<TEntity>();
        }

Results: Still contain duplicates
 {
    "instance": {
      "attrTypeId": 1,
      "attrType": "Text description",
      "lrsAttrs": []
    },
    "container": {},
    "modelID": "9e249f29-05f0-4925-9fae-9a910e8d1d1f",
    "untypedInstance": {
      "attrTypeId": 1,
      "attrType": "Text description",
      "lrsAttrs": []
    },
    "instanceType": null,
    "useInstanceForProperties": true

**Comment by benitazz** [comment]
@KanishManuja-MS  @xuzhg 

The explicit expansion works fine:

 [OdataEnableQuery]
        [HttpGet]
        [ProducesResponseType(typeof(LrsAttrTypeResource), StatusCodes.Status200OK)]
        public IActionResult GetAll(ODataQueryOptions<LrsAttrTypeResource> options)
        {
            try
            {
                var query = this._repository.GetAll();
                string[] requestedExpands = ExpandExtension.GetMembersToExpandNames(options);

                // var LrsAttrTypeResources = query.ProjectTo<LrsAttrTypeResource>(
                //     this._mapper.ConfigurationProvider, null, requestedExpands);

                var LrsAttrTypeResources = query.ProjectTo<LrsAttrTypeResource>(
                   this._mapper.ConfigurationProvider, d => d.LrsAttrs); //Explicit expansion.

                return Ok(LrsAttrTypeResources);
            }
            catch (Exception ex)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, ex);
            }
        }

Results:

 {
    "attrTypeId": 6,
    "attrType": "Boolean Value",
    "lrsAttrs": [
      {
        "attrId": 32,
        "attrName": "Partially Mapped",
        "attrTypeId": 6,
        "audUserId": null,
        "audDate": null,
        "classId": null,
        "entDisplayAttrId": null,
        "attrRefCol": "REF_ID1",
        "rangeId": null,
        "lrsAttrType": null,
        "lrsAttrValues": [],
        "lrsLaneSegAttrs": [],
        "lrsLinkAttrs": [],
        "lrsLinkVerAttrs": [],
        "lrsLinkVerSegAttrs": []
      }
    ]
  }

**Comment by xiaotupansy** [comment]
I also face an expand error in [https://github.com/OData/WebApi/issues/1994](url).
So I guess there is a breaking change between 7.2.2 and 7.3.0.
