### ISSUE TITLE
3.1 nightly: Serializer is disposing input stream.

### ISSUE THREAD

**Issue by NetTecture** [OData/WebApi#2052]
For reasins related to Delta not supporting odata.bind syntax, I need to rewind the input stream and deserialize some properties in a patch delta manually.

To enable this, I do this:

* In startup, I enable rewind:

            app.Use(next => ctx => {
                ctx.Request.EnableBuffering(50 * 1024 * 1024); // In memory up to 50mb
                return next(ctx);
            });

* In the patch, I rewind and deserialize manually:

            Request.Body.Position = 0;
            var bodyStr = await new StreamReader(Request.Body).ReadToEndAsync();
            JObject rawDelta = JObject.Parse(bodyStr);

In nightly, this does not work. I get (in the line with Position = 0:

System.ObjectDisposedException: 'Cannot access a disposed object.
Object name: 'FileBufferingReadStream'.'

This object should at this point not be disposed in order to facilitate rewindind.

Full stack trace:

System.ObjectDisposedException
  HResult=0x80131622
  Message=Cannot access a disposed object.
Object name: 'FileBufferingReadStream'.
  Source=Microsoft.AspNetCore.WebUtilities
  StackTrace:
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.ThrowIfDisposed()
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.set_Position(Int64 value)
   at Api.Odata.Web.Controllers.EquipmentController.<Patch>d__3.MoveNext() in C:\Work\OBB\Source.Backend\Api.Odata.Web\Controllers\EquipmentController.cs:line 133

Note: As a solution I would also accept a syntax that allows me to extract the bindings (via a separate syntax). The object can easily keep them in the dictionary, have a get method and allow retrieving them via code. I actually think as a workaround I should be able to subclass Delta - I am willing to submit this as PR.

Note that I am not looking for something fancy - a dictionary with strings are good enough. My current code actually does this:

            Request.Body.Position = 0;
            var bodyStr = await new StreamReader(Request.Body).ReadToEndAsync();
            JObject rawDelta = JObject.Parse(bodyStr);

           if (rawDelta.TryGetValue("Room@odata.bind", out var keyToken)) {

So, my DeltaWithBindings would have TryGetBinding(propertyname) return string.

**Comment by xuzhg** [comment]
@NetTecture  1. What's the 3.1 nightly?  2. Could you please create a sample repo for me to investigate?

**Comment by NetTecture** [comment]
@xuzhg 
1: yes ;)
2: give me a ocuple of days - under water now. I should have something by end of the week.
