### ISSUE TITLE
DateTimeOffset property used as ConcurrencyCheck

### ISSUE THREAD

**Issue by sergiomoreno** [OData/WebApi#2057]
When a DateTimeOffset property is used to manage concurrency using the attribute ConcurrencyCheck it fails calling the method IfMatch of ODataQueryOptions.

### Assemblies affected

Microsoft.AspNetCore.OData 7.3.0

### Reproduce steps

1- Set a DateTimeOffset property as concurrency field:

```
        [Required, ConcurrencyCheck]
        public DateTimeOffset ModificationDate { get; set; }
```

2- When the Delete (or any other) function is called in this way it fails:

 ```
public async Task<IActionResult> Delete([FromODataUri(Name = "key")] string AreaCode, ODataQueryOptions<Area> options)
	    {
	        try
	        {
	            Area existing;
	            var query = this.Context.Areas.Where(x => x.AreaCode == AreaCode);
	            if (options.IfMatch != null)
	            {
	                existing = options.IfMatch.ApplyTo(query).FirstOrDefault(); <---- It throws an Exception
	                if (null == existing)

```

### Actual result
This exception is thrown:

```
Object must implement IConvertible.
  at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Microsoft.AspNet.OData.Extensions.HttpRequestExtensions.GetETag(HttpRequest request, EntityTagHeaderValue entityTagHeaderValue) in C:\Trabajo\WebApiOData\src\Microsoft.AspNetCore.OData\Extensions\HttpRequestExtensions.cs:line 226
   at Microsoft.AspNet.OData.Extensions.HttpRequestExtensions.GetETag[TEntity](HttpRequest request, EntityTagHeaderValue entityTagHeaderValue) in C:\Trabajo\WebApiOData\src\Microsoft.AspNetCore.OData\Extensions\HttpRequestExtensions.cs:line 251
   at Microsoft.AspNet.OData.Adapters.WebApiRequestMessage.GetETag[TEntity](EntityTagHeaderValue etagHeaderValue) in C:\Trabajo\WebApiOData\src\Microsoft.AspNetCore.OData\Adapters\WebApiRequestMessage.cs:line 178
   at Microsoft.AspNet.OData.Query.ODataQueryOptions`1.GetETag(EntityTagHeaderValue etagHeaderValue) in C:\Trabajo\WebApiOData\src\Microsoft.AspNet.OData.Shared\Query\ODataQueryOptionsOfTEntity.cs:line 46
   at Microsoft.AspNet.OData.Query.ODataQueryOptions.get_IfMatch() in C:\Trabajo\WebApiOData\src\Microsoft.AspNet.OData.Shared\Query\ODataQueryOptions.cs:line 203
   at Microsoft.AspNet.OData.Query.ODataQueryOptions`1.get_IfMatch() in C:\Trabajo\WebApiOData\src\Microsoft.AspNet.OData.Shared\Query\ODataQueryOptionsOfTEntity.cs:line 25
   at AdhProject02.WebAPI.AreasController.<Delete>d__12.MoveNext() 

```

**Comment by xuzhg** [comment]
@sergiomoreno I tested your scenario, it works fine at my side. 

See my test codes at https://github.com/xuzhg/WebApi/tree/issue2057

If you send request like:

![image](https://user-images.githubusercontent.com/9426627/74868393-08774000-530b-11ea-8691-eeb91d7739f4.png)

you can get the following debug information:

![image](https://user-images.githubusercontent.com/9426627/74868521-3f4d5600-530b-11ea-94d9-cc76d94753d7.png)

**Comment by sergiomoreno** [comment]
I've found the problem. It was my fault. I put the attribute Required in the entity:

```
  [Required, ConcurrencyCheck]
        public DateTimeOffset ModificationDate { get; set; }
```

And optional in the fluent API:

`  builder.EntityType<Area>().Property(p => p.ModificationDate).IsOptional(); `

So it tried to convert from Nullable DateTimeOffset to DateTimeOffset.

Sorry for the inconvenience.
