### ISSUE TITLE
Server-side paging $skiptoken fails

### ISSUE THREAD

**Issue by Ali-ModernBeauty** [OData/WebApi#2078]
Server-side paging $skiptoken fails.

### Assemblies affected

Microsoft.AspNetCore.OData (7.3.0)
|- Newtonsoft.json (12.0.2)
|- Microsoft.OData.Core (7.6.1)
   |- Microsoft.OData.Edm (7.6.1)
   |- Microsoft.Spatial (7.6.1)

### Reproduce steps

1- Add `PageSize`  in enable `[EnableQuery]`

```C#
       //Items Controller
       [HttpGet]
       [ODataRoute("Items")]
       [EnableQuery(PageSize = 20)]
        public IQueryable<Item> GetItems()
            => _db.Items;
```

2- Query endpoint
`GET /odata/Items`

**returns**
```json
{
    "@odata.context": "https://localhost:5001/odata/$metadata#Items",
    "value": [
        {
            "Id": "1PA111DIRECT",
            "Description": "Description",
        },
        {
            "Id": "1PA222COMMENT",
            "Description": "Description",
        }
    ],
    "@odata.nextLink": "https://localhost:5001/odata/Items?$skiptoken=Id-'1PA222COMMENT'"
}
```

3- GET `@odata.nextLink`

**returns**
```shell
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: The LINQ expression 'DbSet<Item>
    .OrderBy(i => i.Id)
    .Where(i => string.Compare(
        strA: i.Id, 
        strB: __TypedProperty_0, 
        comparisonType: Ordinal) > 0)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|8_0(ShapedQueryExpression translated, <>c__DisplayClass8_0& )
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
```

**Comment by SiberaIndustries** [comment]
Note this part of your exception:

```cs
string.Compare(
        strA: i.Id, 
        strB: __TypedProperty_0, 
        comparisonType: Ordinal)
```

I bet you are using Entity Framework Core 3+ as an ORM framework? Since EF Core 3.0, the framework disallows client-side evaluation. This describes the same issue: https://github.com/OData/WebApi/issues/2043

 I already made a fix, but it needs to be reviewed: https://github.com/OData/WebApi/pull/2053

**Comment by Ali-ModernBeauty** [comment]
Correct. I am using efcore 3.0. Great! Thank you for the fix. (ﾉ◕ヮ◕)ﾉ*:・ﾟ
I will wait until to test again once #2053 is released. I'm guessing I would know when this issue is closed?

**Comment by webbatastic** [comment]
Is this going to be fixed / merged? The issue still remains in version 7.41. Is there any other way to easily achieve paging with complex types as Id like Guid?

**Comment by cristinamanum** [comment]
Are there any updates for this issue?
