### ISSUE TITLE
AspNetCore.OData: Truncated JSON returned for $expand and contained entities

### ISSUE THREAD

**Issue by Stephan-Hoffmann** [OData/WebApi#2094]
Related to case #2040, expanding contained child entities results in a HTTP 200 response with a truncated JSON when the number of sub-child entities exceeds the set PageSize on [EnableQuery]. 

### Assemblies affected

This affects Microsoft.AspNetCore.OData 7.3.0, 7.4.0-beta

### Reproduce steps

The following controller method illustrates the issue.
```c#
[HttpGet]
[EnableQuery(PageSize = 1)]
public IQueryable<EntitySet> Get()
    => new EnumerableQuery<EntitySet>(new [] {
        new EntitySet {
            Id = "A",
            Children = new[] {
                new Child {
                    Id = "A-1",
                    Children = new[] {
                        new SubChild {Id = "A-1-1"},
                        new SubChild {Id = "A-1-2"}
                    }
                }
            }
        } 
   });
```
If accessed by this link https://localhost:44349/odata/entityset?$expand=children($expand=children)
 the truncated JSON is returned.
Attached is a sample AspNetCore 3.1 WebApi that illustrates the issue.
[ODataContainment.zip](https://github.com/OData/WebApi/files/4355132/ODataContainment.zip)

### Expected result

Either the child entities should have an @odata.next link, or it should contain all child elements. Either is acceptable.

### Actual result

A truncated JSON is returned with an HTTP 200 response!!
```json
{
  "@odata.context":"https://localhost:44349/odata/$metadata#EntitySet(Children(Children()))",
  "value":[
    {"Id":"A","Children":[
      {"Id":"A-1","Children":[
        {"Id":"A-1-1"}
```
### Additional detail

The exception occurs in generating the URL. It thinks to start at the `Children` level, ignoring the `EntitySet` completely. The URL it tries to generate before throwing the exception looks like this
https://localhost:44349/odata/children('A-1')/children

```exception
Microsoft.OData.UriParser.ODataUnrecognizedPathException: Resource not found for the segment 'Children'.
   at Microsoft.OData.UriParser.ODataPathParser.CreateDynamicPathSegment(ODataPathSegment previous, String identifier, String parenthesisExpression)
   at Microsoft.OData.UriParser.ODataPathParser.CreateFirstSegment(String segmentText)
   at Microsoft.OData.UriParser.ODataPathParser.ParsePath(ICollection`1 segments)
   at Microsoft.OData.UriParser.ODataPathFactory.BindPath(ICollection`1 segments, ODataUriParserConfiguration configuration)
   at Microsoft.OData.UriParser.ODataUriParser.ParsePathImplementation()
   at Microsoft.OData.UriParser.ODataUriParser.Initialize()
   at Microsoft.OData.UriParser.ODataUriParser.ParsePath()
   at Microsoft.OData.UriParser.ODataUriParser.ParseUri()
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSetSerializer.GenerateQueryFromExpandedItem(ODataSerializerContext writeContext, Uri navigationLink)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSetSerializer.GetNestedNextPageLink(ODataSerializerContext writeContext, Int32 pageSize, Object obj)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSetSerializer.<>c__DisplayClass6_3.<GetNextLinkGenerator>b__3(Object obj)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteResourceSet(IEnumerable enumerable, IEdmTypeReference resourceSetType, ODataWriter writer, ODataSerializerContext writeContext)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteObjectInline(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteComplexAndExpandedNavigationProperty(IEdmProperty edmProperty, SelectItem selectItem, ResourceContext resourceContext, ODataWriter writer)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteExpandedNavigationProperties(SelectExpandNode selectExpandNode, ResourceContext resourceContext, ODataWriter writer)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteResource(Object graph, ODataWriter writer, ODataSerializerContext writeContext, IEdmTypeReference expectedType)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteObjectInline(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteResourceSet(IEnumerable enumerable, IEdmTypeReference resourceSetType, ODataWriter writer, ODataSerializerContext writeContext)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteObjectInline(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteComplexAndExpandedNavigationProperty(IEdmProperty edmProperty, SelectItem selectItem, ResourceContext resourceContext, ODataWriter writer)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteExpandedNavigationProperties(SelectExpandNode selectExpandNode, ResourceContext resourceContext, ODataWriter writer)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteResource(Object graph, ODataWriter writer, ODataSerializerContext writeContext, IEdmTypeReference expectedType)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteObjectInline(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteResourceSet(IEnumerable enumerable, IEdmTypeReference resourceSetType, ODataWriter writer, ODataSerializerContext writeContext)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteObjectInline(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteObject(Object graph, Type type, ODataMessageWriter messageWriter, ODataSerializerContext writeContext)
   at Microsoft.AspNet.OData.Formatter.ODataOutputFormatterHelper.WriteToStream(Type type, Object value, IEdmModel model, ODataVersion version, Uri baseAddress, MediaTypeHeaderValue contentType, IWebApiUrlHelper internaUrlHelper, IWebApiRequestMessage internalRequest, IWebApiHeaders internalRequestHeaders, Func`2 getODataMessageWrapper, Func`2 getEdmTypeSerializer, Func`2 getODataPayloadSerializer, Func`1 getODataSerializerContext)
   at Microsoft.AspNet.OData.Formatter.ODataOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)```

**Comment by KenitoInc** [comment]
This PR #2287 should fix this issue

**Comment by matteo-mosca** [comment]
2025 and I am having the exact same issue using Odata 8 on net core 8.

With one level expand I get a complete response.

If I use a two level expand, like $expand=Foo($expand=Bar) then I get truncated Json after the first square bracket.
