### ISSUE TITLE
Expand does not work with an instance containing more than 1 item to expand

### ISSUE THREAD

**Issue by brice-fromentin** [OData/WebApi#2099]
I have a application that loads an instance of a object with its children using expand and the selection via key.

I am running 7.4.0 beta on .NET 5.0 preview

When there is is one child, ex : 

Request URL: http://localhost:7121/api/odata/Utilisateurs(6ab447ba-bfb8-4c4f-a60b-66fdb3ea9bb2)?$expand=Service

Controller :

        [EnableQuery]
        [ODataRoute("utilisateurs")]
        public IQueryable<Utilisateur> Get()
        {
            return dbContext.Utilisateur;
        }

        [EnableQuery]
        [ODataRoute("utilisateurs({key})")]
        public SingleResult<Utilisateur> Get([FromODataUri] Guid key)
        {
            var result = dbContext.Utilisateur.Where(p => p.Id == key);
            return SingleResult.Create(result);
        }

Response

@odata.context: "http://localhost:7121/api/odata/$metadata#Utilisateurs(Service())/$entity",…}
@odata.context: "http://localhost:7121/api/odata/$metadata#Utilisateurs(Service())/$entity"
Id: "6ab447ba-bfb8-4c4f-a60b-66fdb3ea9bb2"
DateCreation: "2020-03-24T09:49:30+01:00"
UtilisateurCreation: null
Modification: null
UtilisateurModification: null
Login: "admin"
MotDePasse: "xxx="
EstBloque: false
DoitReinitialiser: false
DateDebutMotDePasse: null
DureeMotDePasse: null
Prenom: "Brice"
Prenom2: "Cyrille"
Prenom3: null
Nom: "FROMENTIN"
Mel: "brice.fromentin@xxx.com"
Telephone: null
Fax: null
DateDebutValidite: null
DureeValidite: null
IdService: "436d6dc0-18c3-4ac1-bb3f-4d26f3c0bb31"
Service: {Id: "436d6dc0-18c3-4ac1-bb3f-4d26f3c0bb31", DateCreation: "2020-03-24T11:43:26.793+01:00",…}
Id: "436d6dc0-18c3-4ac1-bb3f-4d26f3c0bb31"
DateCreation: "2020-03-24T11:43:26.793+01:00"
UtilisateurCreation: null
Modification: null
UtilisateurModification: null
Nom: "JOHN"

----------------------------------------------------------------------------------------------Case 2

Request URL: http://localhost:7121/api/odata/Collectivites(975252f9-fce6-443d-91f9-77c697e71f05)?$expand=CollectiviteTypeOperations

Controller ::

        [EnableQuery]
        [ODataRoute("collectivites")]
        public IQueryable<Collectivite> Get()
        {
            return dbContext.Collectivite;
        }

        [EnableQuery]
        [ODataRoute("collectivites({key})")]
        public SingleResult<Collectivite> Get([FromODataUri] Guid key)
        {
            var result = dbContext.Collectivite.Where(p => p.Id == key);
            return SingleResult.Create(result);
        }

Response ::

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityEqualityRewritingExpressionVisitor.CreatePropertyAccessExpression(Expression target, IProperty property)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityEqualityRewritingExpressionVisitor.RewriteNullEquality(Boolean equality, IEntityType entityType, Expression nonNullExpression, INavigation lastNavigation)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityEqualityRewritingExpressionVisitor.RewriteNullEquality(Boolean equality, IEntityType entityType, Expression nonNullExpression, INavigation lastNavigation)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityEqualityRewritingExpressionVisitor.RewriteEquality(Boolean equality, Expression left, Expression right)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityEqualityRewritingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityEqualityRewritingExpressionVisitor.VisitConditional(ConditionalExpression conditionalExpression)
   at System.Linq.Expressions.ConditionalExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityEqualityRewritingExpressionVisitor.<VisitMemberInit>g__VisitMemberBindings|9_0(ReadOnlyCollection`1 bindings)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityEqualityRewritingExpressionVisitor.VisitMemberInit(MemberInitExpression memberInitExpression)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityEqualityRewritingExpressionVisitor.<VisitMemberInit>g__VisitMemberBindings|9_0(ReadOnlyCollection`1 bindings)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityEqualityRewritingExpressionVisitor.VisitMemberInit(MemberInitExpression memberInitExpression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityEqualityRewritingExpressionVisitor.RewriteAndVisitLambda(LambdaExpression lambda, EntityReferenceExpression source)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityEqualityRewritingExpressionVisitor.VisitSelectMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityEqualityRewritingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityEqualityRewritingExpressionVisitor.Rewrite(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.System.Collections.IEnumerable.GetEnumerator()
   at Microsoft.AspNet.OData.EnableQueryAttribute.SingleOrDefault(IQueryable queryable, IWebApiActionDescriptor actionDescriptor)
   at Microsoft.AspNet.OData.EnableQueryAttribute.ExecuteQuery(Object responseValue, IQueryable singleResultCollection, IWebApiActionDescriptor actionDescriptor, Func`2 modelFunction, IWebApiRequestMessage request, Func`2 createQueryOptionFunction)
   at Microsoft.AspNet.OData.EnableQueryAttribute.OnActionExecuted(Object responseValue, IQueryable singleResultCollection, IWebApiActionDescriptor actionDescriptor, IWebApiRequestMessage request, Func`2 modelFunction, Func`2 createQueryOptionFunction, Action`1 createResponseAction, Action`3 createErrorAction)
   at Microsoft.AspNet.OData.EnableQueryAttribute.OnActionExecuted(ActionExecutedContext actionExecutedContext)
   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Accept: application/json, application/xml, application/text
Accept-Encoding: gzip, deflate, br
Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7
Connection: keep-alive
Host: localhost:7121
Referer: http://localhost:7120/administration/collectivites
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
prefer: return=representation
Sec-Fetch-Dest: empty
Origin: http://localhost:7120
Sec-Fetch-Site: same-site
Sec-Fetch-Mode: cors

**Comment by iamkinetic** [comment]
Bug also mentionned in #2080

**Comment by KenitoInc** [comment]
@brice-fromentin 
We are investigation this issue.
Also confirm that the same issue does not occur in v7.3.0 with the same version of EF Core.
What version of EF core are you using? Can you try with EF Core 2.2

**Comment by xuzhg** [comment]
@brice-fromentin Besides, would you please share your sample for us to dig more?

**Comment by brice-fromentin** [comment]
Here is the truncated part of my project , within DATA.7z contains the detabase.

Here are 4 requests :

http://localhost:7121/api/odata/utilisateurs
http://localhost:7121/api/odata/utilisateurs?$expand=service

http://localhost:7121/api/odata/collectivites
http://localhost:7121/api/odata/collectivites?$expand=CollectiviteTypeOperations  <-- Failed

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : Sam Xu<mailto:notifications@github.com>
Envoyé le :mardi 31 mars 2020 23:32
À : OData/WebApi<mailto:WebApi@noreply.github.com>
Cc : brice-fromentin<mailto:brice.fromentin@outlook.com>; Mention<mailto:mention@noreply.github.com>
Objet :Re: [OData/WebApi] Expand does not work with an instance containing more than 1 item to expand (#2099)


@brice-fromentin<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbrice-fromentin&data=02%7C01%7C%7Ca5c19f9572c542a6fd9408d7d5bb108f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637212871715594592&sdata=Z8lW8AX9JYa2xYfb2aU0s09LbLqN2RRjke5vH3A6K20%3D&reserved=0> Besides, would you please share your sample for us to dig more?

**Comment by xuzhg** [comment]
@brice-fromentin 

A nightly with the quick fix at Microsoft.AspNet.OData.7.4.0-Nightly202004012334.nupkg, can you try it and let me know the result?

**Comment by xuzhg** [comment]
This got fixed. If not, please reopen it. Thanks.
