### ISSUE TITLE
Function 'case' is not supported by ODataQueryOptionParser

### ISSUE THREAD

**Issue by GennadyGS** [OData/WebApi#2101]
Function [case ](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#_Toc31361023) is not supported by ODataQueryOptionParser

### Assemblies affected

Microsoft.AspNet.OData 7.3.0
(Microsoft.AspNet.OData 7.4.0-beta as well)

### Reproduce steps

```
public class OpenEntity
{
	[Key]
	public int Id { get; set; }

	public IDictionary<string, object> Properties { get; set; }
}

public IEdmModel GetEdmModel()
{
	var builder = new ODataConventionModelBuilder();
	builder.EntitySet<OpenEntity>(nameof(OpenEntity)).EntityType.Select().Filter().Page().OrderBy().Count().Expand();
	return builder.GetEdmModel();
}

void Main()
{
	var oDataQueryContext = new ODataQueryContext(GetEdmModel(), typeof(OpenEntity), null);
	var apply = "compute(case(X gt 0:1,X lt 0:-1) as SignumX)";
	var queryOptionParser = new ODataQueryOptionParser(
		oDataQueryContext.Model,
		oDataQueryContext.ElementType,
		oDataQueryContext.NavigationSource,
		new Dictionary<string, string> {
			{ "$apply", apply },
		});
	var applyOption = new ApplyQueryOption(apply, oDataQueryContext, queryOptionParser);
	Console.WriteLine(applyOption.ApplyClause);
}

```
### Expected result

Code should be run successfully and proper AST should be built.

### Actual result
Exception is thrown:

> Microsoft.OData.ODataException: ')' or ',' expected at position 28 in 'compute(case(X gt 0:1,X lt 0:-1,true:0) as SignumX)'.
>    at Microsoft.OData.UriParser.FunctionCallParser.ParseArgumentListOrEntityKeyList(Action restoreAction)
>    at Microsoft.OData.UriParser.FunctionCallParser.TryParseIdentifierAsFunction(QueryToken parent, QueryToken& result)
>    at Microsoft.OData.UriParser.IdentifierTokenizer.ParseIdentifier(QueryToken parent)
>    at Microsoft.OData.UriParser.UriQueryExpressionParser.ParsePrimaryStart()
>    at Microsoft.OData.UriParser.UriQueryExpressionParser.ParsePrimary()
>    at Microsoft.OData.UriParser.UriQueryExpressionParser.ParseUnary()
>    at Microsoft.OData.UriParser.UriQueryExpressionParser.ParseMultiplicative()
>    at Microsoft.OData.UriParser.UriQueryExpressionParser.ParseAdditive()
>    at Microsoft.OData.UriParser.UriQueryExpressionParser.ParseComparison()
>    at Microsoft.OData.UriParser.UriQueryExpressionParser.ParseLogicalAnd()
>    at Microsoft.OData.UriParser.UriQueryExpressionParser.ParseLogicalOr()
>    at Microsoft.OData.UriParser.UriQueryExpressionParser.ParseExpression()
>    at Microsoft.OData.UriParser.UriQueryExpressionParser.ParseComputeExpression()
>    at Microsoft.OData.UriParser.UriQueryExpressionParser.ParseCompute()
>    at Microsoft.OData.UriParser.UriQueryExpressionParser.ParseApply(String apply)
>    at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseApplyImplementation(String apply, ODataUriParserConfiguration configuration, ODataPathInfo odataPathInfo)
>    at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseApply()
>    at Microsoft.AspNet.OData.Query.ApplyQueryOption.get_ApplyClause()
>    at UserQuery.Main() 

### Additional detail
If I try to change apply clause to 
`var apply = "compute(case(X gt 0:1,X lt 0:0) as SignumX)";`
in order to exclude issues with minus sign, I get another error:

> Microsoft.OData.ODataException: An unknown function with name 'case' was found. This may also be a function import or a key lookup on a navigation property, which is not allowed.
>    at Microsoft.OData.UriParser.FunctionCallBinder.GetUriFunctionSignatures(String functionCallToken, Boolean enableCaseInsensitive)
>    at Microsoft.OData.UriParser.FunctionCallBinder.BindAsUriFunction(FunctionCallToken functionCallToken, List`1 argumentNodes)
>    at Microsoft.OData.UriParser.FunctionCallBinder.BindFunctionCall(FunctionCallToken functionCallToken)
>    at Microsoft.OData.UriParser.MetadataBinder.BindFunctionCall(FunctionCallToken functionCallToken)
>    at Microsoft.OData.UriParser.MetadataBinder.Bind(QueryToken token)
>    at Microsoft.OData.UriParser.Aggregation.ApplyBinder.BindComputeToken(ComputeToken token)
>    at Microsoft.OData.UriParser.Aggregation.ApplyBinder.BindApply(IEnumerable`1 tokens)
>    at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseApplyImplementation(String apply, ODataUriParserConfiguration configuration, ODataPathInfo odataPathInfo)
>    at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseApply()
>    at Microsoft.AspNet.OData.Query.ApplyQueryOption.get_ApplyClause()
>

**Comment by GennadyGS** [comment]
Sorry, probably it is related to other library:
https://github.com/OData/odata.net/issues/1673
