### ISSUE TITLE
Lambda Expression filtering with projected DTOs are not working

### ISSUE THREAD

**Issue by AbraamNader** [OData/WebApi#2109]
Lambda Expression filtering with projected DTOs are not working even with client evaluation (as suggested by the error message), 
doing something like this:
`api/EntityEndpoint?$filter=SubCollection/any(e:e/property eq 'test')`
no longer works.

### Assemblies affected
.NET Core 3.1:
Microsoft.AspNetCore.OData 7.4.0-beta
Microsoft.EntityFrameworkCore 3.1.2
Automapper 9.0

### Reproduce steps

1. Clone repo at https://github.com/AbraamNader/NETCoreSandbox
2. Build, Run
3. Browse Any of these urls:
`
/api/data/ProjectTo?$filter=translations/any(t:t/name eq 'test')
`
`
/api/data/ClientEvaluated?$filter=translations/any(t:t/name eq 'test')
`
`
/api/data/ApplyTo?$filter=translations/any(t:t/name eq 'test')
`

### Expected result

It should work like when accessing the entity directly without a DTO:
`
/api/data?$filter=translations/any(t:t/name eq 'test')
`

### Actual result

Error:
```
System.InvalidOperationException: The LINQ expression 'DbSet<Data>
    .Where(d => DbSet<Translation>
        .Where(t => EF.Property<Nullable<long>>(d, "Id") != null && EF.Property<Nullable<long>>(d, "Id") == EF.Property<Nullable<long>>(t, "DataId"))
        .Select(t => new TranslationDTO{ 
            DataId = t.DataId, 
            Id = t.Id, 
            LanguageId = t.LanguageId, 
            Name = t.Name 
        }
        ) == null ? null : (Nullable<bool>)DbSet<Translation>
        .Where(t0 => EF.Property<Nullable<long>>(d, "Id") != null && EF.Property<Nullable<long>>(d, "Id") == EF.Property<Nullable<long>>(t0, "DataId"))
        .Any(t0 => t0.Name == __TypedProperty_0) == (Nullable<bool>)True)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|8_0(ShapedQueryExpression translated, <>c__DisplayClass8_0& )
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Infrastructure.AsyncEnumerableReader.ReadInternal[T](IAsyncEnumerable`1 value)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsyncEnumerable(ActionContext context, ObjectResult result, IAsyncEnumerable`1 asyncEnumerable)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|21_0(ResourceInvoker invoker, IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Additional detail

This used to work with .NET Framework 4.7 and Entity Framework 6.
The sample mentioned above is a small demo of a large project we are porting to .NET Core 3.1 from .NET Framework 4.7, and this is one of two remaining blocking issues, the rest of OData seems to be working fine.
Would appreciate any help regarding this issue.

**Comment by mikepizzo** [comment]
We are aware of some limitations in EFCore 3.x with client side evaluation.  Note that it is possible to use WebAPI OData 7.3 and .NET Core 3.x with the older versions of Entity Framework, if that would allow you to move to .NET Core 3.1.

**Comment by NetTecture** [comment]
Also note that older versions can be EntityFramework NON CORE. It now works on .NET Core.

**Comment by snappyfoo** [comment]
> We are aware of some limitations in EFCore 3.x with client side evaluation. Note that it is possible to use WebAPI OData 7.3 and .NET Core 3.x with the older versions of Entity Framework, if that would allow you to move to .NET Core 3.1.

The OP stated he has tried client evaluation - see the endpoint using AsEnumerable. Do you have any further comments? Is it the intention for these limitations/incompatibilities between EFCore 3.x and OData to be further investigated, solved, workarounds provided?
