### ISSUE TITLE
Enum Filter broken throwing Object must implement IConvertible

### ISSUE THREAD

**Issue by ewkonzo** [OData/WebApi#2180]
*Short summary (3-5 sentences) describing the issue.*

A query  ```someTable?$filter=enumField in ('enumValue1','enumValue2')``` on a working project with OData WebApi lib 7.4.0 breaks after updating to 7.4.1. all methods using enum in results in an exception ```InvalidCastException: Object must implement IConvertible.``` reverting to 7.4.0 fixes the issue.

### Assemblies affected

OData WebApi lib 7.4.1

### Reproduce steps

Create and configure an odata 7.4.1 project with Microsoft.EntityFrameworkCore having a class called someTable and an enum field called enumField. and add sample data.

Add a filter ```$filter=enumField in ('enumValue1','enumValue2')```  on the get request to the controller.

### Expected result

Json Results of `someTable` having 'enumValue1' and 'enumValue2'

### Actual result

```InvalidCastException: Object must implement IConvertible.```  Exception is thrown on a browser

### Additional detail

***Original stack trace***
```System.InvalidCastException: Object must implement IConvertible.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter`2.Sanitize[T](Object value)
   at Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter`2.<>c__DisplayClass3_0`2.<SanitizeConverter>b__0(Object v)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping.CreateParameter(DbCommand command, String name, Object value, Nullable`1 nullable)
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypeMappedRelationalParameter.AddDbParameter(DbCommand command, Object value)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalParameterBase.AddDbParameter(DbCommand command, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.CreateCommand(RelationalCommandParameterObject parameterObject, Guid commandId, DbCommandMethod commandMethod)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.AsyncEnumerableReader.ReadInternal[T](Object value)
   at Microsoft.AspNetCore.Mvc.Infrastructure.AsyncEnumerableReader.ReadInternal[T](Object value)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsyncEnumerable(ActionContext context, ObjectResult result, Object asyncEnumerable, Func`2 reader)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)```

**Comment by xuzhg** [comment]
@ewkonzo [here](https://docs.microsoft.com/en-us/odata/changelog/webapi-7x) is the 7.4.1 release note. It's weird that there's no related change to the filter. On possible is [this](https://github.com/OData/WebApi/pull/2053/files) change. Would you please share us a github repo for us to dig more?

**Comment by xuzhg** [comment]
@ewkonzo I have an investigation project at: https://github.com/xuzhg/WebApiSample/tree/master/IssuesOnWebApi/Issue2180

It works fine using 'In" operator on enum property, and it is using 7.4.1. Please take a look and let me know any problem?

**Comment by ewkonzo** [comment]
@xuzhg Thanks for taking your time... I was finally able to reproduce the issue in this repo
https://github.com/ewkonzo/OdataIssue2180

Apparently it only occurs when a real database is used.. please take a look

**Comment by xuzhg** [comment]
@ewkonzo I tried to run your sample, but i got the following error:

![image](https://user-images.githubusercontent.com/9426627/83912923-8842e200-a723-11ea-8de4-ef36c08086f6.png)

By the way, i also tested in my sample, at: 
https://github.com/xuzhg/WebApiSample/tree/master/IssuesOnWebApi/Issue2180
using EFCore 5.0. below is the output:
![image](https://user-images.githubusercontent.com/9426627/83912992-aa3c6480-a723-11ea-9f9f-638f0c36fa18.png)

You can see the changes in https://github.com/xuzhg/WebApiSample/commit/92e5790f76000f31a9bc5440bcfd7cbfb9c7cbbc

My sample is using VS2019 Preview otherwise, you can't build it for .NET 5.0. Thanks.

**Comment by ewkonzo** [comment]
@xuzhg I think you got an error because you didn't modify the connection string in ```Startup.cs``` to point to a PostgreSQL database like instructed on readme.

Thanks for the updated sample, I also tried reproducing with sqlitedb without success. I am positive there is the change in 7.4.1 only affecting Npgsql implementation and perhaps it can be fixed from that end.

My Sample using postgreSQL requires you to have a separate postgres database installation.. I understand that is too much to ask but please bear with me

**Comment by ilya-chumakov** [comment]
@ewkonzo @xuzhg 
I have this error too and yes, I'm using OData+Npgsql, latest 3.1 packages. However, this error happens only if `in` operator is used. With `eq` operator everything is fine.

```
    status varchar(8) NOT NULL DEFAULT 'NEW'

    public class FooEntity
    {
        public FooEnum Status { get; set; }
    }

    entity.Property(e => e.Status).HasColumnName("status").HasConversion<string>();
```

this works:

    "$filter=status eq 'NEW'"

this throws an "Object must implement IConvertible" exception:

    "$filter=status in ('NEW')"
    
    
packages:
```
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="3.1.11" />
    <PackageReference Include="Microsoft.AspNetCore.OData" Version="7.5.5" />
```

How to provide a sample without attaching a real db?

**Comment by ewkonzo** [comment]
@ilya-chumakov on my side the error only occurs if you are using a real postgres db. I that is also the case for you the no attaching the db don't make sense

**Comment by ilya-chumakov** [comment]
@xuzhg could you tell please why this issue has the label "investigated"? it still unclear even what repo it belongs to :( Any help is appreсiated.

**Comment by ilya-chumakov** [comment]
Oh great, this thread doesn't go to the top of https://github.com/OData/WebApi/issues after a new message appears.

**Comment by ewkonzo** [comment]
> Oh great, this thread doesn't go to the top of https://github.com/OData/WebApi/issues after a new message appears.

Interesting...

**Comment by ewkonzo** [comment]
> Oh great, this thread doesn't go to the top of https://github.com/OData/WebApi/issues after a new message appears.

@xuzhg only investigated this using Sql Server then called it a day. The issue rise with postgres
