### ISSUE TITLE
InvalidOperationException when a function with an explicit route is not included in Edm model

### ISSUE THREAD

**Issue by gathogojr** [OData/WebApi#2185]
If a function with a route explicitly set using `ODataRoute` attribute (plus with `RouteName` property not set) is NOT included in the Edm model, an `InvalidOperationException` is raised when you attempt to browse the metadata or hit any endpoint

Does this mean you can't have a function with an explicit route just lying around in your codebase?

### Assemblies affected
- Microsoft.AspNetCore.OData 7.4.1

### Reproduce steps

1. Create an OData Web API project
2. Add code to configure the service
    ```c#
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddMvc(
            options => options.EnableEndpointRouting = false).SetCompatibilityVersion(CompatibilityVersion.Version_3_0);
        services.AddOData();
    }
    
    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
        var modelBuilder = new ODataConventionModelBuilder();
    
        app.UseMvc(routeBuilder => routeBuilder.MapODataServiceRoute("Route01", "odata", modelBuilder.GetEdmModel()));
    }
    ```
3. Add a controller and define a function with an explicit route
    ```c#
    public class DefaultController : ODataController
    {
        [HttpGet]
        [ODataRoute("GetRating(productId={productId})")]
        public IActionResult GetRating([FromODataUri] int productId)
        {
            var random = new Random(productId);
            var rating = random.Next(0, 5);
    
            return Ok(rating);
        }
    }
    ```
4. Browse the metadata - `http://ServiceRoot/$metadata`

### Expected result

```xml
<?xml version="1.0" encoding="UTF-8"?>
<edmx:Edmx xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx" Version="4.0">
   <edmx:DataServices>
      <Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="Default">
         <Function Name="GetRating">
            <Parameter Name="productId" Type="Edm.Int32" Nullable="false" />
            <ReturnType Type="Edm.Int32" Nullable="false" />
         </Function>
         <EntityContainer Name="Container">
            <FunctionImport Name="GetRating" Function="Default.GetRating" IncludeInServiceDocument="true" />
         </EntityContainer>
      </Schema>
   </edmx:DataServices>
</edmx:Edmx>
```

### Actual result
```
System.InvalidOperationException: The path template 'GetRating(productId={productId})' on the action 'GetRating' in controller 'Default' is not a valid OData path template. Resource not found for the segment 'GetRating'.
   at Microsoft.AspNet.OData.Routing.Conventions.AttributeRoutingConvention.GetODataPathTemplate(String prefix, String pathTemplate, IServiceProvider requestContainer, String controllerName, String actionName)
   at Microsoft.AspNet.OData.Routing.Conventions.AttributeRoutingConvention.<>c__DisplayClass11_0.<GetODataPathTemplates>b__1(ODataRouteAttribute route)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Microsoft.AspNet.OData.Routing.Conventions.AttributeRoutingConvention.BuildAttributeMappings(IEnumerable`1 controllerActions)
   at Microsoft.AspNet.OData.Routing.Conventions.AttributeRoutingConvention.get_AttributeMappings()
   at Microsoft.AspNet.OData.Routing.Conventions.AttributeRoutingConvention.SelectAction(RouteContext routeContext)
   at Microsoft.AspNet.OData.Routing.ODataActionSelector.SelectCandidates(RouteContext context)
   at Microsoft.AspNetCore.Mvc.Routing.MvcRouteHandler.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.Route.OnRouteMatched(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteBase.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
### Additional detail

The issue manifests when the `ODataRoute` attribute matches the following:
- `[ODataRoute("GetRating(productId={productId})")]`
- `[ODataRoute("GetRating(productId={productId})", RouteName = null)]`
- `[ODataRoute("GetRating(productId={productId})", RouteName = "")]`

The issue **does not** manifest when the `ODataRoute` attribute matches the following:
- `[ODataRoute]`
- `[ODataRoute("GetRating(productId={productId})", RouteName = "Route01")]`
- `[ODataRoute("GetRating(productId={productId})", RouteName = "RouteNotConfigured")]`
- `[ODataRoute("GetRating(productId={productId})")]` plus function included in the Edm model as follows:
    ```c#
    var modelBuilder = new ODataConventionModelBuilder();
    modelBuilder.Function("GetRating")
        .Returns<int>()
        .Parameter<int>("productId");
    ````

This issue affects both bound and unbound functions - probably actions as well

The logical workaround when a function is just lying around in the codebase is to ensure that either it doesn't have an explicit route or if it does, the `RouteName` property is set to any non-null or not-empty value.

The problem though is that a typical user won't know what is biting them and are likely to go on a wild goose chase since the error only suggests an invalid OData path template

**Comment by gathogojr** [comment]
FYI: `RouteName` property was added to the `ODataRoute` attribute in this PR to address a different issue https://github.com/OData/WebApi/pull/1390
