### ISSUE TITLE
"A request container already exists on the request." exception for batch requests using endpoint routing

### ISSUE THREAD

**Issue by groogiam** [OData/WebApi#2210]
Batch request do not appear to work when using endpoint routing in ASP.NET Core 3.1

This appears to be the same issue as #2068 but I cannot get past the exception in the 7.4.1 release.

### Assemblies affected

Microsoft.AspNetCore.OData 7.4.1

### Reproduce steps

Calling any batch request fails with the following configuration.

Note: Batch request were working with the commented out UseMvc when endpoint routing was disabled.

I have also tried commenting out the middleware for cors, healthchecks and the open api stuff with the same result.

```c#
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            if (_generalConfig.Security.UseHttpsRedirection)
            {
                app.UseHttpsRedirection();
            }

            app.UseStaticFiles();

            app.UseRouting();

            app.UseCors();

            app.UseHealthChecks("/health");

            app.UseAuthentication();
            app.UseAuthorization();


            if (_generalConfig.Security.EnableOpenApiSpec)
            {
                // Serves the registered OpenAPI/Swagger documents by default on `/swagger/{documentName}/swagger.json`
                app.UseOpenApi();
            }

            if (_generalConfig.Security.EnableOpenApiUi)
            {
                // Serves the Swagger UI 3 web ui to view the OpenAPI/Swagger documents by default on `/swagger`
                app.UseSwaggerUi3(opt => { opt.EnableTryItOut = true; });
            }

            app.UseODataBatching();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapHub<DesignerHub>("/HubTest");

                endpoints.MapControllers();

                //OData
                endpoints.Select().Expand().Filter().OrderBy().MaxTop(500).Count();
                endpoints.MapODataRoute("api", "api", StartupExtensions.GetEdmModel(), new DefaultODataBatchHandler());
                endpoints.EnableDependencyInjection();
            });

            /*app.UseMvc(r =>
            {
                r.Select().Expand().Filter().OrderBy().MaxTop(500).Count();

                r.MapODataServiceRoute("api", "api", StartupExtensions.GetEdmModel(), new DefaultODataBatchHandler());

                r.EnableDependencyInjection();
            });*/
        }
```

### Expected result

Batch requests would execute without exception.

### Actual result

The following exception is thrown.

```
[Error] [Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: A request container already exists on the request.
   at Microsoft.AspNet.OData.Extensions.HttpRequestExtensions.CreateRequestContainer(HttpRequest request, String routeName)
   at Microsoft.AspNet.OData.Batch.DefaultODataBatchHandler.ParseBatchRequestsAsync(HttpContext context)
   at Microsoft.AspNet.OData.Batch.DefaultODataBatchHandler.ProcessBatchAsync(HttpContext context, RequestDelegate nextHandler)
   at Microsoft.AspNet.OData.Batch.ODataBatchMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.SwaggerUiIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.RedirectToIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by xuzhg** [comment]
@groogiam Can you move the batch middleware before the routing middleware?

[Here](https://github.com/OData/WebApi/blob/master/samples/AspNetCore3xEndpointSample.Web/Startup.cs#L50) is one comments. Let me know if it can't work

**Comment by groogiam** [comment]
@xuzhg That looks like it fixed it the issue. Thanks.
