### ISSUE TITLE
OData Expand- Value cannot be null. (Parameter 'key')

### ISSUE THREAD

**Issue by huiali** [OData/WebApi#2218]
*Short summary (3-5 sentences) describing the issue.*

expand 
GET : https://localhost:5002/oq/A?$expand=B($expand=C)-->
ERROR --> Value cannot be null. (Parameter 'key')

But https://localhost:5002/oq/A?$expand=B --> Successful return

Platform: NETCORE 3.1
Database: Mysql

### Assemblies affected

<PackageReference Include="Microsoft.AspNetCore.OData" Version="7.3.0" />
<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="3.1.1" />

### Reproduce steps

class A =>ICollection<B> B HasMany WithOne
class B=> C C HasOne WithMany
class C =>ICollection<B> B

I wrote an example that can reproduce the error, please refer to
[https://github.com/huiali/odata-sample](https://github.com/huiali/odata-sample)

### Expected result

*What would happen if there wasn't a bug.*

System.ArgumentNullException: Value cannot be null. (Parameter 'key')
at System.Collections.Concurrent.ConcurrentDictionary2.ThrowKeyNullException() at System.Collections.Concurrent.ConcurrentDictionary2.TryGetValue(TKey key, TValue& value)
at System.Collections.Concurrent.ConcurrentDictionary2.get_Item(TKey key) at Microsoft.AspNet.OData.Query.Expressions.ModelContainer.GetModel(String id) in S:\src\workspace\WebApi-master\WebApi-master\src\Microsoft.AspNet.OData.Shared\Query\Expressions\ModelContainer.cs:line 29 at Microsoft.AspNet.OData.Query.Expressions.SelectExpandWrapper.GetModel() in S:\src\workspace\WebApi-master\WebApi-master\src\Microsoft.AspNet.OData.Shared\Query\Expressions\SelectExpandWrapper.cs:line 158 at Microsoft.AspNet.OData.Query.Expressions.SelectExpandWrapper.GetEdmType() in S:\src\workspace\WebApi-master\WebApi-master\src\Microsoft.AspNet.OData.Shared\Query\Expressions\SelectExpandWrapper.cs:line 49

![image](https://user-images.githubusercontent.com/29728900/86526295-f6b2c580-bec4-11ea-8961-f9fb1a60dffe.png)

### Actual result

*What is actually happening.*

### Additional detail
[https://github.com/OData/WebApi/issues/2124](Value cannot be null. (Parameter 'key') #2124)

**Comment by xuzhg** [comment]
@huiali ODL and WebApi should work for the nested $expand. I checked with your code, you are using "MySQL" (I don't have MySQL installed). Would you please file the similar issue at: https://github.com/dotnet/efcore/issues. Since EF Core team is working to add "OData" into their test framework.

**Comment by Sreejithpin** [comment]
Duplicate issue of https://github.com/OData/WebApi/issues/2124
hence closing

**Comment by huiali** [comment]
@xuzhg I attached the OData source code, EF can return data normally, OData source code error, please see the following error.
![image](https://user-images.githubusercontent.com/29728900/87065242-5ef60400-c243-11ea-96ca-9300dc4a1708.png)

**Comment by xuzhg** [comment]
> @xuzhg I attached the OData source code, EF can return data normally, OData source code error, please see the following error.
> ![image](https://user-images.githubusercontent.com/29728900/87065242-5ef60400-c243-11ea-96ca-9300dc4a1708.png)

Yes, I have your source code. But, i don't have the MySql installed. Can we switch to other DB to see it can work or not?
