### ISSUE TITLE
FilterBinder.Bind throws System.NullReferenceException converting FilterClause.Expression

### ISSUE THREAD

**Issue by BlaiseD** [OData/WebApi#2237]
This seems to be a popular request:

- [Expose ability convert FilterClause to Linq Expression](https://github.com/OData/WebApi/issues/33)
- [can't convert FilterClause to Linq expression](https://github.com/OData/WebApi/issues/957)

### Assemblies affected
Testing using yesterday's [commit of Microsoft.AspNetCore.OData](https://github.com/OData/WebApi/tree/8e2c3a7c48e9c32519408c87ff8ea13b0e0fb961) . 

### Reproduce steps
```c#
        [HttpGet]
        public async Task<IActionResult> Get(ODataQueryOptions<OpsTenant> options)
        {
            var filterBinder = options.Context.RequestContainer.GetRequiredService<FilterBinder>(); ;
            //Removed for brevity
        }

//Later on
      Expression filter = filterBinder.Bind(filterClause.Expression);
```
Make a request with a filter on a child collection: http://localhost:16324/opstenant?$expand=Buildings($filter=Name eq 'One L1')

### Expected result
FilterBinder.Bind returns an expression.

### Actual result

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.BindRangeVariable(RangeVariable rangeVariable) in C:\.Research\WebApi-master\src\Microsoft.AspNet.OData.Shared\Query\Expressions\FilterBinder.cs:line 582
   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.BindSingleValueNode(SingleValueNode node) in C:\.Research\WebApi-master\src\Microsoft.AspNet.OData.Shared\Query\Expressions\FilterBinder.cs:line 788
   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.Bind(QueryNode node) in C:\.Research\WebApi-master\src\Microsoft.AspNet.OData.Shared\Query\Expressions\FilterBinder.cs:line 198
   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.BindPropertyAccessQueryNode(SingleValuePropertyAccessNode propertyAccessNode) in C:\.Research\WebApi-master\src\Microsoft.AspNet.OData.Shared\Query\Expressions\FilterBinder.cs:line 618
   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.BindSingleValueNode(SingleValueNode node) in C:\.Research\WebApi-master\src\Microsoft.AspNet.OData.Shared\Query\Expressions\FilterBinder.cs:line 794
   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.Bind(QueryNode node) in C:\.Research\WebApi-master\src\Microsoft.AspNet.OData.Shared\Query\Expressions\FilterBinder.cs:line 198
   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.BindBinaryOperatorNode(BinaryOperatorNode binaryOperatorNode) in C:\.Research\WebApi-master\src\Microsoft.AspNet.OData.Shared\Query\Expressions\FilterBinder.cs:line 462
   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.BindSingleValueNode(SingleValueNode node) in C:\.Research\WebApi-master\src\Microsoft.AspNet.OData.Shared\Query\Expressions\FilterBinder.cs:line 779
   at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.Bind(QueryNode node) in C:\.Research\WebApi-master\src\Microsoft.AspNet.OData.Shared\Query\Expressions\FilterBinder.cs:line 198
```
System.NullReferenceException thrown inside `FilterBinder.BindRangeVariable`.

### Additional detail
The problem seems to be that `_lambdaParameters` is null in BindRangeVariable.
```c#
        public virtual Expression BindRangeVariable(RangeVariable rangeVariable)
        {
            ParameterExpression parameter = _lambdaParameters[rangeVariable.Name];
            return ConvertNonStandardPrimitives(parameter);
        }
```

The following works:
```c#
        public virtual Expression BindRangeVariable(RangeVariable rangeVariable)
        {
            if (_lambdaParameters == null)
            {
                _lambdaParameters = new Dictionary<string, ParameterExpression>();
		//may want to handle the null check and initialization inside HandleLambdaParameters
                ParameterExpression parameter = HandleLambdaParameters(new List<RangeVariable> { rangeVariable });
                return ConvertNonStandardPrimitives(parameter);
            }
            else
            {
                ParameterExpression parameter = _lambdaParameters[rangeVariable.Name];
                return ConvertNonStandardPrimitives(parameter);
            }
        }
```

I can create a PR if the fix is appropriate.

**Comment by BlaiseD** [comment]
I can see some issues with this.  It's returning what would be the body without the parameter itself.  So it would still need some work to get the parameter.

Is there a better way to do this?

**Comment by BlaiseD** [comment]
I suppose this is not an option - given there's no response,
