### ISSUE TITLE
Wrong escaped Header (Location) for Objects created with an unicode char within a string-ID causes an Exception

### ISSUE THREAD

**Issue by ckuetbach** [OData/WebApi#2240]
Errors with escaping of unicode Characters as Id of type string.

Given there is a model with a Key of type string. The value of this key is 'ä'. The generated URL will contains chars, that are not valid in Header-Fields. The error may only occur for HTTP 1.1 requests

### Assemblies affected

Microsoft.AspNetCore.OData up to 7.7.0

### Reproduce steps

- Create a model with a string key of type string. 
- POST an element with key "ä"

### Expected result
Object is stored,
HTTP Created is returned,
The Location Header points to the newly created entity: http://localhost:5000/odata/test/umlaute(%27%C3%A4%27)/

### Actual result
Object is stored,
Internal ServerError is returned
An Exception occured, because of an unescaped non-ASCII char http://localhost:5000/odata/test/umlaute(%27ä%27)/ This is invalid for Header Values

### Additional detail

The LinkGenerationHelp creates an correct URI 
https://github.com/OData/WebApi/blob/80999f0dca10cc90ef48906c4323a0724a134ca5/src/Microsoft.AspNet.OData.Shared/Builder/LinkGenerationHelpers.cs#L57, but in https://github.com/OData/WebApi/blob/250e955ff68cedfb0e0553747da11bc1f687a63d/src/Microsoft.AspNetCore.OData/Results/CreatedODataResult.cs#L57 the ToString() Method is called, this will unescape the Non-ASCII chars back to unicode.

```		
Uri u = new Uri("http://localhost:5000/odata/test/umlaute(%27ö%27)/");
Console.WriteLine(u.AbsoluteUri);
Console.WriteLine(u.ToString());
```
will return
``` 
http://localhost:5000/odata/test/umlaute(%27%C3%B6%27)/
http://localhost:5000/odata/test/umlaute(%27ö%27)/
```
This causes an exception while writing the value into the location Header.

``` 
[23:53:52 ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: Invalid non-ASCII or control character in header: 0x00E4
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ThrowInvalidHeaderCharacter(Char ch)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ValidateHeaderCharacters(String headerCharacters)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ValidateHeaderCharacters(StringValues& headerValues)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseHeaders.SetValueFast(String key, StringValues& value)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.Microsoft.AspNetCore.Http.IHeaderDictionary.set_Item(String key, StringValues value)
   at Microsoft.AspNet.OData.Results.CreatedODataResult`1.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
``` 
In my excamples I may have mixed some umlauts.

**Comment by ckuetbach** [comment]
The bug seems not to be reproducable with a test using a Microsoft.AspNetCore.TestHost. I wouldsay, that the TestHost implementation won't check added Header like Kestrel does: https://github.com/dotnet/aspnetcore/blob/dc4670e8d5e8026d3ce832a1e7b5205d34913bce/src/Servers/Kestrel/Core/src/Internal/Http/HttpHeaders.cs

**Comment by gathogojr** [comment]
Hi @ckuetbach. I'm currently looking at your issue.
Did you intend to say **Microsoft.AspNetCore.OData release 7.4.1** in the **Assemblies affected** section? That is the latest release for the OData Web API library. However, the latest release for **Microsoft.OData.Core** library is 7.7.0 so you might have confused the two...

You referenced _WebApi/src/Microsoft.AspNetCore.OData/Results/CreatedODataResult.cs_ so I assume you're returning a `CreatedODataResult` object from your `Post` action method. Note that there are 3 overloads of `Created` method available to you, 2 of which are inherited from `ControllerBase`.
- CreatedResult ControllerBase.Created(Uri uri, object value)
- CreatedResult ControllerBase.Created(string uri, object value)
- CreatedODataResult<TEntity> ODataController.Created<TEntity>(TEntity entity)

What I was able to discover is that the second and third overloads on the list return an invalid location. As an illustration, consider a POST request with the sample payload below (where `LogonName` is the key property):
```json
{
    "LogonName": "Ärne Bjørn",
    "Email": "ärnebjørn@test.com",
    "DateOfBirth": "2001-07-13"
}
```
The second and third overloads will return the following invalid location:
```
http://ServiceRoot/Users('Ãrne BjÃ¸rn')
```
If you attempt to use this to navigate to the created entity, you'll get a 404 - I was using Postman for the investigation.
The OData team intends to remediate the `ODataController.Created` overload.

In the meantime, I advise you to use the first overload on the list as a workaround. Creating the `Uri` enables you to validly escape the special characters. The following statement returns a valid location
```
return Created(new Uri($"{Request.Scheme}://{Request.Host}{Request.Path}/{user.LogonName}", UriKind.Absolute), user);
```
Location:
```
http://ServiceRoot/Users/%C3%84rne%20Bj%C3%B8rn
```

**Comment by ckuetbach** [comment]
Hi @gathogojr ,

I've testest the behavior with `Microsoft.AspNetCore.OData 7.4.1` and 
`Microsoft.Odata.Core 7.7.0`. 

My application is still running in dotnet core 2.1. This could explain, why you've found an encoding issue (the umlaut isn't encoded as utf-8 properly) and I have an exception within the header-value validation of the underlying kesterel web server.

I was able to create valid URLs with the first overload from your list. But I'm not sure, if other links may be corrupt as well (within the payload, like `@odata.editLink`).

**Comment by gathogojr** [comment]
@ckuetbach FYI, I created a PR that should resolve the issue. @odata.editLink should be taken care of too.

**Comment by ckuetbach** [comment]
@gathogojr Thanks a lot.

I wonder how I could create the nuget packages locally to test the fix, because my problem was like the Issue you found but did not have exactly same consequences. In my application I got an 500 error while writing the location header.
