### ISSUE TITLE
ArgumentNullException when attempting to filter within a dynamic complex object

### ISSUE THREAD

**Issue by ificator** [OData/WebApi#2272]
The following request will fail due to an `ArgumentNullException` while executing the `FilterBinder`:
```
/openTypes?$filter=dynamicproperty/innerdynamicproperty%20eq%20null
```

### Assemblies affected

Microsoft.AspNet.OData 7.4.1

### Reproduce steps

1. Define a model that has a collection of an open type
1. Query that collection and provide a filter like the one shown above

### Expected result

The `FilterBinder` completes successfully

### Actual result

The request fails due to an `ArgumentNullException`

### Additional detail

```
at Microsoft.OData.Edm.EdmUtil.CheckArgumentNull[T](T value, String parameterName)
at Microsoft.OData.Edm.EdmTypeSemantics.IsEntity(IEdmTypeReference type)
at Microsoft.AspNet.OData.Query.Expressions.ExpressionBinderBase.GetDynamicPropertyContainer(SingleValueOpenPropertyAccessNode openNode)
at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.BindDynamicPropertyAccessQueryNode(SingleValueOpenPropertyAccessNode openNode)
at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.BindSingleValueNode(SingleValueNode node)
at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.Bind(QueryNode node)
at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.BindBinaryOperatorNode(BinaryOperatorNode binaryOperatorNode)
at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.BindSingleValueNode(SingleValueNode node)
at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.Bind(QueryNode node)
at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.BindExpression(SingleValueNode expression, RangeVariable rangeVariable, Type elementType)
at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.BindFilterClause(FilterBinder binder, FilterClause filterClause, Type filterType)
at Microsoft.AspNet.OData.Query.Expressions.FilterBinder.Bind(IQueryable baseQuery, FilterClause filterClause, Type filterType, ODataQueryContext context, ODataQuerySettings querySettings)
at Microsoft.AspNet.OData.Query.FilterQueryOption.ApplyTo(IQueryable query, ODataQuerySettings querySettings)
at Microsoft.AspNet.OData.Query.ODataQueryOptions.ApplyTo(IQueryable query, ODataQuerySettings querySettings)
```

**Comment by gathogojr** [comment]
@ificator Thank your reporting the issue. We currently don't supported filtering using a nested dynamic property. Dynamic property segment should be the last segment in any odata path - based on the OData spec. Which scenario would require you to do something like this?

**Comment by ificator** [comment]
We have an extension mechanism like what is described in the [Microsoft Graph documentation](https://docs.microsoft.com/en-us/graph/extensibility-schema-groups?context=graph%2Fapi%2F1.0&view=graph-rest-1.0). They actually have an example that aligns pretty well:

*Request:*
```
GET https://graph.microsoft.com/v1.0/groups?$filter=graphlearn_courses/courseId eq ‘123’&$select=displayName,id,description,graphlearn_courses
```
*Response:*
```
HTTP/1.1 200 OK
Content-Type: application/json
Content-length: 326
{
  "value": [
    {
      "displayName": "New Managers March 2017",
      "id": "14429ae5-3e74-41a2-9fa8-028fbb984637",
      "description": "New Managers training course for March 2017",
      "graphlearn_courses": {
        "@odata.type": "#microsoft.graph.ComplexExtensionValue",
        "courseId":"123",
        "courseName":"New Managers",
        "courseType":"Online"
      }
    }
  ]
}
```
In this example the `group` entities returned from the `groups` entity set do not have `graphlearn_courses` defined - it's a dynamic property. But the scenario requires that a caller be able to find all `group` entities with `graphlearn_courses/courseId` of a specific value.

To be honest, I'm not sure how the Microsoft Graph team implemented this... maybe they're only using odatalib?

**Comment by ificator** [comment]
Ping @gathogojr

**Comment by KenitoInc** [comment]
Not supported by the spec

**Comment by ificator** [comment]
Do you mind pointing me to the part of the spec where this is called out? I don't see any mention of dynamic properties in relation to `$filter`, nor do I see anything that states that `$filter` only applies to entity / schema types.

If it truly is against spec then either ODataLib should fail parsing the query string.
