### ISSUE TITLE
ODataModelBuilder does not add ClrPropertyInfoAnnotation for certian inheritance heirarchies

### ISSUE THREAD

**Issue by ethanshea-ms** [OData/WebApi#2297]
I encountered this bug when trying to deserialize a property where I changed the name in the EDM model. The property is declared in an abstract CLR type, and I am deserializing one of multiple EDM types. Each EDM type independently defines the property specified in the base CLR type. 

I believe my scenario is best explained by a code example.

https://dotnetfiddle.net/wjhKdt

```csharp
using System;
using Microsoft.AspNet.OData;
using Microsoft.AspNet.OData.Builder;
using Microsoft.OData.Edm;

namespace TestNamespace 
{
    public class Program
    {	
        public static void Main()
        {
            var builder = new ODataModelBuilder();
            
            var derivedType = builder.ComplexType<TestModelDerived>();
            var inheritedProperty = derivedType.Property(d => d.InheritedProperty);
            inheritedProperty.Name = "inheritedProperty";
            
            var alsoDerivedType = builder.ComplexType<TestModelAlsoDerived>();
            
            // Commenting out this line will change the program output
            var secondInheritedProperty = alsoDerivedType.Property(d => d.InheritedProperty);
            
            var model = builder.GetEdmModel();

            var type = model.FindDeclaredType("TestNamespace.TestModelDerived") as IEdmStructuredType;
            var property = type.FindProperty("inheritedProperty");
            var annotation = model.GetAnnotationValue<ClrPropertyInfoAnnotation>(property);
            
            // Expected behavior is that this is not null. Program output should be "False"
            Console.WriteLine(annotation == null);
        }
    }

    public class TestModelBase 
    {
        public string InheritedProperty { get; set; }
    }
    
    public class TestModelDerived : TestModelBase
    {
    }
    
    public class TestModelAlsoDerived : TestModelBase
    {
    }
}
```

Because the model builder does not correctly assign the ClrPropertyInfoAnnotation, downstream tasks such as serialization are affected. In particular I get something like the below stack trace, indicating an internal error. When debugging, I find that `propertyName` in `SetDeclaredProperty` is using the EDM name rather than the CLR name because the call to `EdmLibHelper.GetClrPropertyName` did not find the annotation.

<details>
  <summary>Stack Trace</summary>

```
System.ArgumentNullException: Value cannot be null. (Parameter 'nullableType')
   at System.Nullable.GetUnderlyingType(Type nullableType)
   at Microsoft.AspNet.OData.Formatter.EdmPrimitiveHelpers.ConvertPrimitiveValue(Object value, Type type)
   at Microsoft.AspNet.OData.Formatter.Deserialization.DeserializationHelpers.SetDeclaredProperty(Object resource, EdmTypeKind propertyKind, String propertyName, Object propertyValue, IEdmProperty edmProperty, ODataDeserializerContext readContext)
   at Microsoft.AspNet.OData.Formatter.Deserialization.DeserializationHelpers.ApplyProperty(ODataProperty property, IEdmStructuredTypeReference resourceType, Object resource, ODataDeserializerProvider deserializerProvider, ODataDeserializerContext readContext)
   at Microsoft.AspNet.OData.Formatter.Deserialization.ODataResourceDeserializer.ApplyStructuralProperty(Object resource, ODataProperty structuralProperty, IEdmStructuredTypeReference structuredType, ODataDeserializerContext readContext)
   at Microsoft.AspNet.OData.Formatter.Deserialization.ODataResourceDeserializer.ApplyStructuralProperties(Object resource, ODataResourceWrapper resourceWrapper, IEdmStructuredTypeReference structuredType, ODataDeserializerContext readContext)
   at Microsoft.AspNet.OData.Formatter.Deserialization.ODataResourceDeserializer.ApplyResourceProperties(Object resource, ODataResourceWrapper resourceWrapper, IEdmStructuredTypeReference structuredType, ODataDeserializerContext readContext)
   at Microsoft.AspNet.OData.Formatter.Deserialization.ODataResourceDeserializer.ReadResource(ODataResourceWrapper resourceWrapper, IEdmStructuredTypeReference structuredType, ODataDeserializerContext readContext)
   at Microsoft.AspNet.OData.Formatter.Deserialization.ODataResourceDeserializer.ReadInline(Object item, IEdmTypeReference edmType, ODataDeserializerContext readContext)
   at Microsoft.AspNet.OData.Formatter.Deserialization.ODataResourceDeserializer.ReadResource(ODataResourceWrapper resourceWrapper, IEdmStructuredTypeReference structuredType, ODataDeserializerContext readContext)
   at Microsoft.AspNet.OData.Formatter.Deserialization.ODataResourceDeserializer.ReadInline(Object item, IEdmTypeReference edmType, ODataDeserializerContext readContext)
   at Microsoft.AspNet.OData.Formatter.Deserialization.ODataResourceSetDeserializer.ReadResourceSet(ODataResourceSetWrapper resourceSet, IEdmStructuredTypeReference elementType, ODataDeserializerContext readContext)+MoveNext()
   at System.Linq.Enumerable.CastIterator[TResult](IEnumerable source)+MoveNext()
   at Microsoft.AspNet.OData.Formatter.Deserialization.CollectionDeserializationHelpers.AddToCollectionCore(IEnumerable items, IEnumerable collection, Type elementType, IList list, MethodInfo addMethod)
   at Microsoft.AspNet.OData.Formatter.Deserialization.CollectionDeserializationHelpers.AddToCollection(IEnumerable items, IEnumerable collection, Type elementType, Type resourceType, String propertyName, Type propertyType)
   at Microsoft.AspNet.OData.Formatter.Deserialization.DeserializationHelpers.SetCollectionProperty(Object resource, String propertyName, IEdmCollectionTypeReference edmPropertyType, Object value, Boolean clearCollection)
   at Microsoft.AspNet.OData.Formatter.Deserialization.DeserializationHelpers.SetCollectionProperty(Object resource, IEdmProperty edmProperty, Object value, String propertyName)
   at Microsoft.AspNet.OData.Formatter.Deserialization.ODataResourceDeserializer.ApplyResourceSetInNestedProperty(IEdmProperty nestedProperty, Object resource, ODataResourceSetWrapper resourceSetWrapper, ODataDeserializerContext readContext)
   at Microsoft.AspNet.OData.Formatter.Deserialization.ODataResourceDeserializer.ApplyNestedProperty(Object resource, ODataNestedResourceInfoWrapper resourceInfoWrapper, IEdmStructuredTypeReference structuredType, ODataDeserializerContext readContext)
   at Microsoft.AspNet.OData.Formatter.Deserialization.ODataResourceDeserializer.ApplyNestedProperties(Object resource, ODataResourceWrapper resourceWrapper, IEdmStructuredTypeReference structuredType, ODataDeserializerContext readContext)
   at Microsoft.AspNet.OData.Formatter.Deserialization.ODataResourceDeserializer.ApplyResourceProperties(Object resource, ODataResourceWrapper resourceWrapper, IEdmStructuredTypeReference structuredType, ODataDeserializerContext readContext)
   at Microsoft.AspNet.OData.Formatter.Deserialization.ODataResourceDeserializer.ReadResource(ODataResourceWrapper resourceWrapper, IEdmStructuredTypeReference structuredType, ODataDeserializerContext readContext)
   at Microsoft.AspNet.OData.Formatter.Deserialization.ODataResourceDeserializer.ReadInline(Object item, IEdmTypeReference edmType, ODataDeserializerContext readContext)
   at Microsoft.AspNet.OData.Formatter.Deserialization.ODataResourceDeserializer.ReadNestedResourceInline(ODataResourceWrapper resourceWrapper, IEdmTypeReference edmType, ODataDeserializerContext readContext)
   at Microsoft.AspNet.OData.Formatter.Deserialization.ODataResourceDeserializer.ApplyResourceInNestedProperty(IEdmProperty nestedProperty, Object resource, ODataResourceWrapper resourceWrapper, ODataDeserializerContext readContext)
   at Microsoft.AspNet.OData.Formatter.Deserialization.ODataResourceDeserializer.ApplyNestedProperty(Object resource, ODataNestedResourceInfoWrapper resourceInfoWrapper, IEdmStructuredTypeReference structuredType, ODataDeserializerContext readContext)
   at Microsoft.AspNet.OData.Formatter.Deserialization.ODataResourceDeserializer.ApplyNestedProperties(Object resource, ODataResourceWrapper resourceWrapper, IEdmStructuredTypeReference structuredType, ODataDeserializerContext readContext)
   at Microsoft.AspNet.OData.Formatter.Deserialization.ODataResourceDeserializer.ApplyResourceProperties(Object resource, ODataResourceWrapper resourceWrapper, IEdmStructuredTypeReference structuredType, ODataDeserializerContext readContext)
   at Microsoft.AspNet.OData.Formatter.Deserialization.ODataResourceDeserializer.ReadResource(ODataResourceWrapper resourceWrapper, IEdmStructuredTypeReference structuredType, ODataDeserializerContext readContext)
   at Microsoft.AspNet.OData.Formatter.Deserialization.ODataResourceDeserializer.ReadInline(Object item, IEdmTypeReference edmType, ODataDeserializerContext readContext)
   at Microsoft.AspNet.OData.Formatter.Deserialization.ODataResourceDeserializer.Read(ODataMessageReader messageReader, Type type, ODataDeserializerContext readContext)
<omitted application code>
```
</details>

### Assemblies affected

Microsoft.AspNet.OData.dll, Microsoft.AspNetCore.OData.dll 7.4.1

Possibly also the ODataModelBuilder in other places like https://github.com/OData/ModelBuilder

**Comment by xuzhg** [comment]
@ethanshea-ms 

It's interesting.

```C#
PropertyInfo property0 = typeof(TestModelBase).GetProperty("InheritedProperty");
PropertyInfo property1 = typeof(TestModelDerived).GetProperty("InheritedProperty");
PropertyInfo property2 = typeof(TestModelAlsoDerived).GetProperty("InheritedProperty");
```
Where, **propert0 != property1** and **property1 != property2** &&  **property0 != property2**

the difference is the "ReflectedType" property.

However,
`var inheritedProperty = derivedType.Property(d => d.InheritedProperty);`
`var secondInheritedProperty = alsoDerivedType.Property(d => d.InheritedProperty);`

we use the Linq Expression and the "PropertyInfo" we get from the Linq Expression are same.

Internally, we use the "PropertyInfo" as the key to build mapping between CLR property and Edm property. So, it's a problem.

As a workaround before we find a way to fix, you can call the fluent API `AddProperty`

```C#
PropertyInfo property1 = typeof(TestModelDerived).GetProperty("InheritedProperty");
PropertyInfo property2 = typeof(TestModelAlsoDerived).GetProperty("InheritedProperty");

derivedType.Configuration.AddProperty(property1).Name = "inheritedProperty";

//var inheritedProperty = derivedType.Property(d => d.InheritedProperty);
//inheritedProperty.Name = "inheritedProperty";

var alsoDerivedType = builder.ComplexType<TestModelAlsoDerived>();
alsoDerivedType.Configuration.AddProperty(property2);

// Commenting out this line will change the program output
// var secondInheritedProperty = alsoDerivedType.Property(d => d.InheritedProperty);
`

**Comment by garethj-msft** [comment]
Just to note @xuzhg, in your workaround example above, the `Configuration `property is internal so can't be used by customers.
Seems to me this limitation should be removed and the property getter made public, as it causes a bunch of worse workarounds.

A public workaround is to use something like 

```C#
    // Replace alsoDerivedType.Configuration.AddProperty(property2); with the following:
    builder.StructuralTypes.OfType<ComplexTypeConfiguration>().
        Single(c => c.ClrType == typeof(TestModelAlsoDerived)).AddProperty(property2);

```

**Comment by xuzhg** [comment]
@garethj-msft Thanks for pointing this out. 

Yes, My sample code is tested in the "model builder" project. 

Besides your suggest,  another way (recommended) is to call the following to get the "Configuration".
`var configuration = builder.AddComplexType(typeof(TestModelAlsoDerived));`
