### ISSUE TITLE
$filter=contains(json property, string) doesn't work in OData v7.4.1 

### ISSUE THREAD

**Issue by onurbos** [OData/WebApi#2322]
I would like to filter json column in OData but i couldn't.

### Assemblies affected

PackageReference Include="Microsoft.AspNetCore.OData" Version="7.4.1" 

### Reproduce steps

 public IActionResult Find(ODataQueryOptions<Entity> queryOptions)
        {
              var items= entityRepository.Find();
              var queryResults = (IQueryable<Entity>)queryOptions.ApplyTo(items, new ODataQuerySettings() { EnsureStableOrdering = false });
              return Ok(new PageResult<Entity>(queryResults, Request.ODataFeature().NextLink, Request.ODataFeature().TotalCount));
        }

Affected Property
 [Column("languages", TypeName = "jsonb")]
  public string Languages { get; set; }

http://localhost:5004/api/entity/find?%24format=json&%24top=10&%24filter=contains(tolower(languages%2Flabel1%2Fname)%2C%27BT%27)&%24count=true

$format: json
$top: 10
$filter: contains(tolower(languages/label1/name), 'BT')
$count: true

### Expected result

default: false
deleted: false
id: 9
languages: "{"label1": {"name": "BT Manager", "description": null}, "label2": {"name":  null, "description": null}}"

### Actual result

Microsoft.OData.ODataException: Could not find a property named 'label1' on type 'Edm.String'.
   at Microsoft.OData.UriParser.InnerPathTokenBinder.BindInnerPathSegment(InnerPathToken segmentToken)
   at Microsoft.OData.UriParser.MetadataBinder.BindInnerPathSegment(InnerPathToken token)
   at Microsoft.OData.UriParser.MetadataBinder.Bind(QueryToken token)
   at Microsoft.OData.UriParser.EndPathBinder.DetermineParentNode(EndPathToken segmentToken)
   at Microsoft.OData.UriParser.EndPathBinder.BindEndPath(EndPathToken endPathToken)
   at Microsoft.OData.UriParser.MetadataBinder.BindEndPath(EndPathToken endPathToken)
   at Microsoft.OData.UriParser.MetadataBinder.Bind(QueryToken token)
   at Microsoft.OData.UriParser.MetadataBinder.BindFunctionParameter(FunctionParameterToken token)
   at Microsoft.OData.UriParser.MetadataBinder.Bind(QueryToken token)
   at Microsoft.OData.UriParser.FunctionCallBinder.<BindFunctionCall>b__7_0(FunctionParameterToken ar)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Microsoft.OData.UriParser.FunctionCallBinder.BindFunctionCall(FunctionCallToken functionCallToken)
   at Microsoft.OData.UriParser.MetadataBinder.BindFunctionCall(FunctionCallToken functionCallToken)
   at Microsoft.OData.UriParser.MetadataBinder.Bind(QueryToken token)
   at Microsoft.OData.UriParser.MetadataBinder.BindFunctionParameter(FunctionParameterToken token)
   at Microsoft.OData.UriParser.MetadataBinder.Bind(QueryToken token)
   at Microsoft.OData.UriParser.FunctionCallBinder.<BindFunctionCall>b__7_0(FunctionParameterToken ar)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Microsoft.OData.UriParser.FunctionCallBinder.BindFunctionCall(FunctionCallToken functionCallToken)
   at Microsoft.OData.UriParser.MetadataBinder.BindFunctionCall(FunctionCallToken functionCallToken)
   at Microsoft.OData.UriParser.MetadataBinder.Bind(QueryToken token)
   at Microsoft.OData.UriParser.BinaryOperatorBinder.GetOperandFromToken(BinaryOperatorKind operatorKind, QueryToken queryToken)
   at Microsoft.OData.UriParser.BinaryOperatorBinder.BindBinaryOperator(BinaryOperatorToken binaryOperatorToken)
   at Microsoft.OData.UriParser.MetadataBinder.BindBinaryOperator(BinaryOperatorToken binaryOperatorToken)
   at Microsoft.OData.UriParser.MetadataBinder.Bind(QueryToken token)
   at Microsoft.OData.UriParser.BinaryOperatorBinder.GetOperandFromToken(BinaryOperatorKind operatorKind, QueryToken queryToken)
   at Microsoft.OData.UriParser.BinaryOperatorBinder.BindBinaryOperator(BinaryOperatorToken binaryOperatorToken)
   at Microsoft.OData.UriParser.MetadataBinder.BindBinaryOperator(BinaryOperatorToken binaryOperatorToken)
   at Microsoft.OData.UriParser.MetadataBinder.Bind(QueryToken token)
   at Microsoft.OData.UriParser.FilterBinder.BindFilter(QueryToken filter)
   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseFilterImplementation(String filter, ODataUriParserConfiguration configuration, ODataPathInfo odataPathInfo)
   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseFilter()
   at Microsoft.AspNet.OData.Query.FilterQueryOption.get_FilterClause()
   at Microsoft.AspNet.OData.Query.FilterQueryOption.ApplyTo(IQueryable query, ODataQuerySettings querySettings)
   at Microsoft.AspNet.OData.Query.ODataQueryOptions.ApplyTo(IQueryable query, ODataQuerySettings querySettings)
   at Microsoft.AspNet.OData.Query.ODataQueryOptions`1.ApplyTo(IQueryable query, ODataQuerySettings querySettings)

### Additional detail

*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by gathogojr** [comment]
Hi @onurbos. We currently do not support the ability to query a JSON string using the property path syntax. You can define a complex type for Languages matching the structure of the JSON object. You could then load the JSON string into that property and use the $filter option with the property path
