### ISSUE TITLE
Instance annotation fails using ODataResourceValue 

### ISSUE THREAD

**Issue by xuzhg** [OData/WebApi#2328]
*Short summary (3-5 sentences) describing the issue.*

### Assemblies affected

Web API OData 7.5

### Reproduce steps

I have the instance annotation for the resource whose value is a "ODataResourceValue".

```C#
ODataInstanceAnnotationContainer container = new ODataInstanceAnnotationContainer();
container.AddResourceAnnotation("NS.ResourceTerm", new ODataResourceValue
{
    TypeName = "InstanceAnnotationWebApiTest.Models.Address",
    Properties = new ODataProperty[]
    {
        new ODataProperty { Name = "Street", Value = "156TH AVE NE" },
        new ODataProperty { Name = "City", Value = "Redmond" }
    }
});
container.AddPropertyAnnotation("Name", "NS.DisplayName", "DisplayName");

_customers = new Customer[]
{
    new Customer
    {
        Id = 1,
        Name = "Freezing",
        Dynamics = new Dictionary<string, object>
        {
            { "StringDynamicProperty", "abc" }
        },
        Container = container
    },
    new Customer
    {
        Id = 2,
        Name = "Hot",
        Dynamics = new Dictionary<string, object>
        {
            { "IntDynamicProperty", 123 }
        },
        Container = new ODataInstanceAnnotationContainer()
    }
};
```

Here's an action in the "CustomersController".

```C#
 [HttpGet]
public IEnumerable<Customer> Get()
{
       return _customers;
 }

 [HttpGet]
 public Customer Get(int key)
 {
       return _customers.FirstOrDefault(k => k.Id == key);
  }
```

When I file request: "http://localhost:5000/odata/Customers"

### Expected result

The response with the correct json payload.

### Actual result

```json
{
    "@odata.context": "http://localhost:5000/odata/$metadata#Customers",
    "value": [
```
### Additional detail

```C#
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: The given model does not contain the type 'Microsoft.OData.ODataResourceValue'.
         at Microsoft.AspNet.OData.Formatter.Serialization.ODataSerializerContext.GetEdmType(Object instance, Type type)         at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.AddODataAnnotations(ICollection`1 InstanceAnnotations, ResourceContext resourceContext, KeyValuePair`2 annotation)
         at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.AppendInstanceAnnotations(ODataResource resource, ResourceContext resourceContext)
         at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.CreateResource(SelectExpandNode selectExpandNode, ResourceContext resourceContext)
         at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteResource(Object graph, ODataWriter writer, ODataSerializerContext writeContext, IEdmTypeReference expectedType)
         at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteObjectInline(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext)
         at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteResourceSet(IEnumerable enumerable, IEdmTypeReference resourceSetType, ODataWriter writer, ODataSerializerContext writeContext)
         at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteObjectInline(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext)
         at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteObject(Object graph, Type type, ODataMessageWriter messageWriter, ODataSerializerContext writeContext)
         at Microsoft.AspNet.OData.Formatter.ODataOutputFormatterHelper.WriteToStream(Type type, Object value, IEdmModel model, ODataVersion version, Uri baseAddress, MediaTypeHeaderValue contentType, IWebApiUrlHelper internaUrlHelper, IWebApiRequestMessage internalRequest, IWebApiHeaders internalRequestHeaders, Func`2 getODataMessageWrapper, Func`2 getEdmTypeSerializer, Func`2 getODataPayloadSerializer, Func`1 getODataSerializerContext)
         at Microsoft.AspNet.OData.Formatter.ODataOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|27_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by xuzhg** [comment]
We should use the CLR type to create the resource value.

```
container.AddResourceAnnotation("NS.ResourceAddress", new Address
            {
                Street = "156th AVE",
                City = "Redmond"
            });
```
