### ISSUE TITLE
Batch request fails to handle Cookie header

### ISSUE THREAD

**Issue by NicholasNoise** [OData/WebApi#2378]
Unable to send odata batch request with any cookie header, such as IdentityServer4 antiforgery.

### Assemblies affected

Microsoft.AspNetCore.OData 7.5.*

### Reproduce steps

Send batch request with any `Cookie` header.

### Expected result

Standard batch behavior.

### Actual result

Batch request and each changeset are failed

### Additional detail

```
   System.ArgumentException: An item with the same key has already been added. Key: Cookie
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Microsoft.AspNetCore.Http.HeaderDictionary.Add(KeyValuePair`2 item)
   at Microsoft.AspNet.OData.Batch.ODataBatchReaderExtensions.CreateHttpContext(HttpContext originalContext)
   at Microsoft.AspNet.OData.Batch.ODataBatchReaderExtensions.ReadOperationInternalAsync(ODataBatchReader reader, HttpContext originalContext, Guid batchId, Nullable`1 changeSetId, CancellationToken cancellationToken, Boolean bufferContentStream)
   at Microsoft.AspNet.OData.Batch.ODataBatchReaderExtensions.ReadChangeSetRequestAsync(ODataBatchReader reader, HttpContext context, Guid batchId, CancellationToken cancellationToken)
   at Microsoft.AspNet.OData.Batch.DefaultODataBatchHandler.ParseBatchRequestsAsync(HttpContext context)
   at NewPlatform.Flexberry.ORM.ODataService.Batch.DataObjectODataBatchHandler.ProcessBatchAsync(HttpContext context, RequestDelegate nextHandler)
   at Microsoft.AspNet.OData.Batch.ODataBatchMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**Comment by NicholasNoise** [comment]
Merged and fixed.
