### ISSUE TITLE
Microsoft.AspNetCore.OData 8.0.0-beta ASRoutePatternException: The route template separator character '/' cannot appear consecutively. It must be separated by either a parameter or a literal value.

### ISSUE THREAD

**Issue by groogiam** [OData/WebApi#2423]
I receive the following error on startup when trying to use OData for .NET 5

ASRoutePatternException: The route template separator character '/' cannot appear consecutively. It must be separated by either a parameter or a literal value.

Configuration code was below. 

```c#
 services.AddOData(opt =>
            {
                opt.AddModel("api", StartupExtensions.GetEdmModel(), new DefaultODataBatchHandler()).Select().Expand()
                    .Filter().OrderBy().SetMaxTop(500).Count();
            });
```

### Assemblies affected
Microsoft.AspNetCore.OData
8.0.0-beta

### Reproduce steps

I converted the 3.0 style api inside the UseEndPoints to the above code and now the application will not start.

```c#
      //OData
                endpoints.Select().Expand().Filter().OrderBy().MaxTop(500).Count();
                endpoints.MapODataRoute("api", "api", StartupExtensions.GetEdmModel(), new DefaultODataBatchHandler());
                //endpoints.EnableDependencyInjection();

```
### Expected result
Exception should not be thrown.

### Actual result

ASRoutePatternException: The route template separator character '/' cannot appear consecutively. It must be separated by either a parameter or a literal value.

**Comment by xuzhg** [comment]
@groogiam Would you please share a repo for me?

**Comment by groogiam** [comment]
Working on it. Stack trace which I forgot to add to the original issue is below. Thanks.

Microsoft.AspNetCore.Routing.Patterns.RoutePatternException: The route template separator character '/' cannot appear consecutively. It must be separated by either a parameter or a literal value.
   at Microsoft.AspNetCore.Routing.Patterns.RoutePatternParser.Parse(String pattern)
   at Microsoft.AspNetCore.Routing.Patterns.RoutePatternFactory.Parse(String pattern)
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointFactory.AddEndpoints(List`1 endpoints, HashSet`1 routeNames, ActionDescriptor action, IReadOnlyList`1 routes, IReadOnlyList`1 conventions, Boolean createInertEndpoints)
   at Microsoft.AspNetCore.Mvc.Routing.ControllerActionEndpointDataSource.CreateEndpoints(IReadOnlyList`1 actions, IReadOnlyList`1 conventions)
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.UpdateEndpoints()
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.Initialize()
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.get_Endpoints()
   at Microsoft.AspNetCore.Routing.CompositeEndpointDataSource.<>c.<Initialize>b__15_0(EndpointDataSource d)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.AspNetCore.Routing.CompositeEndpointDataSource.Initialize()
   at Microsoft.AspNetCore.Routing.CompositeEndpointDataSource.GetChangeToken()
   at Microsoft.AspNetCore.Routing.DataSourceDependentCache`1.Initialize()
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at System.Threading.LazyInitializer.EnsureInitialized[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at Microsoft.AspNetCore.Routing.Matching.DataSourceDependentMatcher..ctor(EndpointDataSource dataSource, Lifetime lifetime, Func`1 matcherBuilderFactory)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcherFactory.CreateMatcher(EndpointDataSource dataSource)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.InitializeCoreAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatcher|8_0(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task`1 matcherTask)
   at Microsoft.AspNetCore.OData.Batch.ODataBatchMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by groogiam** [comment]
I cannot reproduce it outside of my project yet but the edm model names appear to be conflicting with those of the controllers.

E.g. If I register this 

modelBuilder.EntitySet<Book>("Book");

then if the controller is called BookController. I get the error. I can't still can't reproduce it in a sample. My controllers inherit from a base class but they only a constructor and a couple helper methods so I can't imagine that would be the cause.

**Comment by xuzhg** [comment]
In this case, would you please share:

1) Can you get the metadata (CSDL) file? It's easy to send request `$metadata` to any "api"
2) Share me your "BuildEdmModel()"
3) Share me your "startup.cs"
4) Share me your controller

**Comment by groogiam** [comment]
What I said earlier may not be completely correct. It looks like it is the just the entity definition that causes the error. However if I create a copy of the entity it appears to work.

2. This works
```
services.AddOData(opt =>
            {
                var modelBuilder = new ODataConventionModelBuilder();
                var entitySet = modelBuilder.EntitySet<BusinessDomainDefinitionCopy>(nameof(BusinessDomainDefinition));
                entitySet.EntityType.HasKey(entity => entity.Id);
                var model = modelBuilder.GetEdmModel();

                opt.AddModel("api", model, new DefaultODataBatchHandler()).Select().Expand()
                    .Filter().OrderBy().SetMaxTop(500).Count();
            });
```

But this does not. This is strange because the entity with Copy post fixed is an exact copy. So It maybe appears to be related to backreference relationships?

```
services.AddOData(opt =>
            {
                var modelBuilder = new ODataConventionModelBuilder();
                var entitySet = modelBuilder.EntitySet<BusinessDomainDefinition>(nameof(BusinessDomainDefinition));
                entitySet.EntityType.HasKey(entity => entity.Id);
                var model = modelBuilder.GetEdmModel();

                opt.AddModel("api", model, new DefaultODataBatchHandler()).Select().Expand()
                    .Filter().OrderBy().SetMaxTop(500).Count();
            });
```

Is there a way I can share the files requested privately?

**Comment by xuzhg** [comment]
you can share it sending email to: "saxu@microsoft.com"

**Comment by groogiam** [comment]
The project is hosted in azure dev ops I can give you access to the code there if that would help.

**Comment by xuzhg** [comment]
@groogiam
Yes, please.
By the way, I got your email. It seems i can't find the root cause using my eyes on these codes. 
is your project easy to build/run?

**Comment by groogiam** [comment]
Just sent you a dev ops invite and database backup. It should build right out of source control.

**Comment by groogiam** [comment]
Updating the data contract namespace fixed the issue as you described in our email conversation. Thanks again for your help.
