### ISSUE TITLE
EDM model exception of OData not caught in global exception handler 

### ISSUE THREAD

**Issue by gohilravi** [OData/WebApi#2616]
*Short summary (3-5 sentences) describing the issue.*
When providing the wrong input parameter in the OData function i.e. string instead of integer then ODataException is thrown which is not caught in the global exception handler and below error is returned:
`Microsoft.OData.ODataException: The parameter value ($234) from request is not valid. The parameter value should be format of type 'Edm.Int64'.
 ---> Microsoft.OData.ODataException: Expected literal type token but found token '$234'.
   at Microsoft.OData.UriParser.ExpressionLexerLiteralExtensions.ReadLiteralToken(ExpressionLexer expressionLexer)
   at Microsoft.OData.ODataUriUtils.ConvertFromUriLiteral(String value, ODataVersion version, IEdmModel model, IEdmTypeReference typeReference)
   at Microsoft.AspNetCore.OData.Routing.Template.SegmentTemplateHelpers.Match(ODataTemplateTranslateContext context, IEdmFunction function, IDictionary'2 parameterMappings)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.OData.Routing.Template.SegmentTemplateHelpers.Match(ODataTemplateTranslateContext context, IEdmFunction function, IDictionary' parameterMappings)
   at Microsoft.AspNetCore.OData.Routing.Template.FunctionSegmentTemplate.TryTranslate(ODataTemplateTranslateContext context)
   at Microsoft.AspNetCore.OData.Routing.Template.DefaultODataTemplateTranslator.Translate(ODataPathTemplate path, ODataTemplateTranslateContext context)
   at Microsoft.AspNetCore.OData.Routing.ODataRoutingMatcherPolicy.ApplyAsync(HttpContext httpContext, CandidateSet candidates)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatch|8_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at CorrelationId.CorrelationIdMiddleware.Invoke(HttpContext context, ICorrelationContextFactory correlationContextFactory)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`
### Assemblies affected

Microsoft.OData 8.0.6 NuGet package
### Reproduce steps

Attached screenshot of the issue.
<img width="895" alt="OData exception" src="https://user-images.githubusercontent.com/34128405/150502641-71d96dbd-76e8-4828-b0bc-da4134aa8d36.PNG">

### Expected result

The exception should be handled in the global exception handler.

### Actual result

The exception is not being handled in the global exception handler.

### Additional detail
- When providing an invalid value like providing $234 instead of long value 234 in the request parameter id then OData exception is thrown which is not caught in the global exception handler.

**Comment by habbes** [comment]
Hi @gohilravi thank you for reporting this. Could you share more info about your implementation, and in particular, what you global exception handler looks like?

**Comment by gohilravi** [comment]
> Hi @gohilravi thank you for reporting this. Could you share more info about your implementation, and in particular, what you global exception handler looks like?

Hi @habbes it is a simple exception handler as suggested by the .NET core. Attached global exception handler registration logic and its logic with you.

<img width="889" alt="middleware" src="https://user-images.githubusercontent.com/34128405/151557115-1c75c16f-12a8-4544-b05b-1d5c69363d3a.png">

<img width="463" alt="Registration of middleware" src="https://user-images.githubusercontent.com/34128405/151557383-8c3c8144-c99d-4ca0-b1a7-2899bbb548b2.PNG">

**Comment by amkansara** [comment]
@habbes Did you get a chance to review the previous comment?

**Comment by timschwallie** [comment]
Any word on this? Seems to be a common issue, especially with folks that have QA testers that send in all kinds of data in testing.

**Comment by xubinzheng** [comment]
We are seeing the same issue in Microsoft.OData 8.0.10 NuGet package. Any updates on this? Looks like this is a common issue in the OData library.

**Comment by rcefalu10** [comment]
@habbes Do you have any update on this issue? It appears to be quite common. We are still seeing this issue as well. Do you have an estimate or update on a solution?

**Comment by nisarg-marutitechlabs** [comment]
@habbes Any update on this?

**Comment by velchev** [comment]
@gohilravi Any update on your issue? Did you manage to solve it?

**Comment by raginigunnam** [comment]
@habbes Any update on the issue. we are still facing the issue with Microsoft.OData 8.2.5 NuGet package in 2025.

@gohilravi @nisarg-marutitechlabs @xubinzheng does any one of you able to fix it or do you have any work around?
