### ISSUE TITLE
Microsoft.AspNet.OData version 7.5.12 and higher throwing ModelBinding.ModelError -- Value cannot be null.\r\nParameter name: nullableType

### ISSUE THREAD

**Issue by ImGonaRot** [OData/WebApi#2645]
Microsoft.AspNet.OData version 7.5.12 and higher

When I try to save to the OData service I am getting the following error that does not occur in Microsoft.AspNet.OData versions 7.5.11 or lower.

> System.Web.Http.ModelBinding.ModelError
> 
> Value cannot be null.\r\nParameter name: nullableType
> 
>    at System.Nullable.GetUnderlyingType(Type nullableType)
>    at Microsoft.AspNet.OData.Formatter.EdmPrimitiveHelpers.ConvertPrimitiveValue(Object value, Type type)
>    at Microsoft.AspNet.OData.Formatter.Deserialization.DeserializationHelpers.SetDeclaredProperty(Object resource, EdmTypeKind propertyKind, String propertyName, Object propertyValue, IEdmProperty edmProperty, ODataDeserializerContext readContext)
>    at Microsoft.AspNet.OData.Formatter.Deserialization.DeserializationHelpers.ApplyProperty(ODataProperty property, IEdmStructuredTypeReference resourceType, Object resource, ODataDeserializerProvider deserializerProvider, ODataDeserializerContext readContext)
>    at Microsoft.AspNet.OData.Formatter.Deserialization.ODataResourceDeserializer.ApplyStructuralProperties(Object resource, ODataResourceWrapper resourceWrapper, IEdmStructuredTypeReference structuredType, ODataDeserializerContext readContext)
>    at Microsoft.AspNet.OData.Formatter.Deserialization.ODataResourceDeserializer.ApplyResourceProperties(Object resource, ODataResourceWrapper resourceWrapper, IEdmStructuredTypeReference structuredType, ODataDeserializerContext readContext)
>    at Microsoft.AspNet.OData.Formatter.Deserialization.ODataResourceDeserializer.ReadResource(ODataResourceWrapper resourceWrapper, IEdmStructuredTypeReference structuredType, ODataDeserializerContext readContext)
>    at Microsoft.AspNet.OData.Formatter.ODataInputFormatterHelper.ReadFromStream(Type type, Object defaultValue, IEdmModel model, ODataVersion version, Uri baseAddress, IWebApiRequestMessage internalRequest, Func`1 getODataRequestMessage, Func`2 getEdmTypeDeserializer, Func`2 getODataPayloadDeserializer, Func`1 getODataDeserializerContext, Action`1 registerForDisposeAction, Action`1 logErrorAction)

This is happening on several models and all the models are valid.
It sets ModelState.IsValid to false on the HttpActionContext and throws the error.

```c#
    public class TestActionFilterAttribute : ActionFilterAttribute
    {
        public override void OnActionExecuting(HttpActionContext actionContext)
        {
            if (actionContext.ModelState.IsValid == false)
            {
                // get the model validation errors
                StringBuilder errorMessage = new StringBuilder();
                //foreach (KeyValuePair<string, System.Web.Http.ModelBinding.ModelState> keyValue in actionContext.ModelState)
                //{
                //    foreach (System.Web.Http.ModelBinding.ModelError error in keyValue.Value.Errors)
                //    {
                //        errorMessage.AppendLine(error.ErrorMessage);
                //    }
                //}
                foreach (var modelState in actionContext.ModelState)
                {
                    foreach (var modelError in modelState.Value.Errors)
                    {
                        // some models don't have error messages and instead you have to look at the Exception for the message
                        errorMessage.AppendLine((string.IsNullOrEmpty(modelError.ErrorMessage) ? modelError.Exception?.Message : modelError.ErrorMessage));
                    }
                }

                // build odata error to send to client
                ODataError oDataError = new ODataError();
                oDataError.ErrorCode = "Validation";
                oDataError.Message = errorMessage.ToString();

                // create error response
                actionContext.Response = actionContext.Request.CreateErrorResponse(HttpStatusCode.BadRequest, "Validation Error");
                // set the content to validation error
                actionContext.Response.Content = new StringContent(JsonConvert.SerializeObject(oDataError));
            }
        }
    }
```

**Comment by corranrogue9** [comment]
Can you please provide a model that produces this error? Also, if you have the value of `errorMessage` in your code snippet, that would be helpful

**Comment by ImGonaRot** [comment]
The message listed above was "modelError.Exception.ToString".
Here it is again from the Immediate Window.
This is all it gives me and there is no inner exception.
```
?modelError.Exception.ToString()

"System.ArgumentNullException: Value cannot be null.\r\nParameter name: nullableType\r\n   
at System.Nullable.GetUnderlyingType(Type nullableType)\r\n   
at Microsoft.AspNet.OData.Formatter.EdmPrimitiveHelpers.ConvertPrimitiveValue(Object value, Type type)\r\n   
at Microsoft.AspNet.OData.Formatter.Deserialization.DeserializationHelpers.SetDeclaredProperty(Object resource, EdmTypeKind propertyKind, String propertyName, Object propertyValue, IEdmProperty edmProperty, ODataDeserializerContext readContext)   
at Microsoft.AspNet.OData.Formatter.Deserialization.DeserializationHelpers.ApplyProperty(ODataProperty property, IEdmStructuredTypeReference resourceType, Object resource, ODataDeserializerProvider deserializerProvider, ODataDeserializerContext readContext)   
at Microsoft.AspNet.OData.Formatter.Deserialization.ODataResourceDeserializer.ApplyStructuralProperties(Object resource, ODataResourceWrapper resourceWrapper, IEdmStructuredTypeReference structuredType, ODataDeserializerContext readContext)   
at Microsoft.AspNet.OData.Formatter.Deserialization.ODataResourceDeserializer.ApplyResourceProperties(Object resource, ODataResourceWrapper resourceWrapper, IEdmStructuredTypeReference structuredType, ODataDeserializerContext readContext)   
at Microsoft.AspNet.OData.Formatter.Deserialization.ODataResourceDeserializer.ReadResource(ODataResourceWrapper resourceWrapper, IEdmStructuredTypeReference structuredType, ODataDeserializerContext readContext)   
at Microsoft.AspNet.OData.Formatter.ODataInputFormatterHelper.ReadFromStream(Type type, Object defaultValue, IEdmModel model, ODataVersion version, Uri baseAddress, IWebApiRequestMessage internalRequest, Func`1 getODataRequestMessage, Func`2 getEdmTypeDeserializer, Func`2 getODataPayloadDeserializer, Func`1 getODataDeserializerContext, Action`1 registerForDisposeAction, Action`1 logErrorAction)"
```

Here is one of the models that has been working since OData V3 with last change in our source control dated 5/10/2017.
Several models seem to be broken when using 7.5.12 but not all of them.
When I use 7.5.11 this model is working fine but when I update to 7.5.12 it throws the error listed above.

```c#
[Table("tbTestSetting", Schema = "test")]
public partial class TestSetting
{
    [Key]
    [Column("fdTestSettingID")]
    public long TestSettingID { get; set; }

    [Required]
    [Column("fdTestID")]
    public long TestID { get; set; }

    [Required]
    [StringLength(255)]
    [Column("fdKey")]
    public string Key { get; set; }

    [Required]
    [Column("fdValue")]
    public string Value { get; set; }

    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    [Column("fdCreateDate")]
    public DateTime CreateDate { get; set; }

    public DateTime? fdUpdateDate { get; set; }

    [NotMapped]
    public DateTime? UpdateDate
    {
        get
        {
            return fdUpdateDate;
        }
        set
        {
            fdUpdateDate = (CreateDate == default(DateTime) ? default(DateTime?) : DateTime.Now);
        }
    }
}
```

Here is the RAW HTTP from fiddler
```
PATCH https://test.com/TestService/odata/TestSettings(1) HTTP/1.1
OData-Version: 4.0
OData-MaxVersion: 4.0
Content-Type: application/json;odata.metadata=minimal
Accept: application/json;odata.metadata=minimal
Accept-Charset: UTF-8
User-Agent: Microsoft.OData.Client/7.11.0
Prefer: odata.include-annotations="*"
Host: test.com
Content-Length: 270
Expect: 100-continue
Accept-Encoding: gzip, deflate

{"@odata.type":"#TestService.Models.UserSetting",
"CreateDate":"2017-12-03T10:29:04.77-05:00",
"fdUpdateDate":"2022-05-10T15:24:35.153-04:00",
"Key":"SomeTestID",
"UpdateDate":"2022-05-10T15:24:35.153-04:00",
"TestID":1234,
"TestSettingID":1,
"Value":"1"}
```

I have added break points to the Patch method but it does not get called. 
Instead the TestActionFilterAttribute.OnActionExecuting gets called immediately and the HttpActionContext.ModelState.IsValid is false.
Here is the method signature for Patch.
```c#
[AcceptVerbs("PATCH", "MERGE")]
public virtual async Task<IHttpActionResult> Patch([FromODataUri] int key, Delta<TEntity> patch, ODataQueryOptions<TEntity> options)
```

If I revert back to 7.5.11 and "reissue" the same fiddler Patch request it works fine.
I have tried both 7.5.12 and 7.5.14 but both have the same problem.
I have also compared the metadata between 7.5.11 and 7.5.12 and both are identical.

Something I noticed odd in fiddler is that on 7.5.11 the RAW http response for the Patch is 204 No Content and even though it works, it does not return back the "patched" json.
Although that might be normal and I have never noticed until now.

**Comment by corranrogue9** [comment]
@ImGonaRot, I see some things in the offending commit that I don't like, but I've been unable to reproduce this issue. Are you able to provide a small repro? As in, model + request? The above classes I'm not able to repro with, I'm guessing because some other part of the model is actually causing the bug in our `PATCH` code to surface.

**Comment by corranrogue9** [comment]
I'm going to close this issue, if you can help me repro please open the issue back up and we will take another look.
