### ISSUE TITLE
ArgumentNullException on all POST requests to OData controllers with [EnableQuery] attribute. Microsoft.AspNet.OData 7.7.0

### ISSUE THREAD

**Issue by agarayev** [OData/WebApi#2794]
https://github.com/OData/WebApi/blob/8c03a9077020859096a65a49bcc6e6e68429ab98/src/Microsoft.AspNet.OData/EnableQueryAttribute.cs#L90

Hi. We are getting an ArgumentNullException on all POST requests which have [EnableQuery] attribute enabled when not supplying any query parameters. Example: POST to /myODataService. Removing [EnableQuery] attribute fixes the issue.

"Value cannot be null.\r\nParameter name: type"

at Microsoft.OData.Edm.EdmUtil.CheckArgumentNull[T](T value, String parameterName)
   at Microsoft.OData.Edm.ExtensionMethods.NavigationProperties(IEdmStructuredType type)
   at Microsoft.AspNet.OData.Query.ExpandQueryBuilder.GenerateExpandQueryStringInternal(Object value, IEdmModel model, Boolean isNestedExpand)
   at Microsoft.AspNet.OData.EnableQueryAttribute.GenerateExpandQueryFromPayload(HttpActionContext context)
   at Microsoft.AspNet.OData.EnableQueryAttribute.OnActionExecuted(HttpActionExecutedContext actionExecutedContext)
   at System.Web.Http.Filters.ActionFilterAttribute.OnActionExecutedAsync(HttpActionExecutedContext actionExecutedContext, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.AuthenticationFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()

**Comment by KenitoInc** [comment]
Related #2787

**Comment by KenitoInc** [comment]
This issue is caused when we try to call extension method `edmStructuredType.NavigationProperties();` when `edmStructuredType` is `null`.
 https://github.com/OData/WebApi/blob/8c03a9077020859096a65a49bcc6e6e68429ab98/src/Microsoft.AspNet.OData.Shared/Query/ExpandQueryBuilder.cs#L56
