### ISSUE TITLE
ODataConventionModelBuilder GetEdmModel() System.Data.Linq FileNotFoundException

### ISSUE THREAD

**Issue by robertgro** [OData/WebApi#2812]
*Receiving an FileNotFoundException when using ODataConventionModelBuilder.GetEdmModel()*

### Assemblies affected

System.Web.Http.OData.Formatter.EdmLibHelpers

### Reproduce steps

1. Have a sample class
2. Try to build a model

```
ODataConventionModelBuilder modelBuilder = new ODataConventionModelBuilder();
modelBuilder.EntitySet<MySampleClass>("MySampleClass");
IEdmModel model = (IEdmModel)modelBuilder.GetEdmModel();
```

without the cast you'll receive a:

```
Error	CS0266	Cannot implicitly convert type 'Microsoft.Data.Edm.IEdmModel' to 'Microsoft.OData.Edm.IEdmModel'. An explicit conversion exists (are you missing a cast?)
```

### Expected result

_No exception_

### Actual result

System.TypeInitializationException

  HResult=0x80131534

  Message=The type initializer for 'System.Web.Http.OData.Formatter.EdmLibHelpers' threw an exception.

  Source=System.Web.Http.OData

  StackTrace:
   at System.Web.Http.OData.Formatter.EdmLibHelpers.GetEdmPrimitiveTypeOrNull(Type clrType)
   at System.Web.Http.OData.Builder.ODataConventionModelBuilder.GetPropertyType(PropertyInfo property, Boolean& isCollection, StructuralTypeConfiguration& mappedType)
   at System.Web.Http.OData.Builder.ODataConventionModelBuilder.MapEntityType(EntityTypeConfiguration entity)
   at System.Web.Http.OData.Builder.ODataConventionModelBuilder.MapType(StructuralTypeConfiguration edmType)
   at System.Web.Http.OData.Builder.ODataConventionModelBuilder.MapTypes()
   at System.Web.Http.OData.Builder.ODataConventionModelBuilder.GetEdmModel()
   at MyExampleProject.Objects.MyODataContainer.LoadEdmModel() in C:\Users\my.username\source\repos\MyExampleProject2\MyExampleProject.Objects\MyODataContainer.cs:line 36
   at Microsoft.OData.Client.DataServiceClientFormat.get_ServiceModel()
   at Microsoft.OData.Client.DataServiceClientFormat.UseJson()
   at MyExampleProject.Objects.MyODataContainer..ctor(Uri serviceRoot) in C:\Users\my.username\source\repos\MyExampleProject2\MyExampleProject.Objects\MyODataContainer.cs:line 20
   at Program.<>c__DisplayClass0_0.<<Main>$>b__2(IServiceProvider context) in C:\Users\my.username\source\repos\MyExampleProject2\MyExampleProject.Tests.DebugConsole\Program.cs:line 19
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Program.<<<Main>$>g__TestCustomerService|0_1>d.MoveNext() in C:\Users\my.username\source\repos\MyExampleProject2\MyExampleProject.Tests.Console\Program.cs:line 40
   at Program.<<Main>$>d__0.MoveNext() in C:\Users\my.username\source\repos\MyExampleProject2\MyExampleProject.Tests.DebugConsole\Program.cs:line 35

  This exception was originally thrown at this call stack:

Inner Exception 1:
FileNotFoundException: Could not load file or assembly 'System.Data.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

### Additional detail
_none_

**Comment by xuzhg** [comment]
@robertgro It seems your project has the OData v3 package and OData v4 package referenced together. Please remove the un-used on and do a clean-all/rebuild all. Thanks.

**Comment by robertgro** [comment]
@xuzhg Thank you. This resolved the issue. 

I installed the following packages to all projects in the solution:
- **Microsoft.AspNetCore.OData** (latest stable 8.2.3)
- **Microsoft.OData.Client** (latest stable 7.18.0)

and now it's working even without a cast. 😇
