### ISSUE TITLE
Group by a property of a derived type is not supported

### ISSUE THREAD

**Issue by clemvnt** [OData/WebApi#2834]
Hello,

I have a case where I want to group by a property of a derived type :
```
/products?apply=groupby((category/ODataGroupByDerivedTypeIssue.Models.Category/categoryName)) 
```

An error indicating that this is not supported is thrown.

I would have expected it to be possible. Is it a lack or are there reasons why it's not possible?

Using a derived type in a filter clause works :
```
/products?filter=category/ODataGroupByDerivedTypeIssue.Models.Category/CategoryName eq 'Category 1'
```

### Assemblies affected

Microsoft.AspNetCore.OData 8.2.4

### Reproduce steps

1. Clone the repository : https://github.com/clemvnt/ODataGroupByDerivedTypeIssue
2. Run

It should open the `/products?apply=groupby((category/ODataGroupByDerivedTypeIssue.Models.Category/categoryName))` URL.

### Expected result

```json
[
    { "category": { "categoryName": "Category 1" } },
    { "category": { "categoryName": "Category 2" } }
]
```

### Actual result

The following error : 
```
System.NotSupportedException: The query specified in the URI is not valid. Binding OData QueryNode of kind 'SingleResourceCast' is not supported by 'AggregationBinder'.
```

Stack trace :
```
at Microsoft.AspNetCore.OData.Query.Expressions.TransformationBinderBase.BindAccessor(QueryNode node, Expression baseElement)
at Microsoft.AspNetCore.OData.Query.Expressions.TransformationBinderBase.BindAccessor(QueryNode node, Expression baseElement)
at Microsoft.AspNetCore.OData.Query.Expressions.AggregationBinder.CreateGroupByMemberAssignments(IEnumerable`1 nodes)
at Microsoft.AspNetCore.OData.Query.Expressions.AggregationBinder.BindGroupBy(IQueryable query)
at Microsoft.AspNetCore.OData.Query.Expressions.AggregationBinder.Bind(IQueryable query)
at Microsoft.AspNetCore.OData.Query.ApplyQueryOption.ApplyTo(IQueryable query, ODataQuerySettings querySettings)
at Microsoft.AspNetCore.OData.Query.ODataQueryOptions.ApplyTo(IQueryable query, ODataQuerySettings querySettings)
at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.ApplyQuery(IQueryable queryable, ODataQueryOptions queryOptions)
at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.ExecuteQuery(Object responseValue, IQueryable singleResultCollection, ControllerActionDescriptor actionDescriptor, HttpRequest request)
at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.OnActionExecuted(ActionExecutedContext actionExecutedContext, Object responseValue, IQueryable singleResultCollection, ControllerActionDescriptor actionDescriptor, HttpRequest request)
```

**Comment by clemvnt** [comment]
Oops, wrong repo! 😬
