### ISSUE TITLE
Model validation error for nested entity with non-nullable property is missing error message.

### ISSUE THREAD

**Issue by thebothead** [OData/WebApi#288]
I have a model defined where an entity has a collection of a complex type.  The complex type has two properties, one is a string name and the other is a string value.  The string name is non-nullable per the metadata.

When I post a new entity with the collection of complex type to create with the new entity, and set the name to null for the complex type in the collection...

{
"Name" : "MyEvent",
"SourceTimezone" : "Etc/GMT",
"Attributes" : [ {
                                    "Name" : null,
                                    "Value" : "ValidValue"
                                }]
}

I get back the following error message:

{
  "error":{
    "code":"","message":"The request is invalid.","innererror":{
      "message":"entity : An error has occurred.\r\n","type":"","stacktrace":""
    }
  }
}

I believe this is occurring because there is no ErrorMessage present on the HttpError, only an Exception that is thrown.

Note that I am using a filter for model validation as follows:
            if (!actionContext.ModelState.IsValid)
            {
                actionContext.Response = actionContext.Request.CreateErrorResponse(
                    HttpStatusCode.BadRequest,
                    actionContext.ModelState);
            }

I would expect to see the following error message:
{
  "error":{
    "code":"","message":"The request is invalid.","innererror":{
      "message":"entity.Attributes[0].Name : The Name field is required.\r\n","type":"","stacktrace":""
    }
  }
}

Stacktrace:
   at Microsoft.OData.Core.ReaderValidationUtils.ThrowNullValueForNonNullableTypeException(IEdmTypeReference expectedValueTypeReference, String propertyName) in c:\Users\Documents\OI Documents\Code\AggregationVSO\Microsoft.OData\src\OData\Microsoft\OData\Core\ReaderValidationUtils.cs:line 1265
   at Microsoft.OData.Core.ReaderValidationUtils.ValidateNullValueAllowed(IEdmTypeReference expectedValueTypeReference, Boolean validateNullValue, IEdmModel model, String propertyName) in c:\Users\Documents\OI Documents\Code\AggregationVSO\Microsoft.OData\src\OData\Microsoft\OData\Core\ReaderValidationUtils.cs:line 1225
   at Microsoft.OData.Core.ReaderValidationUtils.ValidateNullValue(IEdmModel model, IEdmTypeReference expectedTypeReference, ODataMessageReaderSettings messageReaderSettings, Boolean validateNullValue, ODataVersion version, String propertyName) in c:\Users\Documents\OI Documents\Code\AggregationVSO\Microsoft.OData\src\OData\Microsoft\OData\Core\ReaderValidationUtils.cs:line 119
   at Microsoft.OData.Core.Json.ODataJsonReaderCoreUtils.TryReadNullValue(BufferingJsonReader jsonReader, ODataInputContext inputContext, IEdmTypeReference expectedTypeReference, Boolean validateNullValue, String propertyName) in c:\Users\Documents\OI Documents\Code\AggregationVSO\Microsoft.OData\src\OData\Microsoft\OData\Core\Json\ODataJsonReaderCoreUtils.cs:line 122
   at Microsoft.OData.Core.JsonLight.ODataJsonLightPropertyAndValueDeserializer.ReadNonEntityValueImplementation(String payloadTypeName, IEdmTypeReference expectedTypeReference, DuplicatePropertyNamesChecker duplicatePropertyNamesChecker, CollectionWithoutExpectedTypeValidator collectionValidator, Boolean validateNullValue, Boolean isTopLevelPropertyValue, Boolean insideComplexValue, String propertyName) in c:\Users\Documents\OI Documents\Code\AggregationVSO\Microsoft.OData\src\OData\Microsoft\OData\Core\JsonLight\ODataJsonLightPropertyAndValueDeserializer.cs:line 897
   at Microsoft.OData.Core.JsonLight.ODataJsonLightPropertyAndValueDeserializer.ReadNonEntityValue(String payloadTypeName, IEdmTypeReference expectedValueTypeReference, DuplicatePropertyNamesChecker duplicatePropertyNamesChecker, CollectionWithoutExpectedTypeValidator collectionValidator, Boolean validateNullValue, Boolean isTopLevelPropertyValue, Boolean insideComplexValue, String propertyName) in c:\Users\Documents\OI Documents\Code\AggregationVSO\Microsoft.OData\src\OData\Microsoft\OData\Core\JsonLight\ODataJsonLightPropertyAndValueDeserializer.cs:line 151
   at Microsoft.OData.Core.JsonLight.ODataJsonLightEntryAndFeedDeserializer.ReadEntryDataProperty(IODataJsonLightReaderEntryState entryState, IEdmProperty edmProperty, String propertyTypeName) in c:\Users\Documents\OI Documents\Code\AggregationVSO\Microsoft.OData\src\OData\Microsoft\OData\Core\JsonLight\ODataJsonLightEntryAndFeedDeserializer.cs:line 1235
   at Microsoft.OData.Core.JsonLight.ODataJsonLightEntryAndFeedDeserializer.ReadEntryPropertyWithValue(IODataJsonLightReaderEntryState entryState, String propertyName) in c:\Users\Documents\OI Documents\Code\AggregationVSO\Microsoft.OData\src\OData\Microsoft\OData\Core\JsonLight\ODataJsonLightEntryAndFeedDeserializer.cs:line 1200
   at Microsoft.OData.Core.JsonLight.ODataJsonLightEntryAndFeedDeserializer.<>c__DisplayClass2.<ReadEntryContent>b__0(PropertyParsingResult propertyParsingResult, String propertyName) in c:\Users\Documents\OI Documents\Code\AggregationVSO\Microsoft.OData\src\OData\Microsoft\OData\Core\JsonLight\ODataJsonLightEntryAndFeedDeserializer.cs:line 170
   at Microsoft.OData.Core.JsonLight.ODataJsonLightDeserializer.ProcessProperty(DuplicatePropertyNamesChecker duplicatePropertyNamesChecker, Func`2 readPropertyAnnotationValue, Action`2 handleProperty) in c:\Users\Documents\OI Documents\Code\AggregationVSO\Microsoft.OData\src\OData\Microsoft\OData\Core\JsonLight\ODataJsonLightDeserializer.cs:line 489
   at Microsoft.OData.Core.JsonLight.ODataJsonLightEntryAndFeedDeserializer.ReadEntryContent(IODataJsonLightReaderEntryState entryState) in c:\Users\Documents\OI Documents\Code\AggregationVSO\Microsoft.OData\src\OData\Microsoft\OData\Core\JsonLight\ODataJsonLightEntryAndFeedDeserializer.cs:line 182
   at Microsoft.OData.Core.JsonLight.ODataJsonLightReader.ReadEntryStart(DuplicatePropertyNamesChecker duplicatePropertyNamesChecker, SelectedPropertiesNode selectedProperties) in c:\Users\Documents\OI Documents\Code\AggregationVSO\Microsoft.OData\src\OData\Microsoft\OData\Core\JsonLight\ODataJsonLightReader.cs:line 1033
   at Microsoft.OData.Core.JsonLight.ODataJsonLightReader.ReadAtFeedStartImplementationSynchronously() in c:\Users\Documents\OI Documents\Code\AggregationVSO\Microsoft.OData\src\OData\Microsoft\OData\Core\JsonLight\ODataJsonLightReader.cs:line 509
   at Microsoft.OData.Core.JsonLight.ODataJsonLightReader.ReadAtFeedStartImplementation() in c:\Users\Documents\OI Documents\Code\AggregationVSO\Microsoft.OData\src\OData\Microsoft\OData\Core\JsonLight\ODataJsonLightReader.cs:line 179
   at Microsoft.OData.Core.ODataReaderCore.ReadImplementation() in c:\Users\Documents\OI Documents\Code\AggregationVSO\Microsoft.OData\src\OData\Microsoft\OData\Core\ODataReaderCore.cs:line 555
   at Microsoft.OData.Core.ODataReaderCore.ReadSynchronously() in c:\Users\Documents\OI Documents\Code\AggregationVSO\Microsoft.OData\src\OData\Microsoft\OData\Core\ODataReaderCore.cs:line 500
   at Microsoft.OData.Core.ODataReaderCore.InterceptException[T](Func`1 action) in c:\Users\Documents\OI Documents\Code\AggregationVSO\Microsoft.OData\src\OData\Microsoft\OData\Core\ODataReaderCore.cs:line 624
   at Microsoft.OData.Core.ODataReaderCore.Read() in c:\Users\Documents\OI Documents\Code\AggregationVSO\Microsoft.OData\src\OData\Microsoft\OData\Core\ODataReaderCore.cs:line 315
   at System.Web.OData.Formatter.Deserialization.ODataEntityDeserializer.ReadEntryOrFeed(ODataReader reader) in c:\Users\Documents\OI Documents\Code\Aggregation.AspNetWebStack\AspNetWebStack\OData\src\System.Web.OData\OData\Formatter\Deserialization\ODataEntityDeserializer.cs:line 361
   at System.Web.OData.Formatter.Deserialization.ODataEntityDeserializer.Read(ODataMessageReader messageReader, Type type, ODataDeserializerContext readContext) in c:\Users\Documents\OI Documents\Code\Aggregation.AspNetWebStack\AspNetWebStack\OData\src\System.Web.OData\OData\Formatter\Deserialization\ODataEntityDeserializer.cs:line 66
   at System.Web.OData.Formatter.ODataMediaTypeFormatter.ReadFromStream(Type type, Stream readStream, HttpContent content, IFormatterLogger formatterLogger) in c:\Users\Documents\OI Documents\Code\Aggregation.AspNetWebStack\AspNetWebStack\OData\src\System.Web.OData\OData\Formatter\ODataMediaTypeFormatter.cs:line 412

**Comment by habbes** [comment]
Closing this issue due to inactivity. If this still affects the latest versions of the library, kindly open a new issue.
