### ISSUE TITLE
Cant't $filter or $oderby on Open complex type

### ISSUE THREAD

**Issue by ricksearcy** [OData/WebApi#315]
Using the sample entity below. Project is an open type where we have stored a Relation type as the Value. Key = "Project", Value = The Relation object. 

If you then try to $filter or $order by the open complex type, such as $orderby = Project/Title or $filter = Project/Title you get the exception below. 
Object
{
            "ParentListId": "53bc8adf-fa0b-4968-a340-a04946ff5b38",
            "Title": "script generated 140",
            "Description": "",
            "Project":
            {
                "@odata.type": "#Cloud.Web.Models.Relation",
                "Id": "1cc84d44-010b-40b3-9a02-5436a79eb36a",
                "ItemId": "89d2fd59-06e2-47d2-9f59-d95634fd8895",
                "Title": "two"
            },
            "Priority": "Normal"
        }

Exception
"innererror":
        {
            "message": "Value cannot be null.
Parameter name: type",
            "type": "System.ArgumentNullException",
            "stacktrace": "   at Microsoft.OData.Edm.EdmUtil.CheckArgumentNull[T](T value, String parameterName)
   at Microsoft.OData.Edm.EdmTypeSemantics.IsEntity(IEdmTypeReference type)
   at System.Web.OData.Query.Expressions.FilterBinder.GetDynamicPropertyContainer(SingleValueOpenPropertyAccessNode openNode)
   at System.Web.OData.Query.Expressions.FilterBinder.BindDynamicPropertyAccessQueryNode(SingleValueOpenPropertyAccessNode openNode)
   at System.Web.OData.Query.Expressions.FilterBinder.Bind(QueryNode node)
   at System.Web.OData.Query.Expressions.FilterBinder.BindExpression(SingleValueNode expression, RangeVariable rangeVariable, Type elementType)
   at System.Web.OData.Query.Expressions.FilterBinder.Bind(OrderByClause orderBy, Type elementType, IEdmModel model, ODataQuerySettings querySettings)
   at System.Web.OData.Query.OrderByQueryOption.AddOrderByQueryForProperty(IQueryable query, ODataQuerySettings querySettings, OrderByClause orderbyClause, IQueryable querySoFar, OrderByDirection direction, Boolean alreadyOrdered)
   at System.Web.OData.Query.OrderByQueryOption.ApplyToCore(IQueryable query, ODataQuerySettings querySettings)
   at System.Web.OData.Query.OrderByQueryOption.ApplyTo(IQueryable query, ODataQuerySettings querySettings)
   at System.Web.OData.Query.ODataQueryOptions.ApplyTo(IQueryable query, ODataQuerySettings querySettings)
   at System.Web.OData.Query.ODataQueryOptions`1.ApplyTo(IQueryable query, ODataQuerySettings querySettings)
   at System.Web.OData.Query.ODataQueryOptions.ApplyTo(IQueryable query)
   at System.Web.OData.Query.ODataQueryOptions`1.ApplyTo(IQueryable query)
   at CorasWorks.Cloud.Web.Repositories.ListItemRepositoryMongo.GetByParentId(String Id, ODataQueryOptions queryOptions) in c:\CorasCloud\CorasCloud\CorasCloudWeb\Repositories\ListItemRepositoryMongo.cs:line 56
   at CorasWorks.Cloud.Web.Controllers.ListsController.GetListItems(String key, ODataQueryOptions`1 queryOptions) in c:\CorasCloud\CorasCloud\CorasCloudWeb\Controllers\ListsController.cs:line 49
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ApiControllerActionInvoker.d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Filters.ActionFilterAttribute.d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Filters.ActionFilterAttribute.d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ActionFilterResult.d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.d__1.MoveNext()"
        }

**Comment by daboxu** [comment]
any updates on this?

**Comment by daboxu** [comment]
after investigation I found this bug is caused by the case:
[OpenType] Item (having a dictionary <string,object> dictionary, and in the dictionary, there is a dictionary object <string, object>, let's say 'openDictionary')-> [OpenProperty] 'openDictionary' -> [OpenProperty] property_a

in Odata model express AST model

`SingleValueOpenPropertyAccessNode` property_a.Source is `SingleValueOpenPropertyAccessNode` openDictionary 

which when [FilterBinder checks the source type](https://github.com/OData/WebApi/blob/master/OData/src/System.Web.OData/OData/Query/Expressions/FilterBinder.cs#L205), it failed because the source type is still `SingleValueOpenPropertyAccessNode`, which returns null: https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/UriParser/SemanticAst/SingleValueOpenPropertyAccessNode.cs#L65

so the current workaround for me is reconstructing the model to:
[OpenType] Item (having a dictionary <string,object> dictionary -> [OpenProperty] openDictionary_property and hacks on the filter clause for the incoming request and remove this property before serialization.

**Comment by ersandgamp** [comment]
> @daboxu 
> so the current workaround for me is reconstructing the model to:
[OpenType] Item (having a dictionary <string,object> dictionary -> [OpenProperty] openDictionary_property and hacks on the filter clause for the incoming request and remove this property before serialization.



Can you show me an example how to reconstruct the model to make the filter work on the open complex type?

**Comment by habbes** [comment]
Closing this issue due to inactivity. If this still affects the latest versions of the library, kindly open a new issue.
