### ISSUE TITLE
The edm.Date type doesn't work in Microsoft.AspNet.OData.5.6.0-beta1-150428-Nightly if Declared as Nullable

### ISSUE THREAD

**Issue by jonjalberghini** [OData/WebApi#347]
The edm.Date type doesn't work in Microsoft.AspNet.OData.5.6.0-beta1-150428-Nightly if Declared as Nullable. The EF doesn't seem to understand what it is and says field not declared.

**Comment by xuzhg** [comment]
Hi, @jonjalberghini 

Would you please give us more detail about your model? the usage scenario and the error message you got?

Edm.Date & Edm.TimeOfDay are new Primitive types, and the related CLR types are defined in ODL. the CLR types are structs as [Date](https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Edm/Library/Date.cs) and [TimeOfDay](https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Edm/Library/TimeOfDay.cs). EF can't know these structs at all.

Thanks.

**Comment by jonjalberghini** [comment]
I am not sure I understand. See below sample. 
I have a date field in the database, I want odata to think it is a date field because it keeps rolling it back a day because the server is UTC and the client is one hour behind. I am not even sure how odata know the client timezone but it does I tested setting my time zone 2hr back and it turned it into datetiime day before 22:00:00 when I use datetime for EF model. This is why I want a date. 
So how does the date field work with EF.

Say this EF model 

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Aas.Models.Base;
using Aas.Models.EFHelpers;
using Newtonsoft.Json;
using Microsoft.OData.Edm.Library;

namespace Aas.Models
{
    public partial class Activity
    {
		[Key]
		public int Id { get; set; }
		[Column(TypeName = "Date")]
		public Date IsComplete { get; set; }
    }
}

Exception
System.InvalidOperationException was unhandled by user code
  HResult=-2146233079
  Message=The property 'Occurred' is not a declared property on type 'Activity'. Verify that the property has not been explicitly excluded from the model by using the Ignore method or NotMappedAttribute data annotation. Make sure that it is a valid primitive property.
  Source=EntityFramework
  StackTrace:
       at System.Data.Entity.ModelConfiguration.Configuration.Types.StructuralTypeConfiguration.Configure(String structuralTypeName, IEnumerable`1 properties, IEnumerable`1 propertyPath, PrimitivePropertyConfiguration propertyConfiguration)
       at System.Data.Entity.ModelConfiguration.Configuration.Types.StructuralTypeConfiguration.Configure(String structuralTypeName, IEnumerable`1 properties, ICollection`1 dataModelAnnotations)
       at System.Data.Entity.ModelConfiguration.Configuration.Types.EntityTypeConfiguration.Configure(EntityType entityType, EdmModel model)
       at System.Data.Entity.ModelConfiguration.Configuration.ModelConfiguration.ConfigureEntities(EdmModel model)
       at System.Data.Entity.ModelConfiguration.Configuration.ModelConfiguration.Configure(EdmModel model)
       at System.Data.Entity.DbModelBuilder.Build(DbProviderManifest providerManifest, DbProviderInfo providerInfo)
       at System.Data.Entity.DbModelBuilder.Build(DbConnection providerConnection)
       at System.Data.Entity.Internal.LazyInternalContext.CreateModel(LazyInternalContext internalContext)
       at System.Data.Entity.Internal.RetryLazy`2.GetValue(TInput input)
       at System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
       at System.Data.Entity.Internal.InternalContext.Initialize()
       at System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
       at System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
       at System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext()
       at System.Data.Entity.Infrastructure.DbQuery`1.System.Linq.IQueryable.get_Provider()
       at System.Linq.Queryable.SingleOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
       at Aas.Helper.LoginHelper.GetDbUser(String Email) in c:\Development\investigation-advice-2\Aas\Helper\LoginHelper.cs:line 126
       at Aas.WebApiApplication.Session_Start(Object sender, EventArgs e) in c:\Development\investigation-advice-2\Aas\Global.asax.cs:line 88
       at System.Web.SessionState.SessionStateModule.RaiseOnStart(EventArgs e)
       at System.Web.SessionState.SessionStateModule.CompleteAcquireState()
       at System.Web.SessionState.SessionStateModule.BeginAcquireState(Object source, EventArgs e, AsyncCallback cb, Object extraData)
       at System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
  InnerException: 

.

**Comment by jonjalberghini** [comment]
Sorry didn't mean to close it.

**Comment by jonjalberghini** [comment]
I am not sure I understand. See below sample.
I have a date field in the database, I want odata to think it is a date field because it keeps rolling it back a day because the server is UTC and the client is one hour behind. I am not even sure how odata know the client timezone but it does I tested setting my time zone 2hr back and it turned it into datetiime day before 22:00:00 when I use datetime for EF model. This is why I want a date.
So how does the date field work with EF.

Say this EF model

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Aas.Models.Base;
using Aas.Models.EFHelpers;
using Newtonsoft.Json;
using Microsoft.OData.Edm.Library;

namespace Aas.Models
{
public partial class Activity
{
[Key]
public int Id { get; set; }
[Column(TypeName = "Date")]
public Date IsComplete { get; set; }
}
}

Exception
System.InvalidOperationException was unhandled by user code
HResult=-2146233079
Message=The property 'Occurred' is not a declared property on type 'Activity'. Verify that the property has not been explicitly excluded from the model by using the Ignore method or NotMappedAttribute data annotation. Make sure that it is a valid primitive property.
Source=EntityFramework
StackTrace:
at System.Data.Entity.ModelConfiguration.Configuration.Types.StructuralTypeConfiguration.Configure(String structuralTypeName, IEnumerable1 properties, IEnumerable1 propertyPath, PrimitivePropertyConfiguration propertyConfiguration)
at System.Data.Entity.ModelConfiguration.Configuration.Types.StructuralTypeConfiguration.Configure(String structuralTypeName, IEnumerable1 properties, ICollection1 dataModelAnnotations)
at System.Data.Entity.ModelConfiguration.Configuration.Types.EntityTypeConfiguration.Configure(EntityType entityType, EdmModel model)
at System.Data.Entity.ModelConfiguration.Configuration.ModelConfiguration.ConfigureEntities(EdmModel model)
at System.Data.Entity.ModelConfiguration.Configuration.ModelConfiguration.Configure(EdmModel model)
at System.Data.Entity.DbModelBuilder.Build(DbProviderManifest providerManifest, DbProviderInfo providerInfo)
at System.Data.Entity.DbModelBuilder.Build(DbConnection providerConnection)
at System.Data.Entity.Internal.LazyInternalContext.CreateModel(LazyInternalContext internalContext)
at System.Data.Entity.Internal.RetryLazy2.GetValue(TInput input) at System.Data.Entity.Internal.LazyInternalContext.InitializeContext() at System.Data.Entity.Internal.InternalContext.Initialize() at System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType) at System.Data.Entity.Internal.Linq.InternalSet1.Initialize()
at System.Data.Entity.Internal.Linq.InternalSet1.get_InternalContext() at System.Data.Entity.Infrastructure.DbQuery1.System.Linq.IQueryable.get_Provider()
at System.Linq.Queryable.SingleOrDefaultTSource
at Aas.Helper.LoginHelper.GetDbUser(String Email) in c:\Development\investigation-advice-2\Aas\Helper\LoginHelper.cs:line 126
at Aas.WebApiApplication.Session_Start(Object sender, EventArgs e) in c:\Development\investigation-advice-2\Aas\Global.asax.cs:line 88
at System.Web.SessionState.SessionStateModule.RaiseOnStart(EventArgs e)
at System.Web.SessionState.SessionStateModule.CompleteAcquireState()
at System.Web.SessionState.SessionStateModule.BeginAcquireState(Object source, EventArgs e, AsyncCallback cb, Object extraData)
at System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
InnerException:

**Comment by xuzhg** [comment]
@jonjalberghini 

In fact, EF doesn't know the "Date" type defined in ODL. It can't mapping <strong>IsComplete</strong> to any column in the DB. So, you can't do it.

You can change to use <strong>DateTime</strong> type, or mapping the column by yourself.

By the way, what is 'Occurred' property?

**Comment by xuzhg** [comment]
please re-open it if you have any further concern.
