### ISSUE TITLE
Providing $select on a contained navigation without the key when odata.metadata=full fails

### ISSUE THREAD

**Issue by ificator** [OData/WebApi#410]
GET http://foo.com/Roots('key')/Contained?$select=name
    Accept: application/json; odata.metadata=full
    {
      "error":{
        "code":"",
        "message":"An error has occurred.",
        "innererror":{
          "message":"The entity instance value of type 'OwinTest.ObjectModel.Contained' doesn't have a value for property 'Id'. To compute an entity's metadata, its key and concurrency-token property values must be provided.",
          "type":"Microsoft.OData.Core.ODataException",
          "stacktrace":"   at Microsoft.OData.Core.Evaluation.ODataEntryMetadataContext.ODataEntryMetadataContextWithModel.<get_KeyProperties>b__d(IEdmStructuralProperty p)
                           at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
                           at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
                           at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
                           at Microsoft.OData.Core.Evaluation.ODataEntryMetadataContext.ODataEntryMetadataContextWithModel.get_KeyProperties()
                           at Microsoft.OData.Core.Evaluation.ODataConventionalEntityMetadataBuilder.get_ComputedKeyProperties()
                           at Microsoft.OData.Core.Evaluation.ODataConventionalEntityMetadataBuilder.ComputeIdForContainment()
                           at Microsoft.OData.Core.Evaluation.ODataConventionalEntityMetadataBuilder.get_ComputedId()
                           at Microsoft.OData.Core.Evaluation.ODataConventionalEntityMetadataBuilder.TryGetIdForSerialization(Uri& id)
                           at Microsoft.OData.Core.JsonLight.ODataJsonLightEntryAndFeedSerializer.WriteEntryStartMetadataProperties(IODataJsonLightWriterEntryState entryState)
                           at Microsoft.OData.Core.JsonLight.ODataJsonLightWriter.StartEntry(ODataEntry entry)
                           at Microsoft.OData.Core.ODataWriterCore.InterceptException(Action action)
                           at System.Web.OData.Formatter.Serialization.ODataEntityTypeSerializer.WriteEntry(Object graph, ODataWriter writer, ODataSerializerContext writeContext)
                           at System.Web.OData.Formatter.Serialization.ODataFeedSerializer.WriteFeed(IEnumerable enumerable, IEdmTypeReference feedType, ODataWriter writer, ODataSerializerContext writeContext)
                           at System.Web.OData.Formatter.ODataMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, HttpContent content, HttpContentHeaders contentHeaders)
                           at System.Web.OData.Formatter.ODataMediaTypeFormatter.WriteToStreamAsync(Type type, Object value, Stream writeStream, HttpContent content, TransportContext transportContext, CancellationToken cancellationToken)
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at System.Web.Http.Owin.HttpMessageHandlerAdapter.<BufferResponseContentAsync>d__13.MoveNext()"
        }
      }
    }

The action for "GetItems" is returning objects that have ALL the data set on it, including `id` but it appears as though the ODataQueryOptions is filtering it out before serialization code is running that requires it. This does NOT repro when hitting http://foo.com/Roots?select=name

**Comment by xuzhg** [comment]
Can't repo it. So close it and Please file an issue with your repo if you have further concern. Thanks.
