### ISSUE TITLE
Support $expand=*

### ISSUE THREAD

**Issue by congysu** [OData/WebApi#463]
``` json
{
    "error": {
        "code": "",
        "message": "The query specified in the URI is not valid. Could not find a property named '*' on type 'WebApplication1.Models.Customer'.",
        "innererror": {
            "message": "Could not find a property named '*' on type 'WebApplication1.Models.Customer'.",
            "type": "Microsoft.OData.Core.ODataException",
            "stacktrace": "   at Microsoft.OData.Core.UriParser.Parsers.SelectExpandBinder.GenerateExpandItem(ExpandTermToken tokenIn)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Microsoft.OData.Core.UriParser.Parsers.SelectExpandBinder.Bind(ExpandToken tokenIn)
   at Microsoft.OData.Core.UriParser.Parsers.SelectExpandSemanticBinder.Bind(IEdmStructuredType elementType, IEdmNavigationSource navigationSource, ExpandToken expandToken, SelectToken selectToken, ODataUriParserConfiguration configuration)
   at Microsoft.OData.Core.UriParser.ODataQueryOptionParser.ParseSelectAndExpandImplementation(String select, String expand, ODataUriParserConfiguration configuration, IEdmStructuredType elementType, IEdmNavigationSource navigationSource)
   at Microsoft.OData.Core.UriParser.ODataQueryOptionParser.ParseSelectAndExpand()
   at System.Web.OData.Query.Validators.SelectExpandQueryValidator.Validate(SelectExpandQueryOption selectExpandQueryOption, ODataValidationSettings validationSettings)
   at System.Web.OData.Query.SelectExpandQueryOption.Validate(ODataValidationSettings validationSettings)
   at System.Web.OData.Query.Validators.ODataQueryValidator.Validate(ODataQueryOptions options, ODataValidationSettings validationSettings)
   at System.Web.OData.Query.ODataQueryOptions.Validate(ODataValidationSettings validationSettings)
   at System.Web.OData.EnableQueryAttribute.ValidateQuery(HttpRequestMessage request, ODataQueryOptions queryOptions)
   at System.Web.OData.EnableQueryAttribute.ExecuteQuery(Object response, HttpRequestMessage request, HttpActionDescriptor actionDescriptor)
   at System.Web.OData.EnableQueryAttribute.OnActionExecuted(HttpActionExecutedContext actionExecutedContext)"
        }
    }
}
```

Related spec:
It is also possible to expand all declared and dynamic navigation properties using a star (*)
http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part2-url-conventions/odata-v4.0-errata02-os-part2-url-conventions-complete.html#_Toc406398162

**Comment by congysu** [comment]
Pending ODataLIb.

**Comment by xuzhg** [comment]
ODL has supported, see https://github.com/OData/odata.net/pull/446/commits/fb4cbdc745f2764b004c01dbccb8965e0d214d3b, let do investigate in Web API.
