### ISSUE TITLE
xUnit runner extension to nuget

### ISSUE THREAD

**Issue by congysu** [OData/WebApi#479]
The runner extension won't install, and it not supported.  Shall change to nuget runner.

```
8/15/2015 6:52:31 PM - Microsoft VSIX Installer
8/15/2015 6:52:31 PM - -------------------------------------------
8/15/2015 6:52:31 PM - Initializing Install...
8/15/2015 6:52:31 PM - Extension Details...
8/15/2015 6:52:31 PM - 	Identifier      : xunit.runner.visualstudio.Microsoft.623f78dd-6d4b-48f3-a2c7-4bbb381bb146
8/15/2015 6:52:31 PM - 	Name            : xUnit.net runner for Visual Studio
8/15/2015 6:52:31 PM - 	Author          : Outercurve Foundation
8/15/2015 6:52:31 PM - 	Version         : 0.99.9
8/15/2015 6:52:31 PM - 	Description     : NO LONGER NEEDED. Please un-install this extension. See http://xunit.github.io/docs/vsix-deprecated.html
8/15/2015 6:52:31 PM - 	Locale          : en-US
8/15/2015 6:52:31 PM - 	MoreInfoURL     : http://xunit.github.io/docs/vsix-deprecated.html
8/15/2015 6:52:31 PM - 	InstalledByMSI  : False
8/15/2015 6:52:31 PM - 	SupportedFrameworkVersionRange : [3.5,)
8/15/2015 6:52:31 PM - 
8/15/2015 6:52:31 PM - 	Supported Products : 
8/15/2015 6:52:31 PM - 		Microsoft.VisualStudio.Ultimate
8/15/2015 6:52:31 PM - 			Version : [11.0]
8/15/2015 6:52:31 PM - 		Microsoft.VisualStudio.Ultimate
8/15/2015 6:52:31 PM - 			Version : [12.0]
8/15/2015 6:52:31 PM - 		Microsoft.VisualStudio.Ultimate
8/15/2015 6:52:31 PM - 			Version : [14.0]
8/15/2015 6:52:31 PM - 		Microsoft.VisualStudio.Premium
8/15/2015 6:52:31 PM - 			Version : [11.0]
8/15/2015 6:52:31 PM - 		Microsoft.VisualStudio.Premium
8/15/2015 6:52:31 PM - 			Version : [12.0]
8/15/2015 6:52:31 PM - 		Microsoft.VisualStudio.Premium
8/15/2015 6:52:31 PM - 			Version : [14.0]
8/15/2015 6:52:31 PM - 		Microsoft.VisualStudio.Pro
8/15/2015 6:52:31 PM - 			Version : [11.0]
8/15/2015 6:52:31 PM - 		Microsoft.VisualStudio.Pro
8/15/2015 6:52:31 PM - 			Version : [12.0]
8/15/2015 6:52:31 PM - 		Microsoft.VisualStudio.Pro
8/15/2015 6:52:31 PM - 			Version : [14.0]
8/15/2015 6:52:31 PM - 
8/15/2015 6:52:31 PM - 	References      : 
8/15/2015 6:52:31 PM - 
8/15/2015 6:52:31 PM - Searching for applicable products...
8/15/2015 6:52:31 PM - Found installed product - Microsoft Visual Studio Ultimate 2013
8/15/2015 6:52:33 PM - The extension with ID 'xunit.runner.visualstudio.Microsoft.623f78dd-6d4b-48f3-a2c7-4bbb381bb146' is not installed to Microsoft Visual Studio Ultimate 2013.
8/15/2015 6:52:33 PM - Found installed product - Microsoft Visual Studio Premium 2013 
8/15/2015 6:52:33 PM - Found installed product - Microsoft Visual Studio Professional 2013
8/15/2015 6:52:33 PM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
8/15/2015 6:52:33 PM - Found installed product - Microsoft Visual Studio Enterprise 2015
8/15/2015 6:52:35 PM - The extension with ID 'xunit.runner.visualstudio.Microsoft.623f78dd-6d4b-48f3-a2c7-4bbb381bb146' is not installed to Microsoft Visual Studio Enterprise 2015.
8/15/2015 6:52:35 PM - Found installed product - Microsoft Visual Studio Professional 2015
8/15/2015 6:52:35 PM - Found installed product - Microsoft Visual Studio Community 2015
8/15/2015 6:52:35 PM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
8/15/2015 6:52:35 PM - Found installed product - Global Location
8/15/2015 6:52:35 PM - Found installed product - ssms
8/15/2015 6:52:37 PM - The following target products have been selected...
8/15/2015 6:52:37 PM - 	Microsoft Visual Studio Ultimate 2013
8/15/2015 6:52:37 PM - 	Microsoft Visual Studio Enterprise 2015
8/15/2015 6:52:37 PM - 
8/15/2015 6:52:37 PM - Beginning to install extension to Microsoft Visual Studio Ultimate 2013...
8/15/2015 6:52:37 PM - Install Error : System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CheckForValidDotNetFramework(IExtension extension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CheckForInstallBlockers(InstallableExtensionImpl extension, IInstalledExtensionList modifiedInstalledExtensionsList, Boolean isNestedExtension, Boolean& olderVersionInstalled)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallInternal(InstallableExtensionImpl extension, Boolean perMachine, Boolean isNestedExtension, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, UInt64 totalBytesToWrite, UInt64& totalBytesWritten)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.BeginInstall(IInstallableExtension installableExtension, Boolean perMachine, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallWorker(IInstallableExtension extension, Boolean perMachine, AsyncOperation asyncOp)
8/15/2015 6:52:38 PM - Beginning to install extension to Microsoft Visual Studio Enterprise 2015...
8/15/2015 6:52:38 PM - Install Error : System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CheckForValidDotNetFramework(IExtension extension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CheckForInstallBlockers(InstallableExtensionImpl extension, IInstalledExtensionList modifiedInstalledExtensionsList, Boolean isNestedExtension, Boolean& olderVersionInstalled)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallInternal(InstallableExtensionImpl extension, Boolean perMachine, Boolean isNestedExtension, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, UInt64 totalBytesToWrite, UInt64& totalBytesWritten)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.BeginInstall(IInstallableExtension installableExtension, Boolean perMachine, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallWorker(IInstallableExtension extension, Boolean perMachine, AsyncOperation asyncOp)
```

**Comment by LianwMS** [comment]
Submit with 14e17e0474174eb0f78c3a063731853eadba53a4
