### ISSUE TITLE
POST with GeographyPoint throws Object must implement IConvertible

### ISSUE THREAD

**Issue by RemcoBlok** [OData/WebApi#718]
I followed this post on [How to consume SQL Spatial Data with Web API V2.2 for OData V4](https://blogs.msdn.microsoft.com/odatateam/2015/01/11/how-to-consume-sql-spatial-data-with-web-api-v2-2-for-odata-v4/). It works fine when querying spatial data. But when I try to POST a new entity that has a GeographyPoint property, the web api odata v4 controller ModelState has an error saying Object must implement IConvertible. Has anyone seen this? Which object needs to implement IConvertable?

Here is the request sent using olingo odatajs-4.0.0.js

```
{
    "requestUri": "/odata/Fields",
    "method": "POST",
    "data": {
        "Block": "Block A",
        "Location": {
            "type": "Point",
            "coordinates": [
                100,
                45
            ]
        },
        "Name": "Field A",
        "ClientId": 1
    },
    "headers": {
        "Accept": "application/json;q=0.9, */*;q=0.1",
        "OData-Version": "4.0",
        "Content-Type": "application/json",
        "OData-MaxVersion": "4.0"
    },
    "recognizeDates": true,
    "callbackParameterName": "$callback",
    "formatQueryString": "$format=json",
    "enableJsonpCallback": false,
    "async": true
}
```

The ModelState for a PATCH contains the same error as well, but the scaffolded code fails before it can check the ModelState as patch is null:

```
        public async Task<IHttpActionResult> Patch([FromODataUri] int key, Delta<Field> patch)
        {
            Validate(patch.GetEntity());

            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

```

thanks,
 Remco

**Comment by RemcoBlok** [comment]
The same issue is present when using the [OData spatial sample](https://github.com/OData/ODataSamples/tree/2eb16717642a26bb0d3e262d9568eb75426237ea/WebApi/v4/ODataSpatialSample).

The stack trace of the error in the ModelState is

```
System.InvalidCastException: Object must implement IConvertible.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Web.OData.Formatter.EdmPrimitiveHelpers.ConvertPrimitiveValue(Object value, Type type)
   at System.Web.OData.Formatter.Deserialization.DeserializationHelpers.SetDeclaredProperty(Object resource, EdmTypeKind propertyKind, String propertyName, Object propertyValue, IEdmProperty edmProperty, ODataDeserializerContext readContext)
   at System.Web.OData.Formatter.Deserialization.DeserializationHelpers.ApplyProperty(ODataProperty property, IEdmStructuredTypeReference resourceType, Object resource, ODataDeserializerProvider deserializerProvider, ODataDeserializerContext readContext)
   at System.Web.OData.Formatter.Deserialization.ODataEntityDeserializer.ApplyStructuralProperty(Object entityResource, ODataProperty structuralProperty, IEdmEntityTypeReference entityType, ODataDeserializerContext readContext)
   at System.Web.OData.Formatter.Deserialization.ODataEntityDeserializer.ApplyStructuralProperties(Object entityResource, ODataEntryWithNavigationLinks entryWrapper, IEdmEntityTypeReference entityType, ODataDeserializerContext readContext)
   at System.Web.OData.Formatter.Deserialization.ODataEntityDeserializer.ApplyEntityProperties(Object entityResource, ODataEntryWithNavigationLinks entryWrapper, IEdmEntityTypeReference entityType, ODataDeserializerContext readContext)
   at System.Web.OData.Formatter.Deserialization.ODataEntityDeserializer.ReadEntry(ODataEntryWithNavigationLinks entryWrapper, IEdmEntityTypeReference entityType, ODataDeserializerContext readContext)
   at System.Web.OData.Formatter.Deserialization.ODataEntityDeserializer.ReadInline(Object item, IEdmTypeReference edmType, ODataDeserializerContext readContext)
   at System.Web.OData.Formatter.Deserialization.ODataEntityDeserializer.Read(ODataMessageReader messageReader, Type type, ODataDeserializerContext readContext)
   at System.Web.OData.Formatter.ODataMediaTypeFormatter.ReadFromStream(Type type, Stream readStream, HttpContent content, IFormatterLogger formatterLogger)
```

**Comment by xuzhg** [comment]
@RemcoBlok Thanks your input. I have a draft fix, would you please take a look my PR #729? Any feedback are welcome.

**Comment by xuzhg** [comment]
@RemcoBlok 
The fix was pushed at 7916898fd45ccf7ce73c87b0c9d3c831274f6527. Would you please try it out and let us know any problem? Thanks your help.

**Comment by premiaware** [comment]
Hello, I have the same problem after upgrade my project from OData 6.xx to OData 7.xx. in the controller Patch method:

public async Task<IHttpActionResult> Patch([FromODataUri] long key, Delta<Immobili> delta)

delta always null when the DbGeography have valid value.

How can is resolve the problem? using OData 6.x all working well.

**Comment by premiaware** [comment]
How can I fix this. Someone can help me using OData7
