### ISSUE TITLE
Support Computed/Immutable/Permission annotation during read and write

### ISSUE THREAD

**Issue by chinadragon0515** [OData/WebApi#739]
Support Computed/Immutable/Permission annotation during read and write

### Assemblies affected
Can be considered as 7.0 lib content

### Reproduce steps
1. Add a property with some annotation line Computed (supported)
2. Any client send a patch request with this property.
3. Server deserialize the request, and should ignore the property.

### Expected result
The computed property for insert and update is ignored.

### Actual result
The computed property is not ignored.

### Additional details
Also add support for Immutable annotation and Permission annotation.

refer to https://github.com/OData/odata.net/issues/574

**Comment by chinadragon0515** [comment]
For properties whose has annotation Computed = true
1.	During query, server should return the computed property and client should serialized the property.
2.	During update/insert, Client may or may not include these properties, but when server receive the request, it should ignore any value from client if property has computed annotation.

For properties whose has annotation Immutable = true (Or this is removed as comments in ODATA-454?)
1.	During query, server should return the Immutable property and client should serialized the property.
2.	During insert, client may or may not include these properties, if client includes the property, the value from client is been used, but if client does not include, it will use value set by server.
3.	During update, Client may or may not include these properties, but when server receive the request, it should ignore any value from client if property has computed annotation.

In case of permission setting, 
1.	 For read, if permission is set to None or wirte (Added with ODATA-732), the property is not returned by server.
If permission is set to read/readwrite, it will be always returned during read.

2.	(Not finalize) For Write, if permission is set to None/Read, then user should not set the value during update, if user set the value and is different from previous value, then unauthorized error code is returned. And during insert, will throw exception if user set the value.
If permission is set to Write/Readwrite, then processed as normal.

**Comment by Danielku15** [comment]
I am currently struggling with a similar problem. Just like in swagger there should be "writeOnly" and "readOnly" properties. Use cases: 
- WriteOnly could be a password of a user which is only writable, but not readable. (not existing in the core OData vocabulary)
- ReadOnly is used for server side computed properties like "DateCreated" of a entity. (aka. Computed)
- WriteOnce could be a username which is not allowed to be changed (aka. Immutable)

I am currently trying to homebrew a solution for this by having own serializers and deserializers + custom logic in the controllers. Mostly it works well but a major issue is with the ODataReader implementation and the nullability of properties. My readOnly properties are sometimes not nullable. But when I try to post an entity without this property set, the ODataReader will complain that the property is null but must not be like that: 

```
"A null value was found for the property named 'property', which has the expected type 'Edm.String[Nullable=False]'. The expected type 'Edm.String[Nullable=False]' does not allow null values."	Microsoft.OData.ODataException
   at Microsoft.OData.ReaderValidationUtils.ThrowNullValueForNonNullableTypeException(IEdmTypeReference expectedValueTypeReference, String propertyName)
   at Microsoft.OData.ReaderValidationUtils.ValidateNullValueAllowed(IEdmTypeReference expectedValueTypeReference, Boolean validateNullValue, String propertyName, Nullable`1 isDynamicProperty)
   at Microsoft.OData.ReaderValidator.ValidateNullValue(IEdmTypeReference expectedTypeReference, Boolean validateNullValue, String propertyName, Nullable`1 isDynamicProperty)
   at Microsoft.OData.Json.ODataJsonReaderCoreUtils.TryReadNullValue(IJsonReader jsonReader, ODataInputContext inputContext, IEdmTypeReference expectedTypeReference, Boolean validateNullValue, String propertyName, Nullable`1 isDynamicProperty)
   at Microsoft.OData.JsonLight.ODataJsonLightPropertyAndValueDeserializer.ReadNonEntityValueImplementation(String payloadTypeName, IEdmTypeReference expectedTypeReference, PropertyAndAnnotationCollector propertyAndAnnotationCollector, CollectionWithoutExpectedTypeValidator collectionValidator, Boolean validateNullValue, Boolean isTopLevelPropertyValue, Boolean insideResourceValue, String propertyName, Nullable`1 isDynamicProperty)
   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadEntryDataProperty(IODataJsonLightReaderResourceState resourceState, IEdmProperty edmProperty, String propertyTypeName)
   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadPropertyWithValue(IODataJsonLightReaderResourceState resourceState, String propertyName, Boolean isDeltaResourceSet)
   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.<>c__DisplayClass9_0.<ReadResourceContent>b__0(PropertyParsingResult propertyParsingResult, String propertyName)
   at Microsoft.OData.JsonLight.ODataJsonLightDeserializer.ProcessProperty(PropertyAndAnnotationCollector propertyAndAnnotationCollector, Func`2 readPropertyAnnotationValue, Action`2 handleProperty)
   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadResourceContent(IODataJsonLightReaderResourceState resourceState)
   at Microsoft.OData.JsonLight.ODataJsonLightReader.StartReadingResource()
   at Microsoft.OData.JsonLight.ODataJsonLightReader.ReadResourceSetItemStart(PropertyAndAnnotationCollector propertyAndAnnotationCollector, SelectedPropertiesNode selectedProperties)
   at Microsoft.OData.JsonLight.ODataJsonLightReader.ReadAtStartImplementationSynchronously(PropertyAndAnnotationCollector propertyAndAnnotationCollector)
   at Microsoft.OData.JsonLight.ODataJsonLightReader.ReadAtStartImplementation()
   at Microsoft.OData.ODataReaderCore.ReadImplementation()
   at Microsoft.OData.ODataReaderCore.ReadSynchronously()
   at Microsoft.OData.ODataReaderCore.InterceptException[T](Func`1 action)
   at Microsoft.OData.ODataReaderCore.Read()
   at Microsoft.AspNet.OData.Formatter.Deserialization.ODataReaderExtensions.ReadResourceOrResourceSet(ODataReader reader) 
   at Microsoft.AspNet.OData.Formatter.Deserialization.ODataResourceDeserializer.Read(ODataMessageReader messageReader, Type type, ODataDeserializerContext readContext) 
   at Microsoft.AspNet.OData.Formatter.ODataInputFormatterHelper.ReadFromStream(Type type, Object defaultValue, IEdmModel model, Uri baseAddress, IWebApiRequestMessage internalRequest, Func`1 getODataRequestMessage, Func`2 getEdmTypeDeserializer, Func`2 getODataPayloadDeserializer, Func`1 getODataDeserializerContext, Action`1 registerForDisposeAction, Action`1 logErrorAction) 
```

It should be allowed to be null on API level, but is then considered not-nullable in the database and in the business logic. The only workaround I found was to make the property nullable because there is no good way to intercept the serialization process. The code is not really designed to allow customization, most of the code is internal or static methods which do not allow overrides. 

I think it should be a proper feature for the next release to support at least the 3 usecases mentioned above. I think they exist in almost any API somehow and require quite some workarounds.

**Comment by mwncidata** [comment]
Is there any update on this at all? Is there any support for adding the `Org.OData.Core.V1.Immutable` annotation on to individual properties in a complex/entity model? This seems like a pretty key missing feature from the OData specification.
