### ISSUE TITLE
$select does not work well with navigation properties

### ISSUE THREAD

**Issue by CzPete** [OData/WebApi#750]
For tables with Choices navigation property (that is being AutoExpanded), query
https://localhost/beta/me/tableDefinitions/TBK6ZUB2GOK8U6N6GZVVFUXDIK/columnDefinitions?$select=displayName
does now work.
However, query
https://localhost/beta/me/tableDefinitions/TBK6ZUB2GOK8U6N6GZVVFUXDIK/columnDefinitions?$select=propertyName,displayName
works (but returns auto-expanded properties as well)

### Assemblies affected
OData 5.9.0-beta

### Reproduce steps
Issue the above query.

### Expected result
Query works and returns a list of all column definitions, each containing displayName property (and nothing else).
### Actual result
Exception:
{
  "error": {
    "code": "",
    "message": "An error has occurred.",
    "innererror": {
      "message": "The 'ObjectContent`1' type failed to serialize the response body for content type 'application/json; odata.metadata=minimal; odata.streaming=true'.",
      "type": "System.InvalidOperationException",
      "stacktrace": "",
      "internalexception": {
        "message": "The entity instance value of type 'Microsoft.TableServices.ChoiceColumnDefinition' doesn't have a value for property 'propertyName'. To compute an entity's metadata, its key and concurrency-token property values must be provided.",
        "type": "Microsoft.OData.Core.ODataException",
        "stacktrace": "
   at Microsoft.OData.Core.Evaluation.ODataEntryMetadataContext.GetPrimitivePropertyClrValue(ODataEntry entry, String propertyName, String entityTypeName, Boolean isKeyProperty)
   at Microsoft.OData.Core.Evaluation.ODataEntryMetadataContext.<>c__DisplayClass2.<GetKeyProperties>b__0(IEdmStructuralProperty p)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.OData.Core.Evaluation.ODataEntryMetadataContext.GetKeyProperties(ODataEntry entry, ODataFeedAndEntrySerializationInfo serializationInfo, IEdmEntityType actualEntityType)
   at Microsoft.OData.Core.ODataWriterCore.EnterScope(WriterState newState, ODataItem item)
   at Microsoft.OData.Core.ODataWriterCore.WriteStartNavigationLinkImplementation(ODataNavigationLink navigationLink)
   at System.Web.OData.Formatter.Serialization.ODataEntityTypeSerializer.WriteExpandedNavigationProperties(IDictionary`2 navigationPropertiesToExpand, EntityInstanceContext entityInstanceContext, ODataWriter writer)
   at System.Web.OData.Formatter.Serialization.ODataEntityTypeSerializer.WriteEntry(Object graph, ODataWriter writer, ODataSerializerContext writeContext, IEdmTypeReference expectedType)
   at System.Web.OData.Formatter.Serialization.ODataFeedSerializer.WriteFeed(IEnumerable enumerable, IEdmTypeReference feedType, ODataWriter writer, ODataSerializerContext writeContext)
   at System.Web.OData.Formatter.ODataMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, HttpContent content, HttpContentHeaders contentHeaders)
   at System.Web.OData.Formatter.ODataMediaTypeFormatter.WriteToStreamAsync(Type type, Object value, Stream writeStream, HttpContent content, TransportContext transportContext, CancellationToken cancellationToken)
-- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.WebHost.HttpControllerHandler.<WriteBufferedResponseContentAsync>d__1b.MoveNext()"
      }
    }
  }
}

### Additional details
This is most likely caused by the AutoExpand behavior and the fact that propertyName is part of the primary key for ColumnDefinition as well as for Choices, the auto-expanded navigation property.

**Comment by chinadragon0515** [comment]
When user select some contained navigation properties, odata .net lib will find it is contained navigation property, It will need to build path for this property, and as it is contained navigation property, its path will contain its parent entity information including key which means something like “columnDefinitions('Color')”, and this need to have the parent entity key property, but parent key property is not included in the feed to be written, and the writer cannot find the key to build the path, it will throw exception.

**Comment by VikingsFan** [comment]
542776115bf900da77f49f40d70a2e7bff016c89
