### ISSUE TITLE
Aggregate errors

### ISSUE THREAD

**Issue by azzlack** [OData/WebApi#788]
Getting the following errors when trying to use an aggregate query.
I'm using the [Chinook database](https://chinookdatabase.codeplex.com/wikipage?title=Chinook_Schema&referringTitle=Home) for tests.

_Tested using Microsoft.AspNet.OData 5.9.1_

**Query: `/album?$apply=aggregate(Track/Milliseconds with sum as TotalMilliseconds)`**

```
The parent value for a property access of a property 'Milliseconds' is not a single value. Property access can only be applied to a single value.","type":"Microsoft.OData.Core.ODataException","stacktrace":"   at Microsoft.OData.Core.UriParser.Parsers.EndPathBinder.BindEndPath(EndPathToken endPathToken)
   at Microsoft.OData.Core.UriParser.Parsers.MetadataBinder.BindEndPath(EndPathToken endPathToken)
   at Microsoft.OData.Core.UriParser.Parsers.MetadataBinder.Bind(QueryToken token)
   at Microsoft.OData.Core.UriParser.Aggregation.ApplyBinder.BindAggregateExpressionToken(AggregateExpressionToken token)
   at Microsoft.OData.Core.UriParser.Aggregation.ApplyBinder.BindAggregateToken(AggregateToken token)
   at Microsoft.OData.Core.UriParser.Aggregation.ApplyBinder.BindApply(IEnumerable`1 tokens)
   at Microsoft.OData.Core.UriParser.ODataQueryOptionParser.ParseApplyImplementation(String apply, ODataUriParserConfiguration configuration, IEdmType elementType, IEdmNavigationSource navigationSource)
   at Microsoft.OData.Core.UriParser.ODataQueryOptionParser.ParseApply()
   at System.Web.OData.Query.Validators.ODataQueryValidator.Validate(ODataQueryOptions options, ODataValidationSettings validationSettings)
   at System.Web.OData.Query.ODataQueryOptions.Validate(ODataValidationSettings validationSettings)
   at Microsoft.AspNet.OData.Extensions.ODataQueryMapper.ODataQuery`1.ValidateQuery() in C:\\Projects\\Microsoft.AspNet.OData.Extensions.ODataQueryMapper\\src\\ODataQueryMapper\\ODataQuery.cs:line 130
   at Microsoft.AspNet.OData.Extensions.ODataQueryMapper.ODataQuery`1.ApplyTo(IQueryable`1 collection) in C:\\Projects\\Microsoft.AspNet.OData.Extensions.ODataQueryMapper\\src\\ODataQueryMapper\\ODataQuery.cs:line 50
   at Microsoft.AspNet.OData.Extensions.ODataQueryMapper.Tests.Repositories.AlbumRepository.<GetAlbums>d__1.MoveNext() in C:\\Projects\\Microsoft.AspNet.OData.Extensions.ODataQueryMapper\\src\\ODataQueryMapper.Tests\\Repositories\\AlbumRepository.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNet.OData.Extensions.ODataQueryMapper.Tests.Functions.AlbumFunctions.<GetAlbums>d__5.MoveNext() in C:\\Projects\\Microsoft.AspNet.OData.Extensions.ODataQueryMapper\\src\\ODataQueryMapper.Tests\\Functions\\AlbumFunctions.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNet.OData.Extensions.ODataQueryMapper.Tests.Controllers.AlbumODataController.<Get>d__2.MoveNext() in C:\\Projects\\Microsoft.AspNet.OData.Extensions.ODataQueryMapper\\src\\ODataQueryMapper.Tests\\Controllers\\AlbumODataController.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
```

**Query: `/artist?$apply=aggregate(Album with countdistinct as TotalAlbums)`**

```
$apply/aggregate expression 'Microsoft.OData.Core.UriParser.Syntactic.EndPathToken' must evaluate to a single value.","type":"Microsoft.OData.Core.ODataException","stacktrace":"   at Microsoft.OData.Core.UriParser.Aggregation.ApplyBinder.BindAggregateExpressionToken(AggregateExpressionToken token)
   at Microsoft.OData.Core.UriParser.Aggregation.ApplyBinder.BindAggregateToken(AggregateToken token)
   at Microsoft.OData.Core.UriParser.Aggregation.ApplyBinder.BindApply(IEnumerable`1 tokens)
   at Microsoft.OData.Core.UriParser.ODataQueryOptionParser.ParseApplyImplementation(String apply, ODataUriParserConfiguration configuration, IEdmType elementType, IEdmNavigationSource navigationSource)
   at Microsoft.OData.Core.UriParser.ODataQueryOptionParser.ParseApply()
   at System.Web.OData.Query.Validators.ODataQueryValidator.Validate(ODataQueryOptions options, ODataValidationSettings validationSettings)
   at System.Web.OData.Query.ODataQueryOptions.Validate(ODataValidationSettings validationSettings)
   at Microsoft.AspNet.OData.Extensions.ODataQueryMapper.ODataQuery`1.ValidateQuery() in C:\\Projects\\Microsoft.AspNet.OData.Extensions.ODataQueryMapper\\src\\ODataQueryMapper\\ODataQuery.cs:line 130
   at Microsoft.AspNet.OData.Extensions.ODataQueryMapper.ODataQuery`1.ApplyTo(IQueryable`1 collection) in C:\\Projects\\Microsoft.AspNet.OData.Extensions.ODataQueryMapper\\src\\ODataQueryMapper\\ODataQuery.cs:line 50
   at Microsoft.AspNet.OData.Extensions.ODataQueryMapper.Tests.Repositories.ArtistRepository.<GetArtists>d__1.MoveNext() in C:\\Projects\\Microsoft.AspNet.OData.Extensions.ODataQueryMapper\\src\\ODataQueryMapper.Tests\\Repositories\\ArtistRepository.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNet.OData.Extensions.ODataQueryMapper.Tests.Functions.ArtistFunctions.<GetArtists>d__5.MoveNext() in C:\\Projects\\Microsoft.AspNet.OData.Extensions.ODataQueryMapper\\src\\ODataQueryMapper.Tests\\Functions\\ArtistFunctions.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNet.OData.Extensions.ODataQueryMapper.Tests.Controllers.ArtistODataController.<Get>d__2.MoveNext() in C:\\Projects\\Microsoft.AspNet.OData.Extensions.ODataQueryMapper\\src\\ODataQueryMapper.Tests\\Controllers\\ArtistODataController.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
```

**Comment by VikingsFan** [comment]
Close as duplicate, please track on this issue https://github.com/OData/WebApi/issues/634
