### ISSUE TITLE
Serialization fails for collection of enum types

### ISSUE THREAD

**Issue by jatin085** [OData/WebApi#916]
Earlier in 5.9.0, we had separate serializers for entity types and complex types. If a complex type contained a collection, it seems we would not call `GetEdmType()` to get actual type of the collection object to be serialized before passing the object to collection-serializer's `CreateProperty()` method.

Now in 6.0.0, since we have a common serializer, we enter method `ODataResourceSerializer.CreateStructuralProperty()` and this in turn calls `GetEdmType()` on the collection object. I have a collection of enum values and the call to `GetEdmType()` fails with exception.

    message: The given model does not contain the type 'System.Collections.ArrayList'.
    stacktrace:
        at System.Web.OData.Formatter.Serialization.ODataSerializerContext.GetEdmType(Object instance, Type type) in ...\OData\src\System.Web.OData\OData\Formatter\Serialization\ODataSerializerContext.cs:line 195
        at System.Web.OData.Formatter.Serialization.ODataResourceSerializer.CreateStructuralProperty(IEdmStructuralProperty structuralProperty, ResourceContext resourceContext) in ...\OData\src\System.Web.OData\OData\Formatter\Serialization\ODataResourceSerializer.cs:line 807

Inside `GetEdmType()`, I can see handling for generic containers with an underlying type that has a mapping to primitive type. e.g. `List<String>`. For the case for which above stack trace is generated, we are passing non-generic object of type `ArrayList`. The type of elements contained in the `ArrayList` is `ODataEnumValue`. Class `ODataEnumValue` is defined in OData Core library. **Currently, neither Web API works with non-generic containers, nor it can map underlying type `ODataEnumValue` to EDM type.** This used to work in Web API 5.9.0.

If in method `ODataResourceSerializer.CreateStructuralProperty()`, I skip getting actual type by replacing line

    if (!propertyType.IsPrimitive() && !propertyType.IsEnum())

with

    if (!propertyType.IsPrimitive() && !propertyType.IsEnum() && !propertyType.IsCollection())

, the error goes away. But I do not think this would be the right fix since `GetEdmType()` can already handle a lot of enumerable objects.

Copying the metadata of object that needs to be serialized below:

    <EnumType Name="ServiceType">
      <Member Name="ThisService" Value="0"/>
      <Member Name="ThatService" Value="1"/>
    </EnumType>

    <ComplexType Name="ServiceCollection">
      <Property Name="Count" Type="Edm.Int32"/>
      <Property Name="Keys" Type="Collection(namespace.ServiceType)" Nullable="false"/>
      <Property Name="Values" Type="Collection(Edm.String)" Nullable="false" Unicode="false"/>
    </ComplexType>

**Please suggest a suitable type to compose the "Keys" object to be serialized as enum collection.**

### Assemblies affected
*OData Web API 6.0*  

### Reproduce steps
*Already covered above.*  

### Expected result
*Enum collection should be serialized without error*.  

### Actual result
*Enum collection serialization causes exception as mentioned above.*  

### Additional details
*Please contact me (Jatin Sanghvi) in case you need more details.*

**Comment by jatin085** [comment]
OData team has answered the question I raised above: **Please suggest a suitable type to compose the "Keys" object to be serialized as enum collection.**. We should represented the non-CLR enum collections as `EdmEnumCollectionObject` objects, and enum values as `EdmEnumObject` object. Closing the issue.
